### ISSUE TITLE
Broken Symlinks with Yarn-Workspaces

### ISSUE THREAD

**Issue by aeweda** [lerna/lerna#3009] opened 2021-10-13 16:30 UTC
## Expected Behavior

i'm using both lerna and yarn workspaces and the expected behavior is lets say i have 2 packages
Package A, Package B
both have react defined inside of them, the typical behavior is that when i do a lerna bootstrap, react gets installed to root and both Package A, Package B, should have a `node_modules` folder with react inside of it as a symlink to the root package

## Current Behavior

currently react hoisted to the root properly but no symlink is created

## Steps to Reproduce (for bugs)

1. root package.json has `workspaces [ "packages/* "] nothing out of the ordinary
2. define react in 2 packages
3. do a lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [],
  "version": "0.0.0",
  "concurrency": 10,
  "mutex": "network",
  "useWorkspaces": true,
  "npmClient": "yarn",
  "npmClientArgs": ["--no-optional"]
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

It's been causing me a huge headache where i sometimes have to isolate certain packages that depend on tools which use different traversal methods that need the packages to be in the local node_modules directory or their symlinks.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.8 |
| `yarn --version` | 1.22.5 |
| `node --version` | 14.14.0 |

| OS | Version |
| Ubuntu | 20.04 |
| NAME | VERSION |

**Comment by monomadic** [comment] 2021-10-17 06:04
I'm possibly getting this issue, along with about a dozen others with lerna. I scratch my head for hours/days wondering how people actually use tools in the node ecosystem when they are so utterly broken like this. It appears to be some linking problem but there are no real error messages, so it's unhelpful.

I'd suggest dropping lerna.

**Comment by revelt** [comment] 2021-11-03 20:42
It's expected behaviour. In short, `react` will be still picked up because:

> "However, when they import modules, Node.js looks for them in the next node_modules higher up in the file tree."
> —https://2ality.com/2021/07/simple-monorepos.html

But there are peculiarities.

## For external deps like `react`

Independently, are you using workspaces or not, the **external dependencies** (like `react`) will be installed in the root `node_modules` and Node will first look in `Package *`, then in the root and it will find `react` there. The symlinking is for internal packages only (see below) — if your `Package A` was using `Package B`, then you'd get a different setup, depending on, are you using workspaces or not. I've just checked.

## For internal deps cross-consuming each other within the same monorepo

- If you use workspaces, the symlink to `Package B` will be created in the root `node_modules` — proof is for example, [this boilerplate](https://github.com/emunhoz/monorepo-boilerplate) — degit, bootstrap and you'll see `@monorepo/design-tokens` are under root `node_modules`
- If you don't use workspaces, the symlink to `Package B` will be created inside the `node_modules` of `Package A` — proof is my npm package [monorepo](https://github.com/codsen/codsen) — again, if you degit, bootstrap and check let's say `packages/detergent/node_modules` you'll find all the symlinks to my own packages like `test-mixer` — they won't be "lifted" to the root `node_modules`.

---

I own both workspaced (for websites/components/design tokens) and non-workspaced monorepos (npm packages), also at the day job (one of the largest e-commerce retailers in UK) I deal with couple more monorepos — all driven by Lerna — and I'm very confident it in as a tool — it's just Lerna is a complex tool, hard to document, I struggled a bit myself when I started using it. Take it slow and be kind.

**Closed as not planned** 2024-09-30 10:55 UTC
Labels: scope: package management
