### ISSUE TITLE
lerna run prints "success" next to failed packages

### ISSUE THREAD

**Issue by DanielSWolf** [lerna/lerna#1997] opened 2019-03-18 14:56 UTC
Let's assume I want to run all unit tests from all packages in my monorepo. So I'd call `lerna run --no-bail test`. I'd specify `--no-bail` because I don't want to abort on the first error. I want to see which packages succeed and which fail. When Lerna is done, it prints a table that looks like this:

> lerna **success** *run* Ran npm script 'test' in 5 packages in 0.3s:
> lerna **success** - package01
> lerna **success** - package02
> lerna **success** - package03
> lerna **success** - package04
> lerna **success** - package05

The problem is that Lerna prints "**success**" next to each package, even if the script for that package actually failed.

## Expected Behavior

I'd expect "**success**" to be printed only if the error code of the packages's script was zero. Otherwise, I'd expect "**failure**" or something similar to be printed next to the failed package.

## Current Behavior

Currently, Lerna prints "**success**" next to every single package, even if its script failed and returned a non-zero exit code.

## Steps to Reproduce (for bugs)

1. Set up a monorepo with multiple packages.
2. Create a script "test" in each monorepo. Make some scripts succeed (by calling "true" on Unix), make others fail (by calling "false" on Unix).
3. Run `lerna run --no-bail test`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "1.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Context

I want to run the same task on all packages (no fail-fast) and see which packages succeeded and which didn't.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by avatarneil** [comment] 2019-05-22 00:01
Even without the `--no-bail` flag I am also seeing `success` messages for packages that have failed test(s). Can you reproduce without that flag set, or is it only in the case that you have the `--no-bail` flag?

**Comment by evocateur** [comment] 2019-05-23 00:06
`success` is the log _level_, not a qualitative assertion of the result. I'm pretty sure the logging when the error occurs would be sufficient?

**Comment by evocateur** [comment] 2019-05-23 00:10
https://github.com/lerna/lerna/blob/285bd7e9dbc2ead8a764e2e64fddb866f70fee86/integration/lerna-run.test.js#L30 indicates that it does run all of the tests despite failures with `--no-bail`, so maybe what you want is the addition of `--stream`?

**Comment by avatarneil** [comment] 2019-05-25 19:01
I discovered that in my `test` script, I was chaining my mocha execution with an nyc coverage report using a `;`. This suppressed the error codes that were being thrown by mocha, so they didn't bubble up through lerna. Changing the `;` to a `&&` resolved the issue for me!

**Comment by jasonmobley** [comment] 2019-09-20 16:28
> `success` is the log _level_, not a qualitative assertion of the result

That is interesting, but I came to same conclusion as @DanielSWolf and came here to report the same issue. I see bunch of green **success** when one of the packages failed the task.

It would be nice to either rename the log levels to not suggest more than they should (e.g. call this "info" rather than "success") or see if there's a way to get the actual success/failure of each package's run result into that final summary.

**Comment by farooqu** [comment] 2019-10-28 13:42
> `success` is the log _level_, not a qualitative assertion of the result. I'm pretty sure the logging when the error occurs would be sufficient?

A problem is that when running with `--no-bail`, only `stdout` is being output, even when there is an error. Further, all output, even for failed packages, use either info or success log levels. This ends up hiding useful output in error cases.

If you run without `--no-bail`, then both `stdout` and `stderr` is printed, along with log level error being used.

Where I just experienced this issue, jest ran all of the unit tests successfully, but failed because of a coverage threshold. The actual error was output to `stderr` by jest, but lerna just dropped it. In ci this makes it much harder to diagnose issues.

If lerna would print `stderr` in failure cases along with `stdout` when using `--no-bail`, and optionally use the error log level, then the logging would be much more useful.

**Comment by jannikbuschke** [comment] 2020-04-30 07:23
I think this does not only happen for tests but any scripts that are executed by lerna? I see typescript errors but the lerna task does not fail in my CI pipeline.

**Comment by buschtoens** [comment] 2020-08-21 08:45
I still believe that this is fundamentally broken. I would expect that `--no-bail`:

- still prints _all_ output (including `stderr`), exactly like without `--no-bail`
- runs _all_ scripts, even if one fails
- prints a summary in the end, where failed packages are logged as such, not as `success`
- returns a non-zero exit code, if any package fails
  - if only one package fails, returns that exit code
  - if more than one package fails, exits with `1` (or something else?)

I would _really, really_ like to fix this, as I think `--no-bail` is basically pretty much useless otherwise, at least to me. Do you think we can / should fix the behavior of `--no-bail` or rather add a new flag and maybe deprecate `--no-bail`?

**Comment by ironicnet** [comment] 2020-08-28 11:53
Hi! just wanted to add to what @buschtoens said. i was expecting the same, or at least get a list of which packages failed.

when running a whole suite of tests in a monorepo, it's almost impossible to follow the stdout or stderr.

not sure what is the use-case of no-bail if it doesn't report errors. so i would suggest to fix it

**Comment by gxmzjxk** [comment] 2021-09-14 03:57
I meet the same issue too and looking forward that it could be fixed !

**Comment by edriwing** [comment] 2021-09-24 12:33
Same issue here.
Any chance to approve the PR by bruderstein up above soon ? :)

**Comment by lumberjack-daniel** [comment] 2021-09-29 20:32
Digging through log files of a huge monorepo across all modules to find a module level failure is very frustrating and cumbersome.

Instead, something like this would be nice when --no-bail is used:

`
timestamp pkg exitcode status
[2021-09-29T20:16:16.299Z] lerna pkg1	0 	success
[2021-09-29T20:16:16.299Z] lerna pkg2   127	failed
[2021-09-29T20:16:16.299Z] lerna pkg3	0  	success
[2021-09-29T20:16:16.299Z] lerna ERR! One or more packages received non-zero exit code during execution
`

**Comment by lumberjack-daniel** [comment] 2021-09-29 20:34
Digging through log files of a huge mono-repo across all packages to determine which package failed is cumbersome.

Instead, something like this would be nice, when `--no-bail` is used:

```
timestamp pkg exitcode status
[2021-09-29T20:16:16.299Z] lerna pkg1	0 	success
[2021-09-29T20:16:16.299Z] lerna pkg2   127	failed
[2021-09-29T20:16:16.299Z] lerna pkg3	0  	success
[2021-09-29T20:16:16.299Z] lerna ERR! One or more packages received non-zero exit code during execution
```

**Comment by jcollum-nutrien** [comment] 2022-02-22 17:03
> Digging through log files of a huge mono-repo across all packages to determine which package failed is cumbersome.

Agreed. I have to just text search for "FAIL" in my build output, which is a little haphazard. Lerna should only be reporting success for zero exit codes. 

Surprised this issue has been open this long with no comments for several months.

**Comment by jcollum-nutrien** [comment] 2022-06-03 23:37
I just hit this issue again and it's stupendously obnoxious.

**Comment by JacobGrishamPowerSchool** [comment] 2022-12-04 19:48
I ran into this issue as well. I was experiencing this while running tests for our monorepo in our automated CI/CD pipeline. The output log from our CI/CD showed that Lerna reported all tests as passing with 100% code coverage. However, it would also show `lerna ERR! Received non-zero exit code 1 during execution` and therefore caused the CI/CD unit test step to fail.

I had to search hard for the actual error in my local machine's dev environment. I ran the unit tests individually (without lerna) for each package within the monorepo, and finally discovered the error. Lerna did not give the same error output as the individual package test. In effect, it was suppressing the error.

It took a while to discover that the lerna tool was the issue and that I could not rely on it to give me accurate observability on my tests. 

Hopefully, with enough people reporting this issue, it will get prioritized.

**Comment by JamesHenry** [comment] 2023-02-17 08:20
Hi Folks,

I am going to close this one as this issue is not present with the modern task runner that was added as opt-in in v5, and has been the default since we released v6 last year.

The legacy task runner implementation of `lerna run` was much more simplistic and delegated some key logic to some promise handling libraries called `p-map` and `p-queue`.

The modern task runner not only produces more readable output, it also is capable of [deterministic caching](https://lerna.js.org/docs/features/cache-tasks) and [powerful task pipeline](https://lerna.js.org/docs/concepts/task-pipeline-configuration).

Please simply upgrade to the latest version and take a look at those linked docs to enjoy these benefits.

If you do run into any more issues with `lerna run` please open a fresh issue with as much information as possible.

Thanks all!

**Closed by JamesHenry** 2023-02-17 08:20 UTC

**Comment by kumavis** [comment] 2024-10-03 01:12
fwiw im seeing this on lerna `8.1.8`

with `--no-bail`:
```
lerna ERR! Received non-zero exit code 1 during execution
lerna success run Ran npm script 'test' in 39 packages in 42.6s:
lerna success - @endo/base64
lerna success - @endo/bundle-source
[...]
lerna success - ses
[...]
```

without `--no-bail`:
```
lerna ERR! yarn run test exited 1 in 'ses'
```
