### ISSUE TITLE
Conventional Commit with Fixed versioning

### ISSUE THREAD

**Issue by codeNoobie** [lerna/lerna#1383] opened 2018-04-18 07:34 UTC
Do we support publish with conventional-commits for fixed versioning?

**Comment by codeNoobie** [comment] 2018-04-18 16:39
Okay. Then help me identify if below is a bug or an expected behavior.

I have two packages currently managed by lerna. I am using default versioning with conventional commit. I am ensuring that commit messages are in conventional commit format. After every commit, I run the below command.

`lerna publish --conventional-commits --changelog-preset angular-bitbucket --skip-npm --yes`

Let's say the initial versions are:
```
package-1 -> 0.0.0
package-2 -> 0.0.0
```

For any commit, that requires minor and patch version update according to conventional commits guidelines, Lerna correctly the versions of all packages even those which did not have any change since the last release. This is good.

But when i create a Breaking Change commit which only modifies one package, say package-1,  the above Lerna publish command only updates the major version of package-1. But, package-2's version is not modified. I would expect the major version of package-2 to be modified as well.

```
package-1 -> 1.0.0
package-2 -> 0.0.0
```

Now I create another patch commit involving only package-1. This time, all the package versions are now modified. Moreover, the major version of package 2 also gets updated.
It does successfully update the version of

```
package-1 -> 1.0.1
package-2 -> 1.0.1
```

Is this an expected behavior? If not, am i missing something with config or this is indeed a bug?

Here is my lerna.json:

```
{
  "lerna": "2.10.2",
  "packages": [
    "libs/*",
    "studio"
  ],
  "commands": {
    "publish": {
      "conventional-commits" : "true"
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "loglevel": "silent"
}
```

```
yarn -version
1.5.1

node -v
v9.8.0

lerna -v
2.10.2

OsX High sierra
```

**Comment by evocateur** [comment] 2018-04-18 16:57
This would have been useful information to include in the original bug report.

**Comment by evocateur** [comment] 2018-04-18 16:58
Why the `--skip-npm`? Probably not the cause, but definitely odd, if you do it after _every_ commit.

**Comment by codeNoobie** [comment] 2018-04-18 17:45
@evocateur  Yes, I agree I should have added the details with the original description.

I am in the process of setting up a new Angular 5 mono repo. The two lerna packages are component libraries. We are using https://github.com/dherges/ng-packagr to transpile and build the distribution in Angular Package format. This is an important use case for us. 

Lerna publish doesn't support publishing a folder/tarball within a package. I have seen few threads on these in Lerna forum and I understand that the Lerna team is against providing this use case. But it is also important for us to publish the transpiled package. So I am trying to work around these requirements. 

`Lerna publish --skip-npm` would take care of the version upgrade, git tag and changelog creation. I would then run a separate script to build these transpiled packages and publish them separately to our private repository. Currently, I am in the process of building this flow.

Lerna has helped us with a lot of our use case. Thanks for actively maintaining it!

**Comment by codeNoobie** [comment] 2018-04-18 20:49
@evocateur  I tried digging into the code myself. Here is what I found. 

Below line is updating pkg's version to the global version in Fixed mode. It is iterating over the pkgs in this.updates. 
[https://github.com/lerna/lerna/blob/9879fef6b8adc4f314919d4e8f18041d69558a45/commands/publish/index.js#L319](Publish Cmd: Line 319)

If we go to line 126, we can see that this.updates contains the list of packages that are updated.
[https://github.com/lerna/lerna/blob/9879fef6b8adc4f314919d4e8f18041d69558a45/commands/publish/index.js#L126](Publish Cmd : Line: 126)

This could be the reason for my issue. It seems like for Fixed mode, we should be iterating over all packages instead of the updated ones. 

Thoughts?

**Comment by evocateur** [comment] 2018-04-19 17:13
> It seems like for Fixed mode, we should be iterating over all packages instead of the updated ones.

I think you're right, logically, but in practice, it's mostly an aberration around how we handle major version bumps. I would definitely expect a conventional major bump in a fixed repo to bump all packages.

...and as far as I can tell, it kinda means we would have to refactor `collect-updates` to take into account the `recommendVersions()` logic ...somehow. Oy.

Right now, a workaround exists (for fixed versioning), although it is regrettably not exactly automatic: When you _know_ there is a breaking change, pass `--force-publish` to `lerna publish --conventional-commits`, and it should(?) ensure that all packages are bumped to the new major. I haven' tested it, so caveat emptor.

**Comment by codeNoobie** [comment] 2018-04-21 00:25
Thanks Daniel!

This works. Although, are you planning to fix this as a bug in the current version or the upcoming version? I can attempt at submitting a PR for this change.

**Comment by bochen2014** [comment] 2018-04-21 14:25
this is definitely a big issue and should be fixed.  Thanks for raising it up here. 

I created a PR https://github.com/lerna/lerna/pull/1391  for it

**Comment by codeNoobie** [comment] 2018-04-23 17:30
I would wait for this fix to go in. :)

**Closed** 2018-05-03 16:16 UTC
