### ISSUE TITLE
performance regression after switching to using symlinks

### ISSUE THREAD

**Issue by aaronabramov** [lerna/lerna#344] opened 2016-09-23 17:41 UTC
hey! we updated Jest to use `lerna@2.0.0-beta.28` and it increased the running time of our test suite form `<30s` to `45s` on average.

see https://github.com/facebook/jest/issues/1784
it also can be reproduced here https://github.com/facebook/jest/pull/1785

**Comment by thejameskyle** [comment] 2016-09-23 22:01
Does a lerna command run as part of the test suite?

**Comment by cpojer** [comment] 2016-09-24 08:55
Lerna doesn't run as part of a test run so I'm gonna assume the slowdown happens because the symlinks are so deep that analyzing the entire repo takes more time?

Could we bring back the symlinking as an option?

**Comment by thejameskyle** [comment] 2016-09-26 22:49
Yeah, it probably should have been made an option.

Is there something you can do to improve the performance of symlinks in Jest though?

**Comment by AlastairTaft** [comment] 2016-11-15 05:33
+1 for optional symlinking

**Comment by marionebl** [comment] 2017-11-18 08:14
@aaronabramov @cpojer Is this still applicable? `jest` appears to have upgraded to stable releases in the meantime: [facebook/jest/lerna.json#L2](https://github.com/facebook/jest/blob/3d84d75374d23b035cc87cba14afaa7b761273b7/lerna.json#L2)

**Comment by cpojer** [comment] 2017-11-18 08:20
I guess we are surviving with this regression even if it's not good. Regardless, we are now using Yarn's workspaces to link things so this is not up to Yarn any more. Feel free to close this.

**Closed** 2017-11-19 21:45 UTC
