### ISSUE TITLE
[2.0.0] publish creates a tag even when there are no changes

### ISSUE THREAD

**Issue by nevir** [lerna/lerna#912] opened 2017-07-09 17:35 UTC
## Expected Behavior

When publishing and there are no changes; lerna should no-op.

## Current Behavior

When running `lerna publish` when there are no changes to any package, it attempts to create a tag `vundefined`:

```
Releasing 1.1.204
lerna info version 2.0.0
lerna info current version 1.1.0
lerna info Checking for updated packages...
lerna info Comparing with v1.1.196.
lerna info No updated packages to publish. 
lerna ERR! execute Error: fatal: tag 'vundefined' already exists
```

## Steps to Reproduce

1. Make some change outside of `packages`
2. `lerna publish` and notice that the tag `vundefined` is created
3. Make some more changes outside of `packages`
4. `lerna publish` and see the output above.

## Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | v6.10.1 |

```json
{
  "lerna": "2.0.0",
  "version": "1.1.0",
  "packages": [
    "packages/*",
    "test/output/functional"
  ]
}
```

**Comment by userpixel** [comment] 2017-07-12 11:11
I have the same issue with NPM `5.0.3` and Lerna `2.0.0`.
It actually goes ahead and creates a `vnull` and `vundefined`.

### Example repo
https://github.com/userpixel/monorepo/releases

**Comment by dtothefp** [comment] 2017-08-17 21:19
I have the same issue, on top of this the `version` line will be removed be removed from `lerna.json`. This is bad if `vnull` or `vundefined` have not yet been pushed as the lerna.json missing the version will be pushed with the tag.

<img width="854" alt="screen shot 2017-08-17 at 2 13 48 pm" src="https://user-images.githubusercontent.com/4656726/29434251-20b10240-8357-11e7-9114-4a6422a323c6.png">

**Comment by evocateur** [comment] 2017-08-23 20:52
closing as a duplicate of #853

**Closed by evocateur** 2017-08-23 20:52 UTC
Labels: duplicate
