### ISSUE TITLE
Root package.json's version not bumped after running `lerna version`

### ISSUE THREAD

**Issue by DrakeWitt** [lerna/lerna#2879] opened 2021-04-19 19:44 UTC
Upon running `lerna version` in a fixed/locked mode project, all of the package's versions are updated, but the root package's version is left unchanged. The exact command I am running is `lerna version --no-push --force-publish --conventional-commits`, although I experienced the same behavior without the flags. I am including "no-push" and "force-publish" as I'm not changing any files and just testing, so I don't want it pushed yet. The commit's tag is the correct version though. 

Perhaps I am missing something from the docs, any help would be greatly appreciated.

## Expected Behavior
The root `package.json` should have its version changed to match the children's `package.json` version.

## Current Behavior
The version in the root `package.json` remains the same while the version in the children are updated.

## Steps to Reproduce (for bugs)
1. Work in a lerna repo
2. Run `lerna version --no-push --force-publish --conventional-commits`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.2.0-beta.38"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.11 |
| `yarn --version` | N/A |
| `node --version` | v12.18.4 |

| OS | Version |
| --- | --- |
|Manjaro Linux | 21.0.1|

**Comment by johnsoncodehk** [comment] 2021-09-03 12:57
lerna.json:

```json
{
  "packages": [
    ".",
    "packages/*"
  ],
  ...
}

```

root package.json:

```json
{
  "private": true,
  ...
}
```

**Comment by filipw01** [comment] 2021-11-18 07:21
I have the same issue. Above solution didn't help 
Likely duplicate of #2153

**Comment by dlqqq** [comment] 2023-03-04 16:57
In addition to the snippet from @johnsoncodehk, I had to tell Nx to not include any root package scripts as Nx targets, because I used NPM scripts as a shorthand for `lerna run`, e.g. `yarn build` calls `lerna run build`. Declaring the root package as a workspace caused an infinite loop as `lerna run build` would call `yarn build` on the root package, which called `lerna run build`, etc.

The solution was to leverage the `nx.includedScripts` field and add the following to `package.json`:

```
  "nx": {
    "includedScripts": []
  }
```

This tells Nx to not include NPM scripts as Nx targets, which means `lerna run build` never runs on the root package. In summary, I recommend the following configuration in `package.json`:

```
{
  ...,
  "private": true,
  "workspaces": [".", "packages/*"],
  ...,
  "nx": {
    "includedScripts": [],
    ...
  },
  ...
```

I definitely think the root package version should be bumped by default rather than having to declare it as a workspace. Most build tools that need to determine the "package version" do not respect the value in `lerna.json` and look for the value in the root `package.json`. If this is not being implemented purely out of concern with sticking to strict "design principles", then that is equivalent to saying "we won't play nice with other build tooling".

**Comment by JamesHenry** [comment] 2023-03-16 09:36
Hi Folks 👋 

Referencing your root package.json as if it is one of your workspaces (using `.`) is not desirable as it creates a very confusing and non-representative project graph, and has knock on effects on script targets.

This is the only reason why @dlqqq needed to add `includedScripts`, because of treating the root package.json like it is a project on the project graph. Please don't do this. 

The source of truth for the version of the workspace when publishing in lock step is the `lerna.json`. The root `package.json` does not require a version for any publishing purpose because it is never published, so the most appropriate thing is to remove the version field from it (making sure it has `"private": true` as well).

Hope that helps!

**Closed by JamesHenry** 2023-03-16 09:36 UTC
