### ISSUE TITLE
Lerna run errors if there is no package to execute on it after ignore

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#1065] opened 2017-10-10 16:21 UTC
Lerna will throw an error if you execute an npm script and there are no packages with the provided script AFTER ignoring one package.

## Expected Behavior

I want it to provide a friendly message and nothing else. This already  happens if you don't ignore any package.

## Current Behavior

Lerna will throw an error, which is far from ideal in my case.

## Possible Solution

I don't see why this should throw an error. For example, if you use `lerna run test` and there is no package with tests it will not fail, but if you do the same specifying an `--ignore` flag it will throw an error.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 4.1.2 |
| `node --version` | 7.7.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by danielo515** [comment] 2017-10-27 10:36
Any comment about this potential bug ?

**Comment by evocateur** [comment] 2017-10-27 17:07
Quite likely a bug. A minimal repro in a unit test would be a great PR (don't worry about fixing, necessarily).

**Comment by cdtinney** [comment] 2018-10-28 02:06
I can't reproduce this.

```
λ lerna run foo
info cli using local version of lerna
lerna notice cli v3.4.3
lerna info versioning independent
lerna success run No packages found with the lifecycle script 'foo'

**Comment by danielo515** [comment] 2019-02-25 18:41
Oh stale-bot, you are so lack of context...

**Comment by abh1** [comment] 2021-10-12 23:40
Same issue

**Comment by JamesHenry** [comment] 2022-11-29 11:27
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏

**Closed by JamesHenry** 2022-11-29 11:27 UTC
