### ISSUE TITLE
Link and publish not the package directory but it's child `dist` folder instead

### ISSUE THREAD

**Issue by Kamilius** [lerna/lerna#1282] opened 2018-02-23 07:16 UTC
Currently `$ lerna publish` as well as `$ lerna bootstrap` is publishing whole package folders with source files. The problem with this is that I need to publish not the package folders, but their `dist` folders instead, as well as using those `dist` folders as symlink source while using `$ lerna link/bootstrap`

## Expected Behavior
Ability to configure `publish` and `link` sources to make those operations specifically over built `dist` folders, but not over packages themselves. Ability to run `bootstrap run npm-script` should still be executed where it is now.

## Current Behavior
`publish` and `link` are publishing and linking whole packages with all of development related files

## Steps to Reproduce (for bugs)
1. go to `lerna` root
2. run `$ lerna bootstrap`
3. symlinks for packages are leading to other packages folders, not to those package's `dist`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/*"
  ],
  "version": "2.0.0-beta-1",
  "npmClient": "yarn"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.3 |

| OS | Version |
| --- | --- |
| MacOS High Sierra | 10.13.3 (17D47) |

**Comment by evocateur** [comment] 2018-02-23 19:53
This is what the package.json [`files`](https://docs.npmjs.com/files/package.json#files) and [`main`](https://docs.npmjs.com/files/package.json#main) fields are for.

```json
{
  "name": "my-leaf-package",
  "version": "1.0.0",
  "main": "dist/index.js",
  "files": [
    "dist"
  ],
  "dependencies": {}
}
```

**Comment by skidding** [comment] 2018-03-14 09:27
@evocateur do you know of any reason why Lerna would publish files outside `package.json#files`? I'm experiencing this but only in some cases.

- [`files` NOT including src](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-test/package.json#L7-L11)
- `src` gets published
  
![image](https://user-images.githubusercontent.com/250750/37393727-7b84adf6-27a4-11e8-8e33-d0327b7a2aee.png)

Any pointer to how to debug this is very appreciated! Related: https://github.com/react-cosmos/react-cosmos/issues/611

**Comment by evocateur** [comment] 2018-03-14 14:45
As I suspected, you’re using yarn to publish, so that’s a yarn bug. I’ve never been impressed by yarn’s publish command, especially the files array handling. Lerna just calls `yarn publish`, it does not do anything that would affect tarball packaging.

**Comment by jbgraug** [comment] 2018-03-22 09:26
Same here.
I have a local library with 
`
"files": [
        "dist/"
    ],
`
But when running `lerna link` or `lerna bootstrap`, the library gets symlinked to the main library folder, not the to the dist/ one

**Comment by evocateur** [comment] 2018-03-22 15:58
That’s because your “main” property is wrong. It should be pointing to a file under dist, not lib.

**Comment by jbgraug** [comment] 2018-03-22 16:31
I also tried this, the problem is the liking part as is not the same linking the root folder than linking **dist/** because the root folder contains a different node_modules folder with devDependencies which are resolved instead of the main project ones.

**Comment by evocateur** [comment] 2018-03-22 16:38
I didn't see your edit in my email, so my comment isn't valid, sorry. You're using "root" in the context of a leaf package, not the _actual_ lerna root, and that confused me.

Why can't Angular just behave like literally hundreds of thousands of other npm packages? Why is it a special snowflake? It's kind of ridiculous, to be quite frank. Lerna will never support the `"packages/your_package_1/dist"` package spec because it isn't going to cater to an ornate "solution" that ignores almost a decade of precedent.

**Comment by evocateur** [comment] 2018-03-22 18:26
Literally nothing in that linked page describes a _requirement_ for publishing a generated `package.json` in a `dist` subdirectory.

> publishing the a dist/ folder is quite common practice

As a member of the package tarball, as specified in the _original_ package.json by the `files` array, `main` pointing to `dist/{something}.js`, and built during `prepare`/`prepublishOnly` lifecycles, sure. Demanding a separate `cd ./dist` before running `npm publish` is _not_ common in the greater npm ecosystem.

**Comment by jbgraug** [comment] 2018-03-22 18:59
I guess it is just a thing people "usually" do to separate src from built code, cd to dist/ or whatever folder, and then publish from there instead of making use of .npmignore 

What about devDependencies, peerDependecies, etc in package.json? 
Why have them if they are not respected? locally you have the dev. dependencies installed, and then, when you do npm link you have them all in your main project. This will not happen if the package is published and then installed from the npm registry. This is not consistent, is it?

Keep in mind how TypeScript module resolution works.

**Comment by vilic** [comment] 2018-03-23 17:19
For TypeScript projects that needs multiple entries (e.g. `hello`, `hello/world`), it is usually painful to manage extra `.js` and `.d.ts` files just for creating those entries. It would be nice for lerna to support that.

**Comment by evocateur** [comment] 2018-04-27 17:36
I'm getting really good at linking this: https://docs.npmjs.com/files/package.json#files

There you go. Problem solved.

But hey, @johnmcase, feel free to insult me, that's a good strategy for convincing me to do something. I've given my reasons over and over again, and they haven't changed. Have fun forking.

**Closed by evocateur** 2018-04-27 17:36 UTC

**Comment by johnmcase** [comment] 2018-04-27 17:46
This is why that doesn't work:

![image](https://user-images.githubusercontent.com/314819/39376903-ecb7cf9e-4a18-11e8-872f-278070a1bd39.png)

**Comment by evocateur** [comment] 2018-04-27 17:47
Your package.json doesn't include the right dependencies? That seems like a problem independent of lerna.

**Comment by nfour** [comment] 2018-05-09 02:57
@doug-wade Here is the usecase at my company:

```
build/
  foo.js
  foo.d.ts
  bar.js
  bar.d.ts
  package.json
src/
  foo.ts
  bar.ts
package.json
```

Now imagine that `foo` and `bar` contain related but highly import-intensive stuff. 

Lets say `foo` imports an absolute shitload of schemas or something.

Typically we have imports like so to solve this:

```ts
import reallyExpensiveFooImport from "npm-package/foo";
import cloneDeep from "lodash/cloneDeep";
import schema from "@company/schemas/entity/something-+v1";
```

If we were to use the standard layout, which has `package.json` point to `build/index.js` we would have these import paths:

```ts
import reallyExpensiveFooImport from "npm-package/build/foo";
import cloneDeep from "lodash/build/cloneDeep";
import schema from "@company/build/schemas/entity/something-+v1";
```

This is aesthetically displeasing, can be confusing (is it dist or build or lib?) and some people exclude all `/build/` from indexing etc.

This is the real reason to support this, and it's sad that NPM had this feature at one point with special files denoting the root, but has since disappeared.

**Comment by nfour** [comment] 2018-05-10 00:50
It also isn't just about publishing

`yarn link`'ed modules need to point to the build folder as well.

**Comment by evocateur** [comment] 2018-05-10 00:55
This is why Angular is wrong to promote publishing from a generated subdirectory. `npm link` (or yarn, whatever) will literally never work with this ridiculous pattern.

**Comment by dherges** [comment] 2018-06-20 18:30
It's simply not ridiculous but rather should have been an established pattern.

`npm link` is flawed either way. Its benefit was to introduce `--preserve-symlink` flags all over the place.

**Comment by pterblgh** [comment] 2018-07-08 16:53
I guess the main use case for people from the Angular ecosystem is to be able to easily publish packages generated by ng-packagr which is now the default tool used in Angular CLI to generate and build libraries.

I can imagine a use-case for a big project with multiple companies and 20-30+ developers to decide to go with a monorepo backed by Lerna and split the features into multiple NPM packages which are versioned independently and published to a private NPM repository. I guess a lot of big projects already or will follow a setup similar to this because creating Angular libraries _efficiently_ has now become a thing.

I guess many more questions and feature request are going to come up for publishing a dedicated folder (e.g. `dist`) because the Angular (maybe more generally the TypeScript) ecosystem follows this pattern.

@evocateur I clearly understand your reasons, but would you take in consideration adding another argument to the `lerna publish` command which can be used as the first argument of the official `npm publish` command. Maybe you can call it `--folder` because [NPM uses the same name](https://docs.npmjs.com/cli/publish) too.

By the way I'm just getting familiar with Lerna, but I guess the following commands can form a workaround for the main problem:
```bash
lerna publish --conventional-commits --skip-npm
```

```bash
lerna exec --concurrency 1 --scope=@my-org/* -- npm publish dist
```

In the `prepublish` hook anyone can define a proper build process to populate the dist folder correctly.

Am I missing something important somewhere? Thank you for your time to read my idea/proposal.

**Comment by evocateur** [comment] 2018-07-09 18:39
@pterblgh I don't see anything in the "Angular Package Format" spec that _requires_ publishing from a subdirectory. It's also not clear to me why a leaf package.json needs to be mangled at all?

**Comment by pterblgh** [comment] 2018-07-09 19:00
Hmm maybe I'm missing something from the bigger picture.

If I have a repository containing source files which require some kind of transpilation (it can be TypeScript, Babel or basically everything else which takes a language and transpiles it to some valid JavaScript) what's the best practice to publish it to NPM as a JavaScript module?

**Comment by evocateur** [comment] 2018-07-09 22:19
[`files`](https://docs.npmjs.com/files/package.json#files) + [`main`](https://docs.npmjs.com/files/package.json#main), same as it's always been. `src/index.js` transpiles to `dist/index.js`, `"main": "dist/index.js"`, `"files": ["dist"]`. I've been told that's not good enough for Angular, but I don't see why all the other semi-ludicrous "phesom" variants and their myriad package.json properties can't always be present in the package.json and outputs `.gitignore`ed and whitelisted in the `files` array.

**Comment by dherges** [comment] 2018-07-10 08:42
While there are points for and against it, the very first action is to [care about a toxic tone problem](https://compassionatecoding.com/blog/2016/8/25/tech-has-a-toxic-tone-problemlets-fix-it). First step first.

**Comment by evocateur** [comment] 2018-07-11 00:45
I appreciate the reminder to speak with compassion. I hope you can appreciate how difficult it is to do as the only active maintainer of a mildly popular project who also happens to have a day job and a seven month-old.

I found http://neugierig.org/software/blog/2018/07/options.html to be very timely, relevant reading. I think I have made it clear where I draw the line for Lerna. I hear Rush (Microsoft monorepo tool, not the band) handles the kind of subdirectory build pattern you’re after.

**Comment by wanglong167** [comment] 2018-07-12 05:42
https://github.com/sindresorhus/np    --contents    Subdirectory to publish

**Comment by lawlesscreation** [comment] 2018-08-03 15:49
@evocateur firstly thanks for working on Lerna - it's been a great tool for us to breakdown our CSS design system and publish as multiple packages!

We've hit this same problem and not entirely sure if there's a workaround. We have a package containing angular components, when this gets build with ng-packagr it puts the package files in a `dist/` folder, as many have described.

<img width="304" alt="screen shot 2018-08-03 at 16 40 00" src="https://user-images.githubusercontent.com/299914/43652081-124f68b4-973c-11e8-9788-076ca184acb0.png">

We've tried several methods you have suggested but sadly no success. There is no `index.js` that gets created to add to the package.json `main` and we don't seem to be able to simply include the `dist/` folder in the package.json `files` list because there is a package.json file within the `dist/` folder, which seems to cause many folder/files to be ignore in the package - I guess because it thinks this is some weird package-in-a-package!?

Hopefully someone can suggest a workaround for this, until then I guess the only think we can do is have Lerna ignore this package and we'll manage/publish it separately.

**Comment by lawlesscreation** [comment] 2018-08-06 08:17
For anyone interested, the least hacky workaround I could come up with was to disable lerna publish from actually publishing the packages with `--skip-npm` then writing a custom publish command for each package that is called as part of a post script e.g.:

```
// main package.json
"lerna:publish": "lerna publish --conventional-commits --yes --skip-npm",
"postlerna:publish": "lerna run publish:custom",
```

```
// In the angular package because it needs to be published from ./dist/
"publish:custom": "npm publish dist"
```

```
// In every other package.json that publishes from its root folder
"publish:custom": "npm publish"
```

**Comment by lawlesscreation** [comment] 2018-08-13 15:29
hmm, the above approach has the problem that it doesn't use Lerna to publish which means it tries to publish packages that have not changed.

The only option that seems to work without completely recreating the lerna publishing lifecycle is to create a `prepublishOnly` step (npm >= v4), which copies the `dist` files into the `src` folder before it's packs and publishes:

```
// package.json

{
  ...
  "scripts": {
    "prepublishOnly": "cp -r ./dist/* ."
  }
  "files": [
    "bundles",
    "esm5",
    "esm2015",
    "fesm5",
    "fesm2015",
    "lib",
    "angular-components.d.ts",
    "angular-components.metadata.json",
    "index.d.ts",
    "public_api.d.ts"
  ]
}
```

This feels a little dirty as copying compiled files to a source folder gives me shivers - luckily this is part of a CI pipeline that cleans up the checkout each time anyway!

@evocateur it's a shame we cannot specify the folder Lerna should publish from as per the [npm publish [folder]](https://docs.npmjs.com/cli/publish) documentation - it would make it a lot easier 👍 I understand you not wanting to support every possible use-case but I would have thought this is a problem for anyone using Lerna + Angular.
