### ISSUE TITLE
Running `lerna publish` results in bogus commit message

### ISSUE THREAD

**Issue by nicojs** [lerna/lerna#712] opened 2017-03-23 07:30 UTC
Running `lerna publish` results in a bogus commit message: "$(echo Publish"

## Possible Solution
Commit message using echo might not work as expected on windows:
https://github.com/lerna/lerna/blob/e4b74a63b87cab618d1ae9256d1186104977d6ac/src/GitUtilities.js#L31

If i open cmd and run `echo "test"`: i see `"test"` instead of `test`.

## Steps to Reproduce (for bugs)

1. Run `lerna publish` on a windows machine

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
No lerna debug file present.
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38-40-g203f7eb|
| `npm --version`  | 3.8.2|
| `yarn --version` | - |
| `node --version` | 7.5.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment] 2017-03-23 17:14
Thanks for the bug report! I'm going to close this as a duplicate of #552, but I hope you understand we're not ignoring Windows folks on purpose.

#551 is one effort to fix this, but it is unfortunately not a complete fix (and out of date, to boot). I would love to see the [temp file fix](https://github.com/CogniStreamer/lerna/commit/e8a0ea8e5e258702883ba5b2fb791654cd555121) described in [this comment](https://github.com/lerna/lerna/pull/551#issuecomment-286258814) to be implemented, but I've got a lot on my plate and I'm not sure when I'll be able to get to it.

**Closed by evocateur** 2017-03-23 17:14 UTC
