### ISSUE TITLE
lerna cannot locate packages after update from v7 to v8

### ISSUE THREAD

**Issue by wasib-sureify** [lerna/lerna#3964] opened 2024-03-05 06:24 UTC
## Current Behavior
Cannot find packages after updating to lerna v8. 
We have been using lerna with pnpm workspaces and everything used to work fine. Today I updated lerna to v8 and all of a sudden lerna stopped identifying any packages. Reverting lo lerna v7 makes everything run correctly again.

This is what it shows when I run lerna list
<img width="315" alt="image" src="https://github.com/lerna/lerna/assets/55182149/6e0090bd-2038-42fc-aee6-e26dfafa9dfc">

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
`{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "npmClient": "pnpm",
  "version": "independent",
  "command": {
    "version": {
      "createRelease": "github",
      "conventionalCommits": true,
      "allowBranch": ["main", "*-hotfix"],
      "message": "chore(release): publish [skip ci]"
    }
  }
}
`
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by apedroferreira** [comment] 2024-03-11 20:21
I've got the same issue, seems to be related to the `nx` dependency update.

**Comment by JamesHenry** [comment] 2024-03-18 09:20
@apedroferreira I do not encounter any errors when using your repo:

![image](https://github.com/lerna/lerna/assets/900523/a1a5f723-9f53-4180-b9e5-669408610c14)

**Comment by JamesHenry** [comment] 2024-03-18 09:21
@wasib-sureify `npx lerna info` was requested in the issue template and would be helpful in figuring out what is going on, please kindly provide it or steps to reproduce the issue

**Comment by JamesHenry** [comment] 2024-03-18 10:22
@DannyS-Treetop did you try deleting all node_modules directories and recreating the lock file from scratch?

**Comment by apedroferreira** [comment] 2024-03-18 13:27
> @apedroferreira I do not encounter any errors when using your repo:

It seems like my colleagues also don't have the issue, just me. Must be something about my environment.

Here's what I get for `npx lerna info` in the reproduction repository i provided:

```
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Utilities:
    Git: 2.43.1 - /usr/local/bin/git
  npmPackages:
    lerna: ^8.1.2 => 8.1.2
```

**Comment by wasib-sureify** [comment] 2024-03-20 06:59
> @wasib-sureify `npx lerna info` was requested in the issue template and would be helpful in figuring out what is going on, please kindly provide it or steps to reproduce the issue

Here is my response for `npx lerna info`

```
lerna notice cli v8.1.2
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M3 Pro
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Utilities:
    Git: 2.39.3 - /usr/bin/git
  npmPackages:
    lerna: 8.1.2 => 8.1.2 
    ```

**Comment by wasib-sureify** [comment] 2024-03-20 07:18
@DannyS-Treetop I also tried deleting the .git folder and it did not seem to help either. `npx lerna list` still does not list any packages. 

What's strange is that `pnpm install` seems to see all the packages but none of the other commands work.

pnpm install output:
```
pnpm i
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +19
+++++++++++++++++++
Done in 936ms
```

npx lerna list output:
```
npx lerna list
lerna notice cli v8.1.2
lerna info versioning independent
lerna success found 0 packages
```

**Comment by JamesHenry** [comment] 2024-03-22 16:14
@apedroferreira FYI I have hidden all the comments related to your issue, as it is not related at all to the OP. Let's continue the discussion on the PR on your repo.

@wasib-sureify Thanks for confirming, nothing seems strange about your environment from what I can tell.

Please can you try creating a fresh lerna repo and see if you still have the same issue?

E.g. something like

```sh
mkdir lerna-issue-3964
cd lerna-issue-3964
npx lerna init
npx lerna create -y a
npx lerna create -y a
npx lerna list
```

And see if it returns any packages

**Comment by weiwei** [comment] 2024-04-07 14:06
@wasib-sureify @JamesHenry  I'm not sure if my issue is the same, but in my case the issue is triggered by a package exclusion rule in `pnpm-package.yaml`. I have a repo that could demonstrate the issue: https://github.com/weiwei/lrna

**Comment by wasib-sureify** [comment] 2024-04-07 19:46
@weiwei Yes! That was exactly what was happening. I have the same line in my `pnpm-package.yaml` and commenting it resolves the issue. 
@JamesHenry is this behavior intentional?

`packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # exclude packages that are inside test directories
  - "!**/test/**". <-----commenting this resolves the issue
`

Output of `npx lerna list` with or without commenting that exclusion line

`Before:
npx lerna l
ist
lerna notice cli v8.1.2
lerna info versioning independent
lerna success found 0 packages

After commenting:
npx lerna list
lerna notice cli v8.1.2
lerna info versioning independent
lifetime-agent
lifetime-service
portals-common
sureui
lerna success found 4 packages`

**Comment by weiwei** [comment] 2024-04-09 16:00
So I did a bit of digging, and if I'm understanding correctly, it is caused by this line: https://github.com/nrwl/nx/blob/32144bb702b07eddf29ed70055dfbcbcc0f4b11c/packages/nx/src/plugins/package-json-workspaces/create-nodes.ts#L44

We shouldn't need the negation, and my local testing passed with the negation removed.

I would like to submit a PR myself, but `minimatch` seems to have been used in a lot of places. I think it should be fixed by someone who knows better.

**Comment by Thenkei** [comment] 2024-05-17 10:21
I had the same issue this morning. Migrating from Lerna `6.x` to `8.x`(latest).

It was indeed cause by an exclusion pattern used in our `workspaces` configuration.
```
"workspaces": [
    "packages/*",
    "!packages/_example/*"
  ]
```

**Comment by JamesHenry** [comment] 2024-06-07 13:48
Thanks a lot folks, the negative pattern matching is indeed the issue here, I'll get this fixed up and report back once it's available

**Comment by JamesHenry** [comment] 2024-06-09 10:28
Hi Folks, thanks a lot for your patience on this, I believe this one to be completely resolved now. Please kindly update to the latest `8.1.4`.

**Closed by JamesHenry** 2024-06-09 10:28 UTC
Labels: type: bug, blocked: repro needed
