### ISSUE TITLE
use local lerna if global lerna used as entry point

### ISSUE THREAD

**Issue by cdaringe** [lerna/lerna#735] opened 2017-04-06 20:38 UTC
hi all,

would you accept a PR that uses the local version of lerna (if found) when the global `lerna` is the cmd entry point?

## Expected Behavior

- allow global `lerna` to use local `lerna` if it exists
  - allow `lerna <cmd>` to work vs `./node_modules/.bin/lerna <cmd>`

examples:

- https://github.com/webpack/webpack/blob/master/bin/webpack.js#L10

## Current Behavior

no such functionality exists, [ref](https://github.com/lerna/lerna/blob/master/bin/lerna.js)

**Comment by evocateur** [comment] 2017-04-06 20:42
I'm a little confused why you would need this, if you already have `lerna` globally available?

**Comment by cdaringe** [comment] 2017-04-07 00:55
Different projects, different lerna versions.  Iirc some lerna versions make sure that the running version matches that listed in the lerna.json.  peace of mind that the version that is running is always what is declared regardless of what shenanigans I'm doing globally.  I've always loved that feature of webpack

**Comment by evocateur** [comment] 2017-04-07 01:16
I've found calling lerna from root package.json scripts to be more than sufficient for isolating a particular version. #694 makes the version check only complain about insufficient semver (usually major version mismatch or older lerna attempting to work on "newer" repo).

For example, run `lerna bootstrap` in the `postinstall` lifecycle, and you only need to run `npm install` (or `yarn`, if you're fancy) and it will always call the local `lerna`:

```json

  "name": "my-lerna-monorepo",
  "private": true,
  "scripts": {
    "postinstall": "lerna bootstrap",
    "test": "lerna run test"
  },
  devDependencies: {
    "lerna": "^2.0.0-rc.0"
  }
}
```

**Comment by hzoo** [comment] 2017-04-07 02:12
yeah same request was made to Babel https://github.com/babel/babel/issues/5091

**Comment by evocateur** [comment] 2017-05-21 20:55
Closing this as a duplicate of #138

**Closed by evocateur** 2017-05-21 20:55 UTC
