### ISSUE TITLE
lerna publish from-package is not available

### ISSUE THREAD

**Issue by dogoku** [lerna/lerna#1962] opened 2019-03-07 08:21 UTC
The [docs for lerna publish](https://github.com/lerna/lerna/tree/master/commands/publish#readme)  specify that we can use `from-package` as a value for bump, but when running the command, I see an error instead.

## Expected Behavior
`from-package` should be recognised as a valid value for bump and work as described in the docs.

## Current Behavior
I get the following error:
```
$ lerna publish from-package
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', or 'from-git'.
```

## Steps to Reproduce (for bugs)
1. `lerna publish from-package`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/demo/**",
        "**/docs/**",
        "**/test/**",
        "**/*.md",
        "**/package-lock.json"
      ]
    }
  },
  "version": "independent"
}

```
</p></details>

## Context
I am trying to publish a package whose version has already been manually updated in package.json and the PR has been merged

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.8.0 |
| `node --version` | 10.15.1 |

| OS | Version |
| --- | --- |
| MAC | 10.12.6 |

**Comment by pruett** [comment] 2019-04-17 02:47
I'm receiving similar output in a similar environment

**Comment by evocateur** [comment] 2019-05-10 21:47
I'm going to need a more concrete reproduction before any progress can be made diagnosing the issue. I've literally never encountered this issue, and there are [several tests](https://github.com/lerna/lerna/blob/master/commands/publish/__tests__/publish-from-package.test.js) that would fail spectacularly were this not a valid option.

I would first make absolutely certain you have the right version of lerna, non-nested from older versions (sometimes npm has problems maintaining flatness, especially when exact version ranges are in play):
```
npm rm -D lerna
npm i -D lerna@latest
```

**Comment by dogoku** [comment] 2019-05-11 00:41
I'll try to get a clean install in and try again.

**Comment by ilteoood** [comment] 2021-12-15 12:34
Hi, any news about this?

@evocateur if you need a reproduction repo, you can check this: https://github.com/mia-platform/api-explorer

I'm trying from-package using the command:

`
npx lerna publish from-package --yes --no-verify-access
`

And the result is:

`
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', or 'from-git'.
`

**Comment by JamesHenry** [comment] 2023-03-08 15:34
Hi Folks 👋 

Due to its age I am going to close this one. I cannot reproduce any issues against latest lerna, and the reproduction mentioned (which I haven't verified) is using lerna v3.x, whereas the latest version is v6.x, and a lot has improved between the two versions.

If you can reproduce using the latest major version of lerna please feel free to file a new issue which as much information as possible.

Many thanks!

**Closed by JamesHenry** 2023-03-08 15:34 UTC
