### ISSUE TITLE
Running "lerna run tsc" only runs the script for 3/5 packages

### ISSUE THREAD

**Issue by ghost** [lerna/lerna#2913] opened 2021-05-21 22:17 UTC
## Expected Behavior

When running `lerna run tsc` I expect `lerna success run Ran npm script 'tsc' in 5 packages`

## Current Behavior

Creating 5 packages
```
lerna create directory-1
lerna create directory-2
lerna create directory-3
lerna create directory-4
lerna create directory-5
```
Then running `lerna run tsc` results in `lerna success run Ran npm script 'tsc' in 3 packages in 5.8s:`

Why is it not running for all packages?

## Steps to Reproduce (for bugs)

1. Create 5 packages, `lerna create project-1`
2. Run `lerna run tsc`

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "packages": [
    "packages/*"
  ],
  "changelog": {
    "repo": "@tikken/kontiki",
    "labels": {
      "PR: New Feature": ":rocket: New Features",
      "PR: Breaking Change": ":boom: Breaking Changes",
      "PR: Bug Fix": ":bug: Bug Fix",
      "PR: Documentation": ":memo: Documentation",
      "PR: Internal": ":house: Internal",
      "PR: Underlying Tools": ":hammer: Underlying Tools"
    },
    "cacheDir": ".changelog"
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'add' ],
0 silly argv   scope: '@yourcompany/auth0',
0 silly argv   globs: [],
0 silly argv   lernaVersion: '3.22.1',
0 silly argv   '$0': '/usr/local/bin/lerna',
0 silly argv   pkg: '@yourcompany/api-common'
0 silly argv }
1 notice cli v3.22.1
2 verbose rootPath /Users/danielhendricks/Desktop/@tikken:kontiki
3 info versioning independent
4 error Error: 404 Not Found - GET https://registry.npmjs.org/@yourcompany%2fapi-common - Not found
4 error     at /Users/danielhendricks/Desktop/@tikken:kontiki/node_modules/@evocateur/npm-registry-fetch/check-response.js:104:15

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.21.0 |
| `yarn --version` | 1.22.10 |
| `node --version` | v16.2.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Efraa** [comment] 2021-05-26 05:14
Use `lerna run --parallel tsc`

Docs: [--parallel](https://github.com/lerna/lerna/blob/main/commands/run/README.md#--parallel)

**Comment by Deja-vuuu** [comment] 2021-07-25 12:42
How to run only specified packages？
For example    directory-1  directory-3

**Comment by JamesHenry** [comment] 2022-07-05 14:35
As the original reporter's user has been deleted there is not much more we can do here. I was not able to reproduce with the latest version of lerna so closing this one.

**Closed by JamesHenry** 2022-07-05 14:35 UTC
