### ISSUE TITLE
On publish, do not update package.json

### ISSUE THREAD

**Issue by dmk255** [lerna/lerna#1328] opened 2018-03-16 19:53 UTC
On `lerna publish` I would like to have the ability to not update the semver of some packages.

e.g.
 - Package 1 (P1) is a component library.
- Package 2 (P2) is a consumer of P1.
- Package 3 (P3) is a consumer of P1.

If I make a change to P1 to increase its version number (e.g. change some components behavior). I would like the option to lock in P3 or P2 to their prior version. 

For example.
P1: current version v0.1.1
P2:
    * P1 - v0.0.1
P2:
    * P1 - v0.1.1

At present, lerna updates all instances of P1 across the monorepo.

## Context
The main driving force for this, is that we do not want to force users to have to update the entire monorepo any time they make a change to a component in our component library. Maintainers of their respective packages should be responsible for that in my opinion especially if their code is presently working.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.4.0 |
| `node --version` | 9.2.1 |

| OS | Version |
| ---: | :--- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment] 2018-03-16 20:00
This is a duplicate of #707, #718, #1291, and several others. If you don't want component changes to bump the component library(?) it shouldn't be a monorepo.

**Closed by evocateur** 2018-03-16 20:00 UTC
Labels: duplicate

**Comment by dmk255** [comment] 2018-03-16 20:11
@evocateur That makes sense! Thanks for the prompt reply!
