### ISSUE TITLE
Frozen loading bar at bootstrapping

### ISSUE THREAD

**Issue by StarpTech** [lerna/lerna#1001] opened 2017-08-30 09:18 UTC
## Expected Behavior
Bootstrapping works

## Current Behavior
Lerna doesn't proceed I can see a frozen loading bar

## Steps to Reproduce (for bugs)
Checkout https://github.com/hemerajs/hemera
Run `lerna bootstrap`

I have a package called `hemera-plugin` its used by many others. When I try to run the app the message `Cannot find module 'hemera-plugin'` appears. It seems Lerna have some troubles to install it. I can manually install it and fix it but this makes lerna useless.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.2 |
| `npm --version`  | 5.3.0 |
| `node --version` | 8.3.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 10 | 1607 |

**Comment by kenjinp** [comment] 2017-08-31 09:58
I am getting a similar problem using ` lerna run <some command>`

**Comment by evocateur** [comment] 2017-08-31 18:07
Is this a "clean" bootstrap (i.e., after an initial clone or `git clean -fdx && npm install`), or is it after changes to package dependencies?

Is there a `lerna-debug.log` available?

**Comment by StarpTech** [comment] 2017-08-31 19:28
I run `lerna clean` and removed all node_module folders.

**Comment by evocateur** [comment] 2017-08-31 19:31
If you `Ctrl+C` out of the hanging process, it should write a `lerna-debug.log` in the same directory. Posting that in a Gist would be a big help in diagnosing the issue.

**Comment by StarpTech** [comment] 2017-08-31 19:35
I already looked for a debug file but couldn't find anything I will try it again.

**Comment by bobaaaaa** [comment] 2017-10-07 13:48
I got the same error. Maybe it has something to do with yarn/lerna workspaces.

**package.json important parts**
```json
{
  "private": true,
  "workspaces": [
    "static/*",
    "*/static/*"
  ]
}
```

**lerna.json**
```json
{
    "lerna": "2.4.0",
    "packages": [
        "static/*",
        "*/static/*"
    ],
    "version": "independent",
    "npmClient": "yarn",
    "useWorkspaces": true
}

```


| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `yarn --version` | 1.1.0 |
| `node --version` | 8.6.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment] 2017-10-07 14:47
In my limited testing of yarn workspaces, I was under the impression that nesting workspaces was not supported?

**Comment by bobaaaaa** [comment] 2017-10-09 08:22
I have tested yarn/lerna workspaces now with lerna 2.0.0, 2.1.0, 2.2.0, 2.3.1 and 2.4.0. Always the same problem. Here are the log of `yarn lerna bootstrap --loglevel silly`:

```
yarn run v1.1.0
$ lerna bootstrap --loglevel silly
lerna sill input []
lerna sill flags { _: [ 'bootstrap' ], loglevel: 'silly', args: [] }
lerna verb rootPath $ROOT_DIR
lerna info version 2.4.0
lerna info versioning independent
lerna sill existsSync $ROOT_DIR/VERSION
lerna sill initialize attempt
lerna sill npmConfig { registry: undefined,
lerna sill npmConfig   npmClient: 'yarn',
lerna sill npmConfig   npmClientArgs: undefined,
lerna sill npmConfig   mutex: 'network:42424' }
lerna sill initialize success
lerna sill execute attempt
lerna info Bootstrapping 17 packages
lerna sill installInDirOriginalPackageJson $ROOT_DIR
lerna sill getExecOpts { cwd: '$ROOT_DIR' }
lerna sill installInDir [ 'yarn',
lerna sill installInDir   [ 'install', '--mutex', 'network:42424', '--non-interactive' ] ]
```
`$ROOT_DIR` == path to the project root dir. edit by me.

**Comment by StarpTech** [comment] 2017-10-09 08:26
I couldn't reproduce it with yarn in the last trys.

**Comment by bobaaaaa** [comment] 2017-10-10 10:07
I dont have a public example repo :(. Maybe your'e right -- should i open a new issue?

**Comment by StarpTech** [comment] 2017-10-10 10:38
@bobaaaaa so you can't reproduce easily? If you would create an example repo we could check it.

**Comment by ingro** [comment] 2017-11-07 09:04
Got the same problem here (using latest `lerna` and `yarn`), lerna hangs on install dependencies... If I force close the script I can only see this error in `yarn-error.log`:

```
Trace: 
  Error: write EPIPE
      at _errnoException (util.js:1024:11)
      at Socket._writeGeneric (net.js:767:25)
      at Socket._write (net.js:786:8)
      at doWrite (_stream_writable.js:387:12)
      at writeOrBuffer (_stream_writable.js:373:5)
      at Socket.Writable.write (_stream_writable.js:290:11)
      at Socket.write (net.js:704:40)
      at ConsoleReporter._log (C:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:87213:17)
      at ConsoleReporter.log (C:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:87200:10)
      at ConsoleReporter.step (C:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:87146:10)
```

**Comment by marionebl** [comment] 2017-11-07 09:50
@StarpTech Have you verified this happens when running `lerna bootstrap` manually as opposed to running it via the `setup` run-script? https://github.com/hemerajs/hemera/blob/master/package.json#L40

**Comment by sloops77** [comment] 2017-12-26 11:29
Since we are using worksapces the obvious workaround is to `lerna run prepublish` & `lerna run prepare` instead

**Comment by ahmadawais** [comment] 2018-01-13 16:49
In my case I had a script called `prepublish` for something else and it was running that and getting stuck.

**Comment by gabrielizaias** [comment] 2018-01-24 09:51
I solved it by removing `"postinstall": "lerna bootstrap",` from my `package.json`.

**Comment by hulkish** [comment] 2018-01-27 15:55
This is still an issue, even without the `postinstall` script

**Comment by lukejagodzinski** [comment] 2018-02-26 14:41
I have the same problem and in the logs it says:

```
10 error initialize callback with error
11 error Error: Can't diff. There are no commits in this repository, yet.
11 error     at DiffCommand.initialize (/Users/lukejagodzinski/.nvm/versions/node/v6.10.3/lib/node_modules/lerna/lib/commands/DiffCommand.js:89:18)
```

It is a git repository and there is one commit

**Comment by evocateur** [comment] 2018-02-26 16:54
That’s not a problem with lerna bootstrap, that’s lerna diff. How do you expect it to diff changes when there is only one commit in the repo?

**Comment by lukejagodzinski** [comment] 2018-02-26 17:03
@evocateur there is more than 1 commit and I just expect it to work. `lerna run start` (that's the command I'm executing) shouldn't care about diff in my opinion. But as I said there are more commits and effect is the same

**Comment by evocateur** [comment] 2018-02-26 17:07
Bootstrap literally does no git operations. It does not require git at all. The stack posted was from an execution of lerna diff, not bootstrap or run.

**Comment by lukejagodzinski** [comment] 2018-02-26 17:35
@evocateur I've created reproduction repository showing the problem: https://github.com/lukejagodzinski/lerna-freeze-reproduction

**Comment by tdeekens** [comment] 2018-03-05 17:21
We downgraded to yarn version 1.3.1 which fixed the issue.

**Comment by lukejagodzinski** [comment] 2018-03-05 20:21
@tdeekens thanks! I will test it out

**Comment by tdeekens** [comment] 2018-03-05 20:23
On the flip side on some machines it even worked with version 1.5.1. It's really hard to pin the issue down but playing a bit with the yarn version seems to have solved it.

**Comment by hulkish** [comment] 2018-03-05 20:58
You don't actually need to run `lerna bootstrap` [if you're using yarn workspaces](https://github.com/lerna/lerna/issues/1301)

**Comment by evocateur** [comment] 2018-03-06 00:05
`lerna bootstrap` when using yarn + `--use-workspaces` just calls `yarn install` in the root, nothing fancy. A loud warning would be preferable to a hard stop.

**Comment by mcdermed** [comment] 2018-03-13 20:34
I was running into the same issue and noticed the same behavior when running 'yarn install' in the workspace. I noticed a missing package was defined in `workspaces: ['missing', 'not_missing']` but the package hadn't been cloned into the workspace yet.

**Comment by OutThisLife** [comment] 2018-03-31 03:05
Should probably note that here - https://github.com/lerna/lerna#--use-workspaces

**Comment by maciej-gurban** [comment] 2018-04-04 11:39
I'm on yarn 1.5.1 and lerna 2.9.1, with a fresh setup of lerna that uses yarn with workspaces. I stumbled upon this thread when running `lerna bootstrap`, which you say is not necessary. I wouldn't have known that if not for this issue, so perhaps it could be clarified in the docs.

As I understand, one should use `yarn install` instead? I've tried that, but this still will run and hang on lerna bootstrap:
```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ lerna bootstrap
lerna info version 2.9.1
lerna info Bootstrapping 1 packages
⸨░░░░░░░░░░░░░░░░░░⸩ ⠸ install dependencies: info Bootstrapping 1 packages
```

**Comment by tdeekens** [comment] 2018-04-04 11:49
Yes I've got the same. It hangs if you run `lerna boostrap` in a `postinstall` when using workspaces.

**Comment by maciej-gurban** [comment] 2018-04-19 15:41
Could contributors of lerna provide some pointers where to look for a solution? Is anybody looking into it? Is it entirely Yarn's issue? Should we even expect any resolution from Lerna's side?

**Comment by evocateur** [comment] 2018-04-19 22:30
@maciej-gurban `yarn install` by itself, with no `postinstall` hook in `package.json`, will _never_ call `lerna bootstrap` automatically.

Just remove the `postinstall` hook, they're a bad idea anyway. If you use Yarn [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) you can completely skip calling `lerna bootstrap`.

**Comment by hulkish** [comment] 2018-04-20 15:59
Just a suggestion..but imo this should be closed since not really an issue but more user error

**Comment by maciej-gurban** [comment] 2018-04-21 13:13
I was about to say that it's not, since I didn't remember adding a `postinstall` hook or doing anything custom, but I started from scratch by creating a new project and I can't reproduce the issue I had initially. It very well could be that I did something wrong when first setting up. Here's a repo that works for me with `lerna@1.9.1` and `yarn@1.5.1`: https://github.com/maciej-gurban/lerna-with-yarn.

Adding it here in case somebody else stumbles upon the same issue. Thanks for all the help and patience!

**Comment by doug-wade** [comment] 2018-04-23 17:31
I'm with @hulkish; closing

**Closed by doug-wade** 2018-04-23 17:31 UTC

**Comment by carrickjason** [comment] 2018-04-24 20:25
Thanks for the reply.  Does it not also run `npm run` calls in a child process? I was definitely getting output before I switched to yarn.

**Comment by carrickjason** [comment] 2018-04-24 20:33
I added `--stream` and I see now that it's not getting stuck. This is slightly confusing behavior when running scripts that wait to be terminated.

**Comment by hulkish** [comment] 2018-04-24 20:34
It is, but I recommend creating a new issue for it.

**Comment by carrickjason** [comment] 2018-04-24 20:36
Sounds good.  BTW, I must have been seeing output with npm because the script was originally using `--parallel`.  Thanks for your help!

**Comment by evocateur** [comment] 2018-04-24 20:38
> This is slightly confusing behavior when running scripts that wait to be terminated.

The alternative, opting-out of logging, means (largely) useless concurrent console spam for the vast majority of `lerna run` use-cases. `--stream` isn't hard to add, but it's virtually impossible to detect when a given script will hang due to muffled `stdio`. Improved documentation/examples is always possible, and welcome.

**Comment by carrickjason** [comment] 2018-04-24 20:46
@evocateur That makes sense. Maybe that progress bar needs some sort of timeout that drops a hint to use `--stream` if no 'progress' is being made after a while.  Documentation would help but it really feels like something is broken when that bar shows up and doesn't progress ever.
