### ISSUE TITLE
publish(v3): auth error publishing to private registry (Verdaccio)

### ISSUE THREAD

**Issue by jharris4** [lerna/lerna#1560] opened 2018-08-13 14:57 UTC
After upgrading from lerna `2.11.0` to `3.0.3` I get auth errors when trying to publish packages with lerna.

## Expected Behavior
Publishing packages should work like it did with 2.x

## Current Behavior
Publishing packages fails, and I have to run `npm publish` manually in all leaf packages. Manually publishing each leaf package with npm does work, so I strongly suspect this is an issue that is specific to lerna 3.x...

```
$ lerna publish
lerna info version 3.0.3
lerna info version 3.0.3
lerna info current version 1.0.18
lerna info Looking for changed packages since v1.0.18.
? Select a new version (currently 1.0.18) Patch (1.0.19)

Changes:
 - @scope/package-a: 1.0.18 => 1.0.19
 - @scope/package-b: 1.0.18 => 1.0.19

? Are you sure you want to create these versions? Yes
lerna info git Pushing tags...
lerna success version finished
npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-08-13T14_37_14_397Z-debug.log

lerna ERR! EREGISTRY Connection to npm registry failed
error Command failed with exit code 1.
```

## Possible Solution
Run `npm publish` in each leaf package (not ideal! lol)

## Steps to Reproduce (for bugs)
1. Host your packages on verdaccio or other private npm repository
2. Have lerna 3.x in your dev dependencies.
3. run `yarn lerna publish`
4.

<details><summary>lerna.json</summary><p>

```json
{
	"private": true,
	"devDependencies": {
		"lerna": "^3.0.3",
		"rimraf": "^2.6.2"
	},
	"workspaces": [
		"packages/*"
	],
	"scripts": {
		"clean": "rimraf packages/*/node_modules rimraf node_modules",
		"lerna": "lerna"
	}
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'ping',
1 verbose cli   '--fetch-retries=0',
1 verbose cli   '--loglevel=http' ]
2 info using npm@6.2.0
3 info using node@v10.8.0
4 verbose request uri https://registry.yarnpkg.com/-/ping?write=true
5 verbose request always-auth set; sending authorization
6 info attempt registry request try #1 at 10:37:14 AM
7 verbose stack Error: This request requires auth credentials. Run `npm login` and repeat the request.
7 verbose stack     at RegClient.authify (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/authify.js:21:14)
7 verbose stack     at RegClient.makeRequest (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:116:17)
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:68:17
7 verbose stack     at RetryOperation._fn (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:18:5)
7 verbose stack     at RetryOperation.attempt (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry/lib/retry_operation.js:97:8)
7 verbose stack     at RegClient.attempt (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:11:13)
7 verbose stack     at RegClient.regRequest [as request] (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:67:8)
7 verbose stack     at RegClient.ping (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/ping.js:14:8)
7 verbose stack     at EventEmitter.ping (/usr/local/lib/node_modules/npm/lib/ping.js:17:16)
7 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:159:13)
8 verbose cwd /Users/jonharris/Source/webpack-runner
9 verbose Darwin 17.7.0
10 verbose argv "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/bin/npm" "ping" "--fetch-retries=0" "--loglevel=http"
11 verbose node v10.8.0
12 verbose npm  v6.2.0
13 error This request requires auth credentials. Run `npm login` and repeat the request.
14 verbose exit [ 1, true ]
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.3 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.9.4 |
| `node --version` | 10.8.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment] 2018-08-13 15:36
I don't see your _actual_ lerna.json, but I'll assume you're using npmClient yarn.

Purportedly, the yarn registry is just a CDN alias (or whatever) to the public npm registry. Obviously, that's not exactly the case.

> Run `npm publish` in each leaf package

That's exactly what lerna used to do! Until someone convinced me to let them run `yarn publish` if they were using yarn, as if it made any damned difference...

Anyway, the workaround for now is to set a scoped `npmClient` for the publish command in lerna.json:
```json
{
  "command": {
    "publish": {
      "npmClient": "npm"
    }
  }
}
```

**Comment by evocateur** [comment] 2018-08-13 15:45
Or maybe explicitly set `--registry https://registry.npmjs.org/` so yarn doesn't use its stupid alias thing?

**Comment by jharris4** [comment] 2018-08-13 15:53
@evocateur oops, I pasted the root package.json by accident, here's my lerna.json

```
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "version": "1.0.19",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

**Comment by jharris4** [comment] 2018-08-13 15:54
Also, I'm using a private npm repository, so the `.npmrc` in the root of the monorepo looks like this:

```
always-auth=true
registry=https://verdaccio.mydomain.com/
```

**Comment by evocateur** [comment] 2018-08-13 16:06
Oh, okay, interesting. A couple things are happening here, as far as I can tell:

1. Your custom registry isn't getting picked up by yarn (a yarn bug)
    * Try adding `"registry": "https://verdaccio.mydomain.com/"` to your lerna.json?
2. I'm not entirely certain Verdaccio even supports the `npm ping` or `npm access` endpoints, so the new registry + package access validation will probably fail
    * I guess I'll just skip the validation if an explicitly configured registry does _not_ match `"https://registry.npmjs.org/"`...

**Comment by evocateur** [comment] 2018-08-13 16:08
And I suppose I could parse the npm config myself and always set `npm_config_registry` appropriately, but that gets prohibitively complex with scoped registries etc etc... _That_ part I consider to be a Yarn bug.

**Comment by panjiesw** [comment] 2018-08-13 16:15
Ah this is actually the issue I want to submit.

I also use scoped package and publish to custom registry, I ran with `lerna publish --registry <registry-url>` command, but even then the publish still failed, yarn complained about the package is marked as private.

So the problem is because Yarn can't run `yarn publish` command inside private package (in this case a root package of monorepo). Related issue: yarnpkg/yarn#5334

Also yarn has bug that can't override scoped npm registry if it's in an `.npmrc`. Related: yarnpkg/yarn#4732

Lastly, before @evocateur tried to set `npm_config_registry` to fix this for yarn, there is this issue yarnpkg/yarn#2091. Yarn doesn't read from `npm_config_registry` :disappointed:

**Comment by jharris4** [comment] 2018-08-13 16:28
@evocateur just to reiterate, this all used to work fine with lerna 2.x, and publishing to the private repository also works fine with the `yarn publish` command.

**Comment by panjiesw** [comment] 2018-08-13 16:34
@jharris4 That's because lerna 2.x used to publish from inside sub-package directly as mentioned by @evocateur. 

Currently lerna use `npm pack` to pack all non-private sub-package into the root of monorepo, then run `npm publish` or `yarn publish` depending on `npmClient` lerna config, in the root of monorepo. This is what fails yarn.

You can try running `npm pack` of one of your sub-package from monorepo root, then run `yarn publish` the resulting tarball.

**Comment by panjiesw** [comment] 2018-08-13 16:48
@evocateur this workaround you mentioned,

> Anyway, the workaround for now is to set a scoped npmClient for the publish command in lerna.json

I tried it and while the publish is success (the packages are in the private registry), it produces wrong behavior: all related manifest (`lerna.json`, and packages `package.json`) doesn't get updated to the new version

**Comment by evocateur** [comment] 2018-08-13 21:58
> I tried it and while the publish is success (the packages are in the private registry), it produces wrong behavior: all related manifest (lerna.json, and packages package.json) doesn't get updated to the new version

hrm, that seems wrong...

Oh, and packing into the root is just as easily done into a temp directory and then move the tarballs back into the leaf package dirs. Probably for the best, since it means any package-specific publishConfig etc will be properly followed. I think we can do that.

**Closed** 2018-08-14 01:01 UTC
Labels: bug, upstream, yarn

**Comment by schmkr** [comment] 2018-08-27 07:55
> Fyi, my private registry is nexus oss 3, it doesn't support npm ping and npm access so I also run the publish command with --no-verify-registry and --no-verify-access.

I also ran into this today. Is it possible to set those flex in `lerna.json?

**Comment by evocateur** [comment] 2018-08-27 15:15
@schmkr Yep, exactly.

**Comment by verekia** [comment] 2018-09-15 15:16
Hi! I am trying to use the NPM registry, not a private one, but it seems relevant to this discussion. Lerna keeps trying to authenticate using the Yarn registry when I run `lerna publish`. I tried the 2 suggested configurations of this thread, `"npmClient": "npm"` in the `publish` command and `verifyAccess": false` without success.

```js
{
  "lerna": "3.4.0",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "npmClient": "npm",
      "verifyAccess": false,
      "ignoreChanges": [
        "*.md",
        "tests/*"
      ]
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}

```

```bash
> lerna publish
// ...
lerna notice cli v3.4.0
lerna info versioning independent
lerna info Verifying npm credentials
401 Unauthorized - GET https://registry.yarnpkg.com/-/whoami
lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by evocateur** [comment] 2018-09-17 14:50
Yarn is mutilating the registry config for some obscure reason. I guess we could check for that error case, but I'd rather yarn fixed their pyrrhic registry proxy to correctly forward API calls. (Their proxy is probably stripping the auth fields, which would explain the 401 code)

One alternative is to specify the public npm registry in the `command.publish.registry` field, which should override yarn's incomplete proxy.
