### ISSUE TITLE
lerna publish fails

### ISSUE THREAD

**Issue by fortesp** [lerna/lerna#3477] opened 2022-12-28 07:58 UTC
## Current Behavior

When executing `npx lerna publish --skip-git` it gives an error

## Expected Behavior

No error.

## Steps to Reproduce

0. `lerna boostrap` executed and `npx lerna run build `successfully
1. Execute `npx lerna publish --skip-git`
2. Select any version
3. Error appears

### Failure Logs / Configuration

```
19 error TypeError: Cannot read properties of undefined (reading 'ignore-prepublish')
19 error     at flattenOptions (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:34:26)
19 error     at runLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:70:8)
19 error     at VersionCommand.runPackageLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:175:26)
19 error     at VersionCommand.runRootLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\version\index.js:247:25)
19 error     at C:\Develop\Projects\id-components\node_modules\@lerna\version\index.js:517:37
```

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.1"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
```
19 error TypeError: Cannot read properties of undefined (reading 'ignore-prepublish')
19 error     at flattenOptions (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:34:26)
19 error     at runLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:70:8)
19 error     at VersionCommand.runPackageLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\run-lifecycle\run-lifecycle.js:175:26)
19 error     at VersionCommand.runRootLifecycle (C:\Develop\Projects\id-components\node_modules\@lerna\version\index.js:247:25)
19 error     at C:\Develop\Projects\id-components\node_modules\@lerna\version\index.js:517:37
```
```

</p></details>

### Environment

lerna notice cli v6.3.0

 Environment info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.35.3.
  npmPackages:
    lerna: ^6.3.0 => 6.3.0

--

if I remove the line 70 in `run-lifecycle.js` it moves on... Trying to see how can i pass this.

**Comment by fahslaj** [comment] 2023-01-03 20:04
@fortesp I am unable to reproduce this issue on a fresh Lerna workspace given the information provided above. Can you please create and share a minimal reproduction of the issue?

**Comment by JamesHenry** [comment] 2023-03-09 09:01
Hi @fortesp given it's been a couple of months I'm going to close this one. If you are able to provide instructions/a repo which reproduces the issue we will happily take a look.

**Closed by JamesHenry** 2023-03-09 09:01 UTC
Labels: type: bug, blocked: repro needed

**Comment by fortesp** [comment] 2024-04-25 09:04
Apologies for late reply.

I've tested it now with your latest version 8.1.2 and a new Lerna project and its the same behavior. 
i.e.

1. 

`mkdir test
cd test
npx lerna init
mkdir packages
cd packages
mkdir utils
cd utils
npm init
`

2.
Change package.json and add 

`  "scripts": {
    "publish": "npx lerna publish --no-git-tag-version --no-push",
  },`

3.
`npm run publish`


This is the output result after selecting a version (any version):

```
> npx lerna publish --no-git-tag-version --no-push

lerna notice cli v8.1.2
lerna info current version 0.0.0
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna info Assuming all packages changed
lerna WARN version Skipping working tree validation, proceed at your own risk
? Select a new version (currently 0.0.0) Patch (0.0.1)   
                                                         
Changes:                                                 
 - utils: 1.0.0 => 0.0.1                                 
                                                         
? Are you sure you want to publish these packages? Yes
lerna ERR!     at C:\Develop\Projects\tst2\node_modules\p-waterfall\index.js:5:43
lerna ERR!     at next (C:\Develop\Projects\tst2\node_modules\p-reduce\index.js:17:9)
lerna ERR! TypeError: Cannot read properties of undefined (reading 'ignore-prepublish')
lerna ERR!     at flattenOptions (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:4255:26)
lerna ERR!     at runLifecycle (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:4277:8)
lerna ERR!     at VersionCommand.runPackageLifecycle (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:4341:27)
lerna ERR!     at VersionCommand.runRootLifecycle (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:8126:29)
lerna ERR!     at VersionCommand.updatePackageVersions (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:8361:22)
lerna ERR!     at tasks (C:\Develop\Projects\tst2\node_modules\lerna\dist\index.js:8140:35)
lerna ERR!     at C:\Develop\Projects\tst2\node_modules\p-waterfall\index.js:5:43
lerna ERR!     at next (C:\Develop\Projects\tst2\node_modules\p-reduce\index.js:17:9)
lerna ERR! lerna Cannot read properties of undefined (reading 'ignore-prepublish')
```
`

Could you please re-open this issue and help?

Thanks

**Comment by fortesp** [comment] 2024-04-25 09:21
I've copied the files to a repo here https://github.com/fortesp/lerna-bug
I just removed the package-lock.json just not expose the artifactory domain name.
