### ISSUE TITLE
Specify custom template for CREATE command

### ISSUE THREAD

**Issue by kibertoad** [lerna/lerna#2247] opened 2019-09-02 08:42 UTC
## Expected Behavior

User can pass additional commandline option, pointing to custom package.json template

## Current Behavior

Default, highly opinionated package.json is used for creating new Lerna package.

## Possible Solution

Additional CLI parameter, support for package.json template file.

## Context

Trying to reduce amount of time spent setting up new Lerna packages

**Comment by kibertoad** [comment] 2019-09-02 08:43
If there is approval for this feature, I can look into implementing it myself.

**Comment by kibertoad** [comment] 2019-09-03 07:15
@evocateur Would it be possible to get this proposal reviewed and either accepted (so that I could start working on it) or rejected?

**Comment by ntwb** [comment] 2020-01-13 22:01
This looks like a duplicate of #1742

**Closed** 2020-01-13 22:02 UTC
