### ISSUE TITLE
v6.1.0 failed with nx 15.4.0

### ISSUE THREAD

**Issue by waitingsong** [lerna/lerna#3469] opened 2022-12-23 10:15 UTC
## Current Behavior
```
lerna notice cli v6.1.0
lerna info ci enabled
lerna notice filter excluding "@scope/demo-*"
lerna info filter [ '!@scope/demo-*' ]
lerna ERR! Error: No projects matching: @
lerna ERR!     at projectsToRun (/builds/utQAMD28/0/app/node_modules/nx/src/command-line/run-many.js:53:23)
lerna ERR!     at /builds/utQAMD28/0/app/svc/node_modules/nx/src/command-line/run-many.js:24:26
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR! lerna No projects matching: @
```

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by waitingsong** [comment] 2022-12-23 10:17
with nx ~15.3.3 ok

**Comment by JamesHenry** [comment] 2022-12-23 13:26
Really sorry about this @waitingsong - duplicate of #3468

**Closed by JamesHenry** 2022-12-23 13:26 UTC
Labels: type: bug
