### ISSUE TITLE
Lerna 7 failed to publish if there are cycle dependencies

### ISSUE THREAD

**Issue by chenmmm111** [lerna/lerna#3798] opened 2023-07-29 02:22 UTC
## Current Behavior

`lerna publish` throws error: 
```
lerna ERR! ERROR Not all tasks were run. This is likely a bug in Lerna.
```

It turns out there're cycle dependencies in the monorepo:
```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE packageD-> packageC -> packageD
lerna WARN ECYCLE packageB-> packageF -> packageB
...
```

The above error will be thrown if the dependencies tree looks like this:
![cycles that publish failed](https://github.com/lerna/lerna/assets/22387728/cca8a7b8-b03b-47d6-bee8-ddef8f5624aa)

As a result, the publishing failed with the ambiguous error message.

**Possible cause**
The topology algorithm failed to filter cycle without external dependencies. The `packageE` in the graph is not in any cycles, so it blocks the rest of cycle packages to publish. Here's the reference: https://github.com/fahslaj/lerna/blob/b53bcfffff5bc75451a7a8c07dfd6cb3d85d97c2/libs/core/src/lib/run-projects-topologically.ts#L70C1-L83
## Expected Behavior

Since the cycle dependencies are categorized as `warning` not `error` in Lerna, so the topology running for the above cycle dependencies should work without errors.

## Steps to Reproduce

- Lerna@7.1.4
- run `lerna publish`

### Failure Logs / Configuration

```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE packageD-> packageC -> packageD 
lerna WARN ECYCLE packageB-> packageF -> packageB

Command failed: node_modules/.bin/lerna publish patch --yes --force-publish=packageA --ignore-changes=*

lerna ERR! ERROR Not all tasks were run. This is likely a bug in Lerna.
```

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "$schema": "node_modules/lerna/schemas/lerna-schema.json"
}
```

</p></details>

### Environment

lerna notice cli v7.1.4
lerna info versioning independent

 Environment info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (5) arm64 unknown
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  npmPackages:
    lerna: ^7.1.4 => 7.1.4

**Comment by fahslaj** [comment] 2023-08-28 21:03
Hi @chenmmm111, I created a unit test for the `runProjectsTopologically` function matching the exact example you described, and the function handles this case properly. `packageA` is always run first, since it is not in a cycle. Then, all packages (B through F) are merged into the same cycle. 

<img width="481" alt="image" src="https://github.com/lerna/lerna/assets/6913035/1b983cf5-ccf0-46fa-96b7-4db7a7a147e3">

You can see this test here: https://github.com/fahslaj/lerna/blob/8431b7d87afe8eed3dbb74327509263c3d53f138/libs/core/src/lib/run-projects-topologically.spec.ts#L648

This test recreates the situation in which all packages (A through F) are being published. If it wasn't all of them, can you please provide which packages were actually being published? This might help track down the issue.

**Comment by chenmmm111** [comment] 2023-08-28 23:55
@fahslaj We had a much more complicated dependencies, that might not be a good example. In our case `createProjectGraph` created cycles that does not include `packageE`, just these two cycles:
```
lerna WARN ECYCLE packageD-> packageC -> packageD
lerna WARN ECYCLE packageB-> packageF -> packageB
```

So it cannot proceed cycle with `packageF`, because `packageF` depends on `packageE` which is outside of this cycle. https://github.com/fahslaj/lerna/blob/ab79bb4f1a7ae3303c6606edc8f6ce94e9c58c5b/libs/core/src/lib/run-projects-topologically.ts#L72 
```
// only process the cycle if it has NO nodes with dependencies outside this same cycle
```

We have resolved these errors by fixing all cycle dependencies.

**Comment by fahslaj** [comment] 2023-08-29 20:44
Ok. I am closing this for now, as I have not been able to create a scenario similar to that described above where this error occurs (`lerna ERR! ERROR Not all tasks were run. This is likely a bug in Lerna.`).

If anyone finds a consistent project structure that causes this to happen, please follow up with a reproduction.

**Closed by fahslaj** 2023-08-29 20:44 UTC
Labels: type: bug

**Comment by lpatiny** [comment] 2023-09-04 13:47
I think I encounter the same issue with this open-source project and this branch: https://github.com/cheminfo/mass-tools/tree/test3

But it is quite a complex project ... sorry.

```
mass-tools [test3] % npx lerna version minor -y
lerna notice cli v7.2.0
lerna info versioning independent
lerna info Looking for changed packages since chemical-elements@2.0.3
lerna info version rooted leaf detected, skipping synthetic root lifecycles

Changes:
 - emdb: 2.5.0 => 2.6.0
 - mass-fragmentation: 0.8.0 => 0.9.0
 - mass-tools: 1.6.0 => 1.7.0
 - mf-global: 2.2.0 => 2.3.0
 - mfs-deconvolution: 1.3.1 => 1.4.0
 - ms-spectrum: 2.6.0 => 2.7.0
 - octochemdb: 1.4.3 => 1.5.0

lerna info auto-confirmed 
lerna info execute Skipping releases
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE mf-parser -> mf-utilities -> mf-parser
lerna WARN ECYCLE emdb -> ms-spectrum -> emdb
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"
lerna ERR! ERROR Not all tasks were run. This is likely a bug in Lerna.
```

**Comment by fahslaj** [comment] 2023-09-05 14:22
Thank you @lpatiny , I will look into it!
