### ISSUE TITLE
Lerna v4 leaves orphaned child processes

### ISSUE THREAD

**Issue by FirstVertex** [lerna/lerna#2901] opened 2021-05-12 18:30 UTC
In multiple packages we have a "start" command that launches `webpack-dev-server` or `ng serve`.  In the root package.json we have a command that runs all these start commands

```json
"scripts": {
   "start": "lerna run start --stream"
}
```

In Lerna v3, when that was running, I could kill it with CTRL+C, and then launch it again.

In Lerna v4, when I kill the command with CTRL+C, and subsequently launch it I *always* now receive EADDRINUSE for the port that the webservers are running on.  As a workaround I use npm package `kill-port` to kill Lerna's orphaned child process running on that port, before I can run it again.

As a workaround we have downgraded to Lerna 3.22.1 - this is working as expected.

Lerna run has a --no-bail flag which would appear to control the behavior that this is doing, but we do not want the --no-bail behavior but it now seems to be the default and cannot be disabled.

This seems a broken approach to managing child processes and is a breaking change for those upgrading to v4.

**Comment by lerickson-ds** [comment] 2021-05-17 21:48
I have this same issue as well. I would like CTRL + C to kill the port.

**Comment by mancioshell** [comment] 2021-11-12 14:33
Any update? i have the same issue

**Comment by abarke** [comment] 2022-01-06 12:06
Maintainers 👋 please merge 🙏

**Comment by tutok** [comment] 2022-01-27 17:32
related https://github.com/lerna/lerna/issues/2284

**Comment by aviv-skillset** [comment] 2022-06-02 06:26
Hi @JamesHenry,  since Lerna is now being maintained by Nrwrl, and the Major version bumped again to 5, I would like to bump this issue again. Windows users are still stuck with major 3 because of orphan children. 
Is the source of this bug known?
Is there anything I can do to help with locating the root cause and fix it?

**Comment by JamesHenry** [comment] 2022-06-07 16:18
Thanks all!

This should hopefully be fixed by @feryardiant change, applied in https://github.com/lerna/lerna/pull/3156

**Closed by JamesHenry** 2022-06-07 16:18 UTC
