### ISSUE TITLE
Extract package utilities?

### ISSUE THREAD

**Issue by tomdale** [lerna/lerna#967] opened 2017-08-09 21:00 UTC
I realized I reimplemented a bunch of functionality for the [Glimmer VM monorepo](https://github.com/glimmerjs/glimmer-vm/blob/master/build/utils/project.js) that already exists in Lerna to help with managing subpackages.

I was wondering if you all would be open to extracting these utilities (`Repository`, `Package`, `PackageUtilities` etc.) into a standalone package folks could use in their own scripts? No biggie if not, just thought it might be useful for people who need to write scripts for their monorepo and don't want to rely on reaching into Lerna internals.

**Comment by hzoo** [comment] 2017-08-09 21:38
Hi Tom!

Yeah we could do that (theres a lot of code that is reaching into internals already haha)

Don't really have time to do it myself thou cc @evocateur?

**Comment by evocateur** [comment] 2017-08-09 21:44
#174 was what I hoped would yield something like this. I really want to do this, but I'm in a release crunch right now and realistically won't have time for a few weeks yet.

**Comment by marionebl** [comment] 2017-11-18 08:09
This is a duplicate of #167, I'd suggest we centralize the discussion there. @evocateur: Can we close this issue?

**Comment by tomdale** [comment] 2017-11-18 21:40
@marionebl Sounds good to me.

**Closed** 2017-11-18 21:40 UTC
