### ISSUE TITLE
Request: Method of using lerna bootstrap with npm link

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#214] opened 2016-06-13 05:38 UTC
I need a way to link actual modules together using `npm link`. The main reason for this is using `lerna` in junction with `apex`. I'd like to zip up a module and have all of it's npm modules in a folder without having to publish. Right now if you even `npm install` a module locally using a relative path it can have absolute paths in it from `lerna bootstrap`.

Proposal command options:

* `lerna bootstrap-link`
* `lerna bootstrap --link`

**Comment by reggi** [comment] 2016-06-13 16:20
Would really love it if there was a way to `npm install` (locally) as well as `npm link`, could we make this plug-and-play somehow?

**Comment by rygine** [comment] 2016-06-14 15:55
this would be fixed using the updated bootstrapping process i've created.

more info here: https://github.com/lerna/lerna/issues/215

**Comment by thejameskyle** [comment] 2016-06-15 01:59
Duplicate of #11

**Closed by thejameskyle** 2016-06-15 01:59 UTC
