### ISSUE TITLE
Lerna with npm 2FA (npm otp)

### ISSUE THREAD

**Issue by Bamieh** [lerna/lerna#1137] opened 2017-11-23 11:40 UTC
After assigning [2FA](https://docs.npmjs.com/getting-started/using-two-factor-authentication) on my npm account, lerna fails to publish (unless i publish once manually first for each package!)

## Current Behavior

lerna publish fails if otp is added to the npm account of the publisher, there is no way through lerna to pass the `otp`.

## Possible Solution

pass otp to npm if otp options i passed to lerna:
```
$ lerna publish --otp=123456`
```

## Steps to Reproduce (for bugs)

1. install OTP to the npm account
2. try to publish through lerna

<details><summary>lerna-debug.json</summary><p>

```json
lerna info publish Publishing packages to npm...
lerna ERR! publish Retrying failed publish: reflow-core
lerna ERR! publish Retrying failed publish: reflow-core
lerna ERR! publish Retrying failed publish: reflow-core
lerna ERR! publish Retrying failed publish: reflow-core
lerna ERR! publish Ran out of retries while publishing reflow-core Error: Command failed: npm publish --tag latest
lerna ERR! publish npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
lerna ERR! publish npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
lerna ERR! publish npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
lerna ERR! publish npm ERR! publish Failed PUT 401
lerna ERR! publish npm ERR! code E401
lerna ERR! publish npm ERR! 404 You must provide a one-time pass. : reflow-core
```
</p></details>

## Context

Cannot publish packages anymore through lerna without going through the hassle of manually publishing each package once to add the `otp`. Or turning off the 2fa completely.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` |  2.4.0 |
| `npm --version`  | 5.5.1 |
| `node --version` | v8.5.0 |

**Comment by Bamieh** [comment] 2017-12-18 12:52
Could someone kindly provide any updates on this issue?

**Comment by rickmak** [comment] 2017-12-22 08:19
I discovered in npm doc: https://docs.npmjs.com/misc/config#environment-variables You may give a try to `NPM_CONFIG_OTP`.

**Comment by vvo** [comment] 2018-01-28 00:28
Was not able to use npm_config_otp, it does not change anything. Maybe because I am also using npmClient: yarn and yarn does not support that?

**Comment by vvo** [comment] 2018-01-28 00:30
cc @neoziro is this working for you? What's the command line you are using exactly?

**Comment by neoziro** [comment] 2018-01-28 08:48
`NPM_CONFIG_OTP=123456 lerna publish`

But I finally turn two factor authentication on npm to auth-only and I am very happy 👍.

**Comment by vvo** [comment] 2018-01-28 13:23
Indeed that ease the process, here's how to do it:

```sh
npm profile disable-2fa
npm profile enable-2fa auth-only
```

thx @neoziro

**Comment by Bamieh** [comment] 2018-01-29 09:24
@rickmak true, i wrote a custom bash script for the publishing but was faced with this issue (1 otp is not enough sometimes). my solution to this was to use 2fa in `auth-only` mode only

**Comment by freaktechnik** [comment] 2018-02-25 17:07
This seems to be the same issue as #1091 except that it is less specific about how to solve the issue?

**Comment by evocateur** [comment] 2018-02-28 01:40
Closing as a duplicate of #1091

**Closed by evocateur** 2018-02-28 01:40 UTC
Labels: duplicate
