### ISSUE TITLE
git checkout fails after successfully publishing npm package

### ISSUE THREAD

**Issue by sathyavikram** [lerna/lerna#1801] opened 2018-11-29 10:53 UTC
git checkout fails after successfully publishing npm package. 

Lerna tries to checkout `packages/**/*/package.json` throws error.
If I manually checkout `packages/**/package.json`, works fine.

## Expected Behavior
git checkout successfully after publishing package

## Current Behavior
`lerna ERR! Error: Command failed: git checkout -- packages/**/*/package.json
lerna ERR! error: pathspec 'packages/**/*/package.json' did not match any file(s) known to git
lerna ERR! 
lerna ERR!     at makeError (/Users/vikram/my_documents/develop/devcharts/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/vikram/my_documents/develop/devcharts/node_modules/execa/index.js:278:16)
lerna ERR! lerna Command failed: git checkout -- packages/**/*/ package.json
lerna ERR! lerna error: pathspec 'packages/**/*/package.json'  did not match any file(s) known to git
lerna ERR! lerna `

```json
{
  "packages": [
    "packages/**/*"
  ],
  "version": "0.0.4",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

macOS Sierra
Attached is lerna-debug.log

Github: https://github.com/workswithweb/devcharts

[lerna-debug.log](https://github.com/lerna/lerna/files/2628781/lerna-debug.log)

**Comment by evocateur** [comment] 2018-11-29 16:36
I believe this is a duplicate of #1786, which should be fixed by the just-published lerna v3.5.1

**Closed by evocateur** 2018-11-29 16:36 UTC
