### ISSUE TITLE
Cannot find module 'nx/src/lock-file/lock-file'

### ISSUE THREAD

**Issue by dep** [lerna/lerna#3459] opened 2022-12-13 15:52 UTC
## Current Behavior

Currently when I try to publish my apps I receive the following error:

`Cannot find module 'nx/src/lock-file/lock-file'`

Full stack:

```
Run npx lerna run tsc && npx lerna publish --include-merged-tags --conventional-commits --registry https://npm.pkg.github.com
lerna notice cli v6.0.1
lerna info versioning independent
lerna info ci enabled
lerna success run No packages found with the lifecycle script 'tsc'
/home/runner/work/Titan/Titan/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

Error: Cannot find module 'nx/src/lock-file/lock-file'
Require stack:
- /home/runner/work/Titan/Titan/node_modules/@nrwl/devkit/index.js
- /home/runner/work/Titan/Titan/node_modules/@lerna/version/lib/git-add.js
- /home/runner/work/Titan/Titan/node_modules/@lerna/version/index.js
- /home/runner/work/Titan/Titan/node_modules/@lerna/publish/index.js
- /home/runner/work/Titan/Titan/node_modules/@lerna/publish/command.js
- /home/runner/work/Titan/Titan/node_modules/lerna/index.js
- /home/runner/work/Titan/Titan/node_modules/lerna/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/Titan/Titan/node_modules/@nrwl/devkit/index.js:242:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/Titan/Titan/node_modules/@nrwl/devkit/index.js',
    '/home/runner/work/Titan/Titan/node_modules/@lerna/version/lib/git-add.js',
    '/home/runner/work/Titan/Titan/node_modules/@lerna/version/index.js',
    '/home/runner/work/Titan/Titan/node_modules/@lerna/publish/index.js',
    '/home/runner/work/Titan/Titan/node_modules/@lerna/publish/command.js',
    '/home/runner/work/Titan/Titan/node_modules/lerna/index.js',
    '/home/runner/work/Titan/Titan/node_modules/lerna/cli.js'
  ]
}
```

## Expected Behavior

Build to run without errors

### Environment

```
lerna notice cli v6.0.1
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Utilities:
    Git: 2.37.1 - /usr/bin/git
  npmPackages:
    lerna: 6.0.1 => 6.0.1
```

**Comment by crusoexia** [comment] 2022-12-14 11:49
Looks like a dependency issue: the @nrwl/devkit@15.3.3 that the lerna@6.2.0 depends on rely on nx@^15.3.0, but lerna still depends on nx@15.0.0 caused the issue.

**Comment by lucastobrazil** [comment] 2022-12-26 11:10
Same here - @crusoexia did you manage to fix the issue?

This is what we have in our monorepo:
```
"lerna": "^5.5.2",
"nx": "^14.5.2",
```

**Comment by JamesHenry** [comment] 2022-12-26 18:46
@crusoexia Lerna's range definitions for "nx" and "@nrwl/devkit" are always both the same - `">=14.8.6 < 16"` at the time of writing.

I cannot reproduce this issue with a new lerna workspace with lerna `6.3.0`, nor an Nx + Lerna combined workspace, so hopefully this can be marked as resolved.

If anybody experiences any issues with the latest version of lerna please open a new issue with full reproduction instructions.

Many thanks!

**Closed by JamesHenry** 2022-12-26 18:46 UTC
Labels: type: bug
