### ISSUE TITLE
`ignore` not work with bootstrap

### ISSUE THREAD

**Issue by HsuTing** [lerna/lerna#1511] opened 2018-07-20 03:37 UTC
## Expected Behavior

The package which match the pattern of `ignore` should be ignored.

## Current Behavior

Still Install dependencies in package which should be ignored.

## Steps to Reproduce (for bugs)

`yarn lerna bootstrap` or `yarn lerna bootstap --ignore test-*`

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.2.14",
  "command": {
    "bootstrap": {
      "ignore": "test-*"
    }   
  },  
  "changelog": {
    "repo": "meepshop/meep-lerna",
    "cacheDir": ".changelog",
    "labels": {
      "PR: Breaking Change :boom:": ":boom: Breaking Change",
      "PR: New Feature :rocket:": ":rocket: New Feature",
      "PR: Bug Fix :bug:": ":bug: Bug Fix",
      "PR: Docs :memo:": ":memo: Documentation",
      "PR: Internal :house:": ":house: Internal"
    }   
  },  
  "lerna": "2.11.0",
  "npmClientArgs": [
    "--no-package-lock"
  ],  
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

<details><summary>bootstrap command information</summary><p>

```js
lerna info version 2.11.0
lerna info ignore test-*
lerna info Bootstrapping 3 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 3 packages
```
</p></details>

## Context

I do not want to install dependencies in the packages which are named by `test-*`, like `test-utils`.
Because `test-*` packages are just used for `testing`, I do not need to use this in the development step.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.2.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by evocateur** [comment] 2018-07-24 15:47
I find it hard to believe development doesn't involve testing.

**Comment by evocateur** [comment] 2018-07-25 00:38
Lerna is meant to facilitate development of multiple npm packages. It's not meant to fix broken/slow packages.

That being said, does the issue repro with `lerna@next`?

**Comment by doug-wade** [comment] 2018-07-30 18:35
Closing as duplicate of #1421

**Closed by doug-wade** 2018-07-30 18:35 UTC
