### ISSUE TITLE
[Bug] NPM throws error during concurrent `lerna bootstrap`

### ISSUE THREAD

**Issue by iantanwx** [lerna/lerna#397] opened 2016-10-30 10:04 UTC
We've just shifted over to using `lerna@2.0.0-beta.30`. When running `lerna bootstrap` in Travis CI with no concurrency limit, we randomly see this error occurring when installing a git npm dependency.

```
Errored while running BootstrapCommand.execute
npm ERR! Command failed: git clone --template=/home/travis/.npm/_git-remotes/_templates --mirror ssh://git@github.com/scope/repo.git /home/travis/.npm/_git-remotes/git-ssh-git-github-com-scope-repo-git-8d9e84ee
npm ERR! fatal: destination path '/home/travis/.npm/_git-remotes/git-ssh-git-github-com-scope-repo-git-8d9e84ee' already exists and is not an empty directory.
```

I have not seen this issue encountered so far. It appears that this is caused by a race condition between two packages that are cyclical dependencies and also have the same dependency: if one finishes fast and then the other starts, everything works out fine. If not, they both try to write to the same directory, and `lerna bootstrap` fails. I am not sure how to go about fixing this, or I would submit a PR.

Also, great work on lerna!

**Comment by thejameskyle** [comment] 2016-11-16 19:17
Can you create a repo that reproduces this? Two separate npm processes shouldn't be touching the same directory. I'm not sure how this would happen

**Comment by iantanwx** [comment] 2016-11-17 13:58
@thejameskyle just dropping in to let you know I'll try to recreate this issue. We moved that npm package into our `lerna` repository and the issue went away. It _could_ be a travis cache issue.

**Comment by doug-wade** [comment] 2018-04-13 07:05
Closing due to a lack of repro

**Closed by doug-wade** 2018-04-13 07:05 UTC
Labels: Tag: Bug Fix
