### ISSUE TITLE
how to use conventional commits correctly?

### ISSUE THREAD

**Issue by rileylnapier** [lerna/lerna#1230] opened 2018-01-23 01:40 UTC
hi, i have a question on the right way to use conventional commits and changelogs with lerna.  everytime i run lerna publish, i seem to be getting duplicate changelog entires and i'm not sure what i'm supposed to do.

right now i have developers creating feature branches and using commitizen to generate commit messages.

we all land on a "staging" branch using pull requests (without squashing commmits) when our work is done and on the staging branch, i run lerna publish.  

after running lerna publish, i merge into our production branch which deploys our application suite.

the problem is that everytime i run lerna publish, it seems to be adding the same changelog over and over again.  am i supposed to be squashing my commits at some point?  how does lerna know to ignore commits after a publish has happened?

what am i doing wrong??

thanks,

**Comment by alexeyraspopov** [comment] 2018-01-24 06:17
By default, `lerna publish` will attempt to do publish of packages that were updated (have new commits) since previous git tag. Do you specify `--since` when run `lerna publish`?

**Comment by DavideDaniel** [comment] 2018-02-04 00:31
This might be actually an inherent flaw in the mechanism of lerna publish. We have this issue as well and have been debating how to use lerna in CD. There are some strong opinions about the git tagging being conflated with the publish. 

An example repro:
1. make a change in any package in an independent mode lerna repo
2. run `lerna publish --skip-npm --skip-git --conventional-commits --yes`
3. run `lerna publish --skip-npm --conventional-commits --yes`

You can immediately tell that the command should not be run twice. Because package.json is going to be evaluated for the git tag step in the 2nd publish there will always be a change from the first publish that will then duplicate the bump.

We currently have a lerna repo that multiple teams contribute to. In order to enable CD publishing and prevent git tag fiascos we have had to do some git gymnastics in our pipeline.

Please feel free to point out something we've overlooked!

**Comment by evocateur** [comment] 2018-05-08 19:27
@greypants In lerna 2.x, I'm not sure anymore. I'm really itching to make 3.x `latest`, personally.

If I had to guess, it's because the tag might not be the "first" one accessible from the current branch. A reproducible example would be required to make further guesses/diagnoses.

**Comment by greypants** [comment] 2018-05-09 17:00
@evocateur Same results with v3.0.0-beta.20 - shows the correct current version, but for whatever reason, compares with an older one.

**Comment by greypants** [comment] 2018-05-09 17:27
So we're narrowing this down. My coworker, @claytuna and I are both tagging releases, and for whatever reason, Lerna only respects my tags.

1) I manually created a tag `v3.3.2` and pushed it to github
2) I ran `lerna publish` and "Comparing with `v3.3.2`" correctly logged
3) @claytuna tried steps 1 and two with a new tag `v4.0.1`
4) He rean `lerna publish` and lerna is comparing with MY last tag instead of his newly created one: "Comparing with `v3.3.2`"

Both our tags show up when running `git tag -l`, and appear in Github.

Any ideas about how different users might affect what's happening here?

**Comment by evocateur** [comment] 2018-05-09 17:35
The tags need to be annotated tags, not “lightweight” tags. The difference is basically the -m argument (or -a, but -m implies -a).

**Comment by greypants** [comment] 2018-05-09 18:34
That was it! Thanks!

Running `git describe --abbrev=0` showed the issue. The issue happened because we were creating tags manually, and they either were associated with the wrong commit, or weren't annotated. The original issue happened when a coworker accidentally published to his fork instead of origin, then we tried to manually create the tags on origin.

**Comment by greypants** [comment] 2018-05-10 14:45
For anyone else running into this, this also occurs if you do your `--conventional-commits` release on a branch, **and then squash and merge with master**. This is because the original commit hash that you're tagging is re-written to a different hash when you either squash and merge or rebase and merge, thus orphaning the tag. 

Running `git log --oneline --decorate=short`, you should see your release commits appropriately tagged like so:

![image](https://user-images.githubusercontent.com/647549/39875458-b192c7ea-543e-11e8-9a1f-6c76c5d1e826.png)

If you've accidentally orphaned a tag (no tag appears next to your commit like above), you can `git checkout` the release commit hash, then `git tag -af <your tag here>` to force update an annotated tag to point to the right hash again. Then `git push -f origin/master --tag <your tag here>` to update the tag on GitHub.

**Comment by doug-wade** [comment] 2018-05-16 00:25
@greypants Thanks for including such a detailed description of what happened and how future users can diagnose and fix this!  It sounds like this issue is resolved, so I'm going to close it, but if I'm wrong, don't be shy about reopening.

**Closed by doug-wade** 2018-05-16 00:25 UTC
Labels: repro-needed
