### ISSUE TITLE
bootstrap ignore * with scoped packages

### ISSUE THREAD

**Issue by 7ynk3r** [lerna/lerna#862] opened 2017-06-02 18:19 UTC
The following configuration doesn't work using **scoped packages**.
```
  "commands": {
    "bootstrap": {
      "ignore": "*"
    }
  },
```

## Expected Behavior

It should ignore all packages during bootstrap.

## Current Behavior

It bootstraps all packages.

## Possible Solution

None

## Steps to Reproduce (for bugs)

Just use the following configuration

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.4",
  "version": "1.0.0",
  "npmClient": "yarn",
  "commands": {
    "bootstrap": {
      "ignore": "*"
    }
  },
  "packages": [
    "packages/common-elements"
  ]
}
```
</p></details>

</p></details>

## Context

I've worked around this by adding the scope and the *
```
  "commands": {
    "bootstrap": {
      "ignore": "@m/*"
    }
  },
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 4.5.0 |
| `yarn --version` | 0.21.3 |
| `node --version` | v7.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by evocateur** [comment] 2017-06-06 16:32
What is the use case for this? If you're ignoring _everything_ when you bootstrap, ....why bootstrap?

**Comment by doug-wade** [comment] 2018-07-30 18:36
Closing as duplicate of #1421

**Closed by doug-wade** 2018-07-30 18:36 UTC
