### ISSUE TITLE
Nested directory support

### ISSUE THREAD

**Issue by patrickheeney** [lerna/lerna#11] opened 2016-01-07 02:28 UTC
I currently access packages like this `import { foo } from 'foo/bar';`. It seems the current bootstrap only creates `node_modules/foo/index.js` with `module.exports = require('/full/path/packages/foo');`. Thus when accessing `foo/bar`, it `Error: Cannot find module`. 

What would be the best path forward for supporting this? The only thing I can think of is to find all `*.js` paths and then create that path with matching exports.

**Comment by thejameskyle** [comment] 2016-01-28 20:54
@kittens any reason we don't just symlink everything?

**Comment by thejameskyle** [comment] 2016-02-01 23:26
This should be fixed by #34, but be warned that we're not sure if this will cause other issues and we might revert it with another major bump.

**Comment by thejameskyle** [comment] 2016-02-02 00:12
Symlinking causes other issues with npm, we'll have to figure something else out.

**Comment by patrickheeney** [comment] 2016-02-11 22:45
This seems to be outside the scope of the project, closing this.

**Comment by thejameskyle** [comment] 2016-02-11 22:57
It's not, we need to figure it out in another way

**Comment by evocateur** [comment] 2016-02-23 23:30
I've hit this too, it's especially nasty when you're trying to test stuff that is trying to import a subpath generated by Babel (`const foo = require('my-sibling-package/lib/foo');`). An approach like [npm-sync](https://github.com/neoziro/npm-sync) can work for simple use cases, but clearly doesn't scale for a `lerna`-based monorepo.

Symlinking is it's own ball of wax, since node's `require()` always calls `realpath` on the requested module path and thus it resolves the symlinks and now everything breaks because symlinks are. the. worst.

Maybe expand the [`createLinkedDepFiles`](https://github.com/kittens/lerna/blob/master/lib/commands/bootstrap/linkDependenciesForPackage.js#L5) method to loop over non-npmignored files and require those as well?

**Comment by thejameskyle** [comment] 2016-02-23 23:36
I want to narrow down the issue in npm and see if it can be patched.

**Comment by patrickheeney** [comment] 2016-02-23 23:38
@evocateur I thought of the same as well and prototyped locally. One issue I ran into that you need a watcher when adding new files as they would need that shim to link the dependency files.

@thejameskyle I am not sure that npm is the issue here or what the goal would be? The module code is frozen in npm so introducing new behavior to load files locally isn't something they are going to accept (don't have a link to cite this but its in a discussion about linking local modules).

**Comment by thejameskyle** [comment] 2016-02-24 01:48
@patrickheeney I tried [symlinking previously](https://github.com/kittens/lerna/pull/34) however `npm install` has weird behavior around installing recursively through symlinks which I don't think is intentional.

**Comment by dchambers** [comment] 2016-02-24 11:22
Sorry, just another me too message, but just to say that Lerna is unusable for my use-case at present without this feature.

If there are issues with sym-linking the directory, is it not possible to use the current approach of adding `module.export = require()` files, but for all files?

**Comment by thejameskyle** [comment] 2016-02-24 11:26
We can copy all files if that solves things for you for now. I'm just wary about it and I would put it under and unstable flag.

Please reserve judgement on lerna though, it's still in its early stages and I want to figure all this out in the coming weeks

**Comment by dchambers** [comment] 2016-02-24 12:51
> We can copy all files if that solves things for you for now. I'm just wary about it and I would put it under and unstable flag.

Sounds good to me :+1:

**Comment by eirslett** [comment] 2016-05-07 11:41
I use Windows, which, for all its goodness, doesn't have symlinks, so projects that rely on it are not possible to work on... npm handles linking very well :-)

**Comment by ainscore** [comment] 2016-06-05 21:28
@thejameskyle Are you able to provide more details on the weird behavior in npm install when symlinks are present?  Does it affect all versions or just a certain subset?

**Comment by thejameskyle** [comment] 2016-06-06 06:26
I don't remember exactly what happens, but it was doing something like trying to recursively install things

**Comment by bkniffler** [comment] 2016-06-09 23:18
I just discovered lerna through the open-sourced cloudflare ui package, and this was the first thing I thought about when I've seen the index.js proxy method lerna uses (which is by the way a very clever solution!). I've been trying npm link and webpack/babel alias, but these solutions all have their drawbacks.

But now that its so easy to maintain many packages with lerna I will just go and migrate the stuff that I import through `import {x} from "foo/bar"` to a new repository for `import {x} from "foo-bar"`. This might not be applicable to all scenarios, but it can be a simple sufficient one for some. Especially since in most cases, everything you separate into a module folder that isn't within your root scope might be worth a reconsideration for separation into a new package.

**Comment by sheerun** [comment] 2016-06-11 09:15
Why not symlink all the js files instead of just main?

**Comment by sheerun** [comment] 2016-06-11 09:15
I mean proxy

**Comment by rygine** [comment] 2016-06-14 15:58
i've created an updated bootstrapping process that allows for this via symlinks.

more info here: https://github.com/lerna/lerna/issues/215

**Comment by zkochan** [comment] 2016-07-01 22:40
I just tried to link the packages manually via the `npm link` in my monorepo and it worked (on windows). From the thread it seems to me that nobody tried this solution yet.

**This is what I did.** I have package A and package B. Package A is in the dependencies of package B.

1. I run `npm link` in package A
2. I `cd` to package B and run `npm link A`
3. I run `npm install` in package B

**Results.** There is a symlink to package A in the `node_modules` of package B. `npm install` is successful and it does not override the symlink (I used npm v3.8.3 and node v5.10.0). I think the npm linking algorithm is smart enough* and can be used for a better bootstrapping in lerna.

\* - observation, I didn't look into the source code yet

**Comment by ainscore** [comment] 2016-07-02 06:16
I think that the install behavior with symlinked packages has been fixed, though I'm not sure in which version of npm.  I'm hoping to find some time to narrow it down and provide results here.

**Comment by zkochan** [comment] 2016-07-02 09:12
Might be true. However, should we symlink manually if there is a [builtin command for that in npm](https://docs.npmjs.com/cli/link)? IMHO, it is better to use the builtin `npm link` method because it'll be supported by npm itself

**Comment by ainscore** [comment] 2016-07-05 06:04
It is nice to use a supported command, however, by using that you also limit yourself to linking one version of that package per npm installation on that system.

**Comment by zkochan** [comment] 2016-07-05 19:20
I haven't had a situation where I needed to link two versions of the same package. I am guessing it would be more logical to install the older version as an actual dependency.

**Comment by matthewdavidson** [comment] 2016-07-15 13:05
It would be nice to see a symlink / `npm link` based approach to solve this. It would open up Lerna for use in css/scss projects too e.g:

Package A:
```json
{
  "name": "package-a",
  "main": "index.scss"
}
```

Package B:
```json
{
  "name": "package-b",
  "dependencies": {
    "package-a": "0.0.1"
  }
}
```

Given that npm is being used more and more for front end projects - not just nodejs - this makes sense, doesn't it?

**Comment by cchamberlain** [comment] 2016-07-15 14:53
`npm link` has its shortcomings (at least on Windows) which is the primary reason I switched to lerna. In nested linked projects, `npm install` will often not do what it would have done with non-linked packages.  Specifically it will not touch dependencies because they are part of another package that is linked and you will commonly get errors regarding missing dependencies. Fix is typically to nuke node_modules, and spend hours rebuilding / relinking all the projects.

Lerna's proxy style is a much closer reproduction of the real world with the caveat of not being able to import one-off files from the package. Creating 1:1 file mappings (module re-exports / soft links?) will allow lerna to remain decoupled from npm's bugs.

**Comment by sheerun** [comment] 2016-07-15 15:14
How about patching `require` instead?

**Comment by zkochan** [comment] 2016-07-15 18:28
In one of my projects I use a fork of lerna that uses pnpm instead of npm for installing dependencies + symlinking for connecting the packages. It works great!

Maybe symlinking would work with npm as well. However, using pnpm on NodeJS >= v6.3.0 gives an interesting opportunity to use a shared storage for the dependencies https://github.com/rstacruz/pnpm/issues/244. As a consequence, dependencies are not only installed faster, but they are not downloaded separately for the different packages. This might be off topic, so if someone wants to give it a try I can write more details about it in a gist or somewhere else. Here's the project where I used this approach https://github.com/mosjs/mos/tree/0dadff422bc9e00b831845934cd3c6cd8fdba374

**Comment by patrickheeney** [comment] 2016-07-15 20:38
Since originally posting this I have also moved onto pnpm with some custom scripts instead of using lerna. I have several issues open with pnpm which would prevent anyone using it on a complex app. It has an elusive bug which causes install to fail 50% of the time with a lot of dependencies (symlink + stream error). It also doesn't support optionalDependencies and some other npm features which causes some popular packages to fail installation. Manually working around these issues has solved this requirement for me. 

I have also tried patching require, using npm link, and expanding the proxy support to include all files. All of them ended up being brittle and unworkable for me.

**Comment by thejameskyle** [comment] 2016-07-21 17:33
This issue got off topic, locking.

**Comment by patrickheeney** [comment] 2016-07-23 20:25
This is a summary of some different options discussed above:

**Index Proxy** - This what lerna looks to be doing right now. It generates a proxy to `require` the real path of `package.json main`.

Cons: It only supports one entry file.

**Proxy Everything** - Lerna could be expanded to proxy all files to point to the real path so that `require`. 

Cons: How would it handle non-js files? What happens when you create new js files (manual step to rebuild the proxy? watchers?). 

**NPM Link** - Adapt lerna to npm link all packages. 

Cons: Complex with lots of packages. Can only have one version of a dependency linked at a time. Other issues documented above and elsewhere.

**Symlink** - Create a symlink process to link all the modules. Not sure this is possible on its own without the next point.

Cons: Will it work on windows smoothly? How to avoid complexity? Was mentioned above it had some issues with recursive node modules.

**Global Cache / Symlink** - Using tools like `pnpm` or other projects that store all npm packages in a global cache. Then recursively symlink to link them. 

Cons: Will it work on windows smoothly? Adds another dependency. Can't use `npm` directly for a few commands.

**Patch NPM** - Patch the NPM require process to change its behavior.

Cons: NPM won't change how modules will load due to standardization. Patching the require process will be brittle and not future proof.

---

I have done some extensive testing of all of these. My current thoughts:

The **proxy everything** approach is the easiest to roll into the project now. It is also error prone because of the inability to add new files, change paths, etc without a manual step to rebuild or initiate watchers. It seems like a perfect starting point.

The **global cache / symlink** approach I have been using outside of learna, but I'd like to roll this into it. A [fork](https://github.com/lerna/lerna/issues/11#issuecomment-233030648) also exists to do something similar. I personally love this approach as it is what I think `npm 3` should have been. However it does depart a bit from `npm`'s default behavior. It is the best candidate that I have found to handle this seamlessly. 

One interesting thought is, can we use both approaches behind flags? Use **proxy everything** by default and enable the **global cache / symlink** with a flag. We are essentially just talking about two strategies to `proxy` the `node_modules`, so it may be doable.

**Comment by rtsao** [comment] 2016-07-24 20:35
https://github.com/timoxley/linklocal supports Windows

**Comment by patrickheeney** [comment] 2016-07-24 20:39
This would fall under the **Symlink** section above which was tried and reverted. Those issues would likely need to be resolved in order to consider that option.

**Comment by hzoo** [comment] 2016-08-08 02:26
To add to the discussion - https://github.com/boennemann/alle, I wrote up https://github.com/boennemann/alle/issues/1

**Comment by ainscore** [comment] 2016-08-11 20:47
I didn't have much to go by, but based on the brief descriptions by @kittens  here: https://github.com/lerna/lerna/issues/78#issuecomment-192259563 and @thejameskyle here: https://github.com/lerna/lerna/issues/11#issuecomment-188005150, it would seem the issues with symlinks and npm are rooted in this npm bug https://github.com/npm/npm/issues/10343, which I believe at this point is partially patched though i haven't had a chance to figure out which versions, but at least npm 3.3.12 is affected, which was the latest around the time that the symlink experiments were happening.

The issue arrises when you have symlinked dependencies and then attempt to install a package by name, which Lerna does do in its install command: https://github.com/lerna/lerna/blob/ce3e1eddc65689ec92fcf3ec4a3096bc2cda4686/src/commands/BootstrapCommand.js#L185.

Without having much context on the internals, is it possible that, when bootstrapping, we could symlink local dependencies for a package first, and then run 'npm install' for the package, thus avoiding the install-by-name issue?

**Comment by patrickheeney** [comment] 2016-08-12 17:06
@ainscore Thanks for tracking that down! 

I did just that on my private repo. I symlinked all local packages first so that if you install one with a dependency on another, it can be resolved. I then used `pnpm` to install within each package and had it exclude any local packages since I added the symlink in the first step. I used `pnpm` for the global store, symlink everything, faster installation, and better install API. I assume you could likely do the same with `npm`. I haven't found any edge cases so far so maybe it would be a good place to start. Alternatively [https://github.com/lerna/lerna/issues/11#issuecomment-238128422](alle) sounds like it could solution with much less hackery.

**Comment by patrickheeney** [comment] 2016-08-12 17:20
I will try to summarize this again as I think we have 3 different concepts that should be pursued and a lot of discussion that lead to this point. 

**Concept #1:** Modular API - https://github.com/lerna/lerna/issues/174. This would push all ideas into user-land, opening up the possibility for anyone to develop a different set of functionality like bootstrap strategies. It could also allow an code sharing between tools that may have similar goals but different approaches.

**Concept #2:** Symlinks. Work around the nested problem by addressing the issues that we have identified by using symlinks. Make them cross-platform, symlink local dependencies, selectively install other dependencies, etc.

**Concept #3:** Alle. That repo has a simple change to the structure that wouldn't require any symlinks. The drawbacks are minimal. 

All 3 of these have been explored and could be viable options for solving this. Hopefully we can get some feedback by the project maintainers to determine a direction, or directions, to push forward with.

**Comment by gigabo** [comment] 2016-08-12 18:53
Thanks for tracking down the history here @ainscore.

And thanks for sticking with this @patrickheeney.  That summary is really useful.

My thoughts:

Concept 1: I think #174 is a good direction for Lerna (for all of the reasons I outlined there), but I don't know how soon we'll be able to get there.  Even the first step of making the existing `lerna` module a package within a Lerna repo involves moving most of the code.  That will break all open PRs, and conflict with all half-baked code people are working on (probably more painful for me than anybody).  So I think step zero there is to clear as much of the PR backlog and fix as many open issues as possible.

Concept 2: Symlinks seem worth trying again.  Even with the links that @ainscore dug up I'm still having trouble figuring out what exactly caused it to be reverted originally.  I think what we need here is a small, _targeted_ PR that just tries a single strategy.  I still hold out hope that there is a strategy that will work for everyone.  That may just be wishful thinking, but IMO it would be ideal.

Concept 3: The use of `node_modules` directories suggested in `alle` is cool.  It makes me a little nervous, though.  There's so much special handling of `node_modules` that I worry about unforeseen headaches.

I'm most bullish on symlinks in the short term.  We have #237 and #263 open currently, though neither is up-to-date.  I'll ping the authors on those tickets to get them rebased.  I'll also need to review them carefully to understand how they're different.

This is, I think, the biggest road block for Lerna right now.  It's a hard problem, but worth solving.

@hzoo, @thejameskyle - Please chime in if I've misunderstood or misrepresented anything here.

**Comment by hzoo** [comment] 2016-08-12 19:14
agree with what @gigabo is saying - definetely seems like 1 is the way to go so no one has to wait on lerna itself - just build on top of it.

Every command is an independent command - should be free to test out a version of bootstrap or anything else and then we can include it in core if it works for everyone. I think we want to encourage fast local development/iteration on ideas/strategies that can eventually be added so everyone else can use it too?

**Comment by ainscore** [comment] 2016-08-12 19:26
I did have one last thought in a similar vein to Concept3/alle, which is to use initialized environments a la virtualenv for python.  So in initializing the environment, lerna would add 'packages' to the NODE_PATH.  This would also remove the bootstrap phase like alle.  It too has its drawbacks as this type of setup can be confusing without shell support the way many shells have for virtualenv, but it would maintain the same folder structure that lerna currently has.

**Comment by patrickheeney** [comment] 2016-08-12 19:46
@ainscore https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders It sounds like NODE_PATH is for historic purposes and they encourage local node_modules solutions. They also list a few potential side effects. Also, what if you had a private package called `babel` in packages/. You would have to ensure that every package name is unique among all of your dependencies and dependency's dependencies or it could also cause side effects.

**Comment by ainscore** [comment] 2016-08-18 06:08
@patrickheeney I believe sub-dependencies would still be resolved through the normal node_modules way unless a sub-dependency was missing in which case it would search on the NODE_PATH ... or maybe I'm misunderstanding what you mean, but nevertheless, I agree, it is preferable to use a method more in line with the convention.

**Closed** 2016-09-08 20:50 UTC
Labels: enhancement

**Comment by dchambers** [comment] 2016-09-08 21:41
Yay! Great work to everyone that helped to get this issue across the line :+1:

**Comment by k3n** [comment] 2017-02-08 21:55
Is there a summary of what was actually implemented anywhere? I've read through this issue, the changes, and the docs, but I'm unclear what the net-net is.

My specific question is: in my root `package.json` I have a dependency `foo`. This dependency is also present as `packages/foo`. I would like the app to install whichever version of `foo` is currently present at `packages/foo`. Should I use a simple `file:` link, or is there something else that I should do?

Thanks in advance.

**Comment by hzoo** [comment] 2017-02-08 22:03
Uhh well one of the changes is that bootstrap uses symlinks + you can use the packages key to specify the folders that will be packages https://github.com/lerna/lerna#lernajson including root (`.`)

**Comment by k3n** [comment] 2017-02-09 15:22
Thank you, though I'm still battling through my problem.

**Comment by k3n** [comment] 2017-02-10 16:15
Ok, I think my issue is that I was trying to have a 'top-level' module. Once I made everything a package, it works as expected.

**Comment by shimmerjs** [comment] 2017-05-17 16:28
I'm still experiencing issues symlinking when running `lerna bootstrap`.  I have 2 packages, one depends on the other, both are under `packages/`, `lerna boostrap` reports that it has symlinked the two, but `packages/a/node_modules/b` is not a symlink to `packages/b`, so changes are not propagated.

**Comment by aga5tya** [comment] 2017-05-30 04:40
I have the exact problem as @shimmerjs and @k3n,, i have to manually run lerna bootstrap to get the changes across, anything i am missing out on here ?

**Comment by shimmerjs** [comment] 2017-05-30 12:09
@aga5tya I fixed this by specifying the dependencies with explicit versions (instead of `latest`) and then `lerna bootstrap` realized they needed to be linked.  Moving forward, `publish` will keep them in sync.  This is confusing behavior granted `npm` itself no longer is this strict about linking, but definitely workable.  Cheers.

**Comment by liuchong** [comment] 2017-10-15 08:56
I'm also want a feature which let me "require/install/link a package without publish"

**Comment by evocateur** [comment] 2017-10-15 15:35
@liuchong If you’re not publishing any packages, don’t use lerna. Relative imports are not bad.

That said, you can add `”private”: true` to the package.json of any package you do not want lerna to publish. Ensure that the private package is not a runtime dependency of anything you _do_ publish, or the dependents will be broken when consumed outside your monorepo.
