### ISSUE TITLE
Passing unknown command to lerna should print to stderr and have a non-zero exit code

### ISSUE THREAD

**Issue by martijnthe** [lerna/lerna#1107] opened 2017-11-09 16:30 UTC
## Expected Behavior
```
$ yarn lerna bogus_cmd
yarn run v1.3.2
[REDACTED]/node_modules/.bin/lerna bogus_cmd
ERROR: Known command 'bogus_cmd' (or something along these lines)
✨  Done in 0.41s.
$ echo $?
1
```

## Current Behavior
```
$ yarn lerna bogus_cmd
yarn run v1.3.2
[REDACTED]/node_modules/.bin/lerna bogus_cmd
✨  Done in 0.41s.
$ echo $?
0
```
## Possible Solution
Seems obvious?

## Steps to Reproduce (for bugs)
See above.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.4.0",
  "version": "0.7.0",
  "commands": {
  },
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.1.3 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment] 2017-11-15 18:58
Duplicate of #1098

**Closed by evocateur** 2017-11-15 18:58 UTC
