### ISSUE TITLE
Option to remove "v" from the git tag

### ISSUE THREAD

**Issue by ksmolyanin** [lerna/lerna#1399] opened 2018-04-25 13:32 UTC
My team insists on not using "v" in git tags like "v1.2.3" but create tags like "1.2.3".

## Expected Behavior
There is an option to not add "v" to git tags

## Current Behavior
It always add "v".

**Comment by evocateur** [comment] 2018-04-25 16:29
In the "fixed" (default) versioning method, that's true. Independent versioning always uses `${packageName}@${version}`, and that isn't likely to change.

Presumably you're also setting npm's [tag-version-prefix](https://docs.npmjs.com/misc/config#tag-version-prefix) config to `""`? If so, I think we can just read that and use it (in all non-independent cases, since it defaults to `"v"`).

**Comment by ksmolyanin** [comment] 2018-04-25 19:54
Thank you for quick response! Actually I didn't know about tag-version-prefix. As for me it is a solution.

**Comment by evocateur** [comment] 2018-04-25 20:33
Well, I mean, right now `lerna` (`v3.0.0-beta.18`) does not respect this (since we're not calling `npm version`). We could add awareness of this fairly simply.

**Comment by ksmolyanin** [comment] 2018-04-26 10:30
Oops ... thank you for explanation. Yes, if it is possible it would be very good to add this feature!

**Comment by bochen2014** [comment] 2018-04-30 13:28
we have an issue with tag as well. 

we have `master` branch and `release` branch, both are monitored by CI pipeline. when a new commit is merged into either branch, a new build will be triggered and new npm packages will be published to  Prod/QA npm registry respectively.

the problem is that `release ` branch will be merged back into `master` at some time,  and when that happens, all tag will be brought over.  Since when lerna tags, it only tags version, not git branch, so `master` would think that it has published there before and wont' do a publish again--- yes, it did published somewhere before, but that was in QA, not Prod. 

we can delete the tag when merging `release` into `master`, but we then lose track of what has been published into QA; we really wish we could keep that tag.

this is not an urgent issue, but I think worth thinking about it

**Comment by bochen2014** [comment] 2018-04-30 13:35
I was also thinking, is having a prod npm registry and qa registry an evil thing to do?? 

I guess we can have only one registry, and utilise `pre-release` to differentiate prod version from qa version, but, , that means we will have to manage version manually. 
At the moment, we let `conventional-recommended-bump` to handle versioning for us in CI server, so there is no human intervention at all;

not sure which way to go, any comments will be  appreicated

**Comment by bochen2014** [comment] 2018-04-30 13:53
yep. I think we if add`-preid` in release branch , it may just work;
when merging `release` into `master`, we can  'graduate' those pre-release and have a full publish.`lerna` already has this behaviour as explained somewhere else

**Comment by evocateur** [comment] 2018-04-30 14:42
I would just use dist-tags, that’s what they’re for. Don’t bother with a release branch or a second registry.

**Comment by bochen2014** [comment] 2018-05-01 06:05
right. thanks for the info. 

I guess the only work that needs to be done using dist-tag approach is when merging ` release`  into `master`, I need to "promote" the package from `next` to `latest`;

**Comment by lehni** [comment] 2018-06-09 09:58
I would love to see this implemented also. I am migrating a project to Lerna that so far was using tags without 'v' prefixed to the versions, and that decision was informed by reading:

https://github.com/semver/semver/issues/204
https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version

**Comment by evocateur** [comment] 2018-08-08 22:38
This was fixed in #1522

**Closed by evocateur** 2018-08-08 22:38 UTC
