### ISSUE TITLE
Bootstrap command yields error, "Cannot find module '...' or its corresponding type declarations." when new local modules are using version postfixes

### ISSUE THREAD

**Issue by ds-its-jnj** [lerna/lerna#3346] opened 2022-09-28 23:00 UTC
## Current Behavior

When running the `lerna bootstrap` command locally I get the error, "Cannot find module '...' or its corresponding type declarations."

## Expected Behavior

Lerna should bootstrap the monorepo project without error.

## Steps to Reproduce

1. Create a new monorepo workspace with at least 2 modules
2. Add Module 1 as a dependency of Module 2
3. Set Module 1's package.json version string to something that contains a postfix such as, "0.1.0-alpha.1"
4. Run the bootstrap command
5. Observe that the error is produced

## Details

I think that this error is caused by a bug where if the linked local module has not yet been published to NPM, and it contains a custom version string that contains a postfix (such as "-alpha.1"), Lerna will not be able to locate the local dependency.

**Comment by fahslaj** [comment] 2022-10-14 22:20
Hi @ds-its-jnj , thank you for reporting this issue. Unfortunately, I was not able to reproduce the error following the exact instructions above. Using https://github.com/lerna/repro as a base, can you please create a minimal reproduction of the issue, include details about the versions of lerna, node, and the OS you are using?

**Comment by JamesHenry** [comment] 2022-11-29 14:37
Given no reproduction is available I will close this one for now

**Closed by JamesHenry** 2022-11-29 14:37 UTC
Labels: type: bug, blocked: repro needed
