### ISSUE TITLE
Lerna does not call "npm ci" when hoisting

### ISSUE THREAD

**Issue by mzyil** [lerna/lerna#2047] opened 2019-04-18 11:25 UTC
I know it's disabled per the following issue but in my testing I couldn't reproduce the same error neither in the `istanbuljs` repo nor in our own repo
https://github.com/lerna/lerna/issues/1865 
## Expected Behavior

When the `CI` environment variable is set, e.g. `CI=1`, Lerna should call `npm ci`
## Current Behavior

Lerna calls `npm install` with `--global-style` and `--no-save` arguments
## Possible Solution

Remove the code block here: https://github.com/lerna/lerna/blob/master/commands/bootstrap/index.js#L112
## Steps to Reproduce (for bugs)

1. Create a minimal repo with one package
2. Add `hoist: ["is-ci"]` to `lerna.json`
3. Add `is-ci` to the package's own dependencies
4. Run `lerna bootstrap --loglevel=silly` -> output shows `['npm', ['install']]` is called
5. Set the `CI` environment variable to `1` and call lerna: `CI=1 lerna bootstrap --loglevel=silly` -> output shows `['npm', ['install', '--global-style', '--no-save']]` is called

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
    "command": {
        "bootstrap": {
            "npmClientArgs": [
                "--loglevel=verbose",
                "--fetch-retries=5",
                "--fetch-retry-factor=20",
                "--fetch-retry-maxtimeout=180000",
                "--fetch-retry-mintimeout=5000"
            ]
        }
    },
    "hoist": [
        "class-validator",
        "deep-equal",
        "json-long",
        "long",
        "node-sass",
        "reflect-metadata",
        "typescript"
    ],
    "packages": [
        "packages/*"
    ],
    "version": "0.0.0"
}
```
</p></details>

## Context

I'm trying to prevent developers from (mostly by forgetting) submitting changes in the package.json files but not updating package-lock.json files.
## Your Environment

We use Buildbot for our CI (which isn't recognized by the `ci-info` package, that's why we explicitly set the `CI` env var

| Executable | Version |
| --- | --- |
| `lerna --version` | 3.13.2 |
| `npm --version`  | 6.9.0 |
| `node --version` | 8.14.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 18.10 |

**Comment by evocateur** [comment] 2019-04-24 23:42
`lerna bootstrap --hoist` mutates package.json in each leaf, so there's no way `npm ci` would even work. It's explicitly disabled when you enable `--hoist` (via lerna.json `hoist`, as you've configured it).

**Comment by mzyil** [comment] 2019-04-25 12:38
Correct me if I'm wrong but, if the `package.json` file is mutated, and the `npm install` command is called against that mutated file, then that would mean the `package-lock.json` file is created according to the mutated `package.json` file. So if in CI environment Lerna calls `npm ci` AT THE SAME STEP that where it's supposed to call `npm install`, than that would mean `npm ci` will see the mutated `package.json` file and 'accordingly mutated' (e.g., no entries for hoisted packages) `package-lock.json` file, which are in sync.

So I would say as long as the `package.json` file is mutated the same way it was mutated while calling `npm install`, there isn't any reason for `npm ci` to not work. If you look at my suggestion, that's what it does. Keep everything the same, just change the `subcommand`.

**Comment by evocateur** [comment] 2019-05-10 21:08
This all assumes that everyone working in the hoisted monorepo _never_ trundles down into a leaf directory and runs `npm install` directly. In my experience, this is an extremely counter-intuitive guideline for working in a monorepo, and thus gets violated 95% of the time.

If you're hoisting _at all_, I would recommend hoisting _everything_, otherwise you're almost predestined to suffer.

**Comment by mzyil** [comment] 2019-05-10 21:51
If you use hoisting, you don't go and `npm install` in the package folder anyway. Otherwise why use hoisting at all.

Our use case was for some packages that needed to have one and only one copy (the boring `class-validator` and `class-transformator` packages). We wouldn't even dream of going on and installing them in the package folder, as it would instantly break the tests.

Anyway we solved it by moving the MUST-BE-hoisted dependencies to `peerDependencies` and added another package that contained just a package.json with the said dependencies, then symlinked its `node_modules` folder to the top and committed the symlink.

But my suggestion is at least provide an option like `--force-ci-in-hoisting` or better yet `--force-ci-despite-of-hoisting` which makes people aware of what they put themselves into.

**Comment by intafon** [comment] 2019-12-20 16:36
I'm running into the same issue. In my case, however, because we have the package-lock.json at the top level checked in, when we invoke `npx lerna bootstrap --hoist` it alters the package-lock.json file, which is bad, because every time someone runs a build in their tree, there is all off the sudden a changed file in their tree.

What is the recommendation for installing dependencies in a build and dev environment for a company where only one team uses npm/lerna (i.e. the UI team)? I've seen claims that one should use `npx lerna link convert` but I'm not really clear that is what should be the procedure either.

**Comment by mzyil** [comment] 2019-12-20 19:59
@intafon you can pass `--no-save` to `npm`, depending on the configuration. No save prevents changes to the lock file, however the `node_modules` folder is still created differently. I.g. if a package has to be upgraded, the upgraded package will be installed but the change won't be written to the lock file

**Comment by intafon** [comment] 2019-12-20 21:01
@mzyil yeh, that is one way to go about it.

I did a couple of tests on offending machines:
- npx lerna bootstrap --hoist   --- dirties the tree
- npn lerna bootstrap               --- does not dirty the tree
- npm ci and npm install behave as expected

The solution looks to be for official builds to not use --hoist and only use that in dev situations perhaps (to save downloading react multiple times for example). Will update if that doesn't fly.

**Comment by joselcc** [comment] 2020-02-12 05:14
```
      // never `npm ci` when hoisting
      this.npmConfig.subCommand = this.hoisting ? "install" : "ci";

      if (this.hoisting) {
        // don't mutate lockfiles in CI
        this.npmConfig.npmClientArgs.unshift("--no-save");
      }
```
I think is fair to prevent running `npm ci` from a mutated `package.json`, my solution for this issue would be to hoist all the dependencies in root `package.json`, install the deps and create the symlinks: `npm ci && lerna link`

**Comment by grnch** [comment] 2020-03-24 03:24
@evocateur wrote:
> This all assumes that everyone working in the hoisted monorepo _never_ trundles down into a leaf directory and runs `npm install` directly. In my experience, this is an extremely counter-intuitive guideline for working in a monorepo, and thus gets violated 95% of the time.

It's even more counter-intuitive when you run `lerna bootstrap --ci` and... Lerna doesn't run `npm ci`!

We spent countless hours wrestling with unexpected package upgrades despite having `package-lock.json` files all over the place, scratching our heads what could possibly be going wrong. This issue breaks any serious CI setup, where we want to build with only controlled package versions and fail otherwise.

Could you please reconsider this and provide a way to run `npm ci` with `--hoist`?

If the developer went to the trouble of discovering the `--ci` parameter and calling `lerna bootstrap --ci`, they damn well expect Lerna to invoke `npm ci`!  To silently ignore the `--ci` parameter without any warning (especially on a CI server) is way more problematic than some developer trundling into a package folder and running `npm install` there.

This doesn't even affect normal `lerna bootstrap` usage which runs `npm install` anyway, so users who don't care about `--ci` won't even notice anything.

**Comment by intafon** [comment] 2020-04-01 00:40
I think I'd actually prefer that bootstrap fail with a message if env CI=true and --hoist is used, or if --hoist and --ci are used simultaneously. There may be some cases I have not considered though, so that is just my two cents. ;-)

**Comment by raijinsetsu** [comment] 2021-03-17 15:48
This was just sprung on us and it is now clear that lerna was never doing what was expected.

If providing the `--ci` flag, the expectation is that `npm ci` will be invoked so that **exactly** what is in the package-lock.json is installed. I do not fully understand why anyone would use `npm install` in a leaf directory and then commit the package-lock.json back to the repository, but let's assume that is something that should not cause lerna to break for existing repositories -- we do something like this so that our distribution can be built using a package-lock.json that contains both hoisted and local dependencies and any audit fixes but that is **not** stored in the package's folder but in another location that lerna is not aware of.

Why not a new configuration option `--allow-ci-flag-when-hoisting` which would cause bootstrap to execute `npm ci` if the `--ci` flag was also provided?

Expectations:

1. passing `--ci` and `--hoist` without `--allow-ci-flag-when-hoisting` should produce a warning indicating that the `--ci` flag will be ignored - I would prefer an error but this thread makes it seem that that would be unacceptable to the maintainers
2. `bootstrap --allow-ci-flag-when-hoisting --ci` would invoke `npm ci` instead of `npm install`
3. the option can be set in the lerna.json config file
3. the next lerna major version should make `--allow-ci-flag-when-hoisting` the default because it seems to make more sense than not invoking `npm ci` when the `--ci` flag is provided

**Comment by raijinsetsu** [comment] 2021-03-17 15:53
Sorry... Two follow-ups to my prior comment:

1. a member of my development team will be submitting a PR for the new flag and behavior soon
2. the lack of this being documented in the CLI or even providing a warning has exposed us to additional development work because tests work in dev builds, which use hoisting and local modules, but not production builds, which install everything from npm using a generated package-lock.json with audit fixes

**Comment by raijinsetsu** [comment] 2021-03-17 16:07
@mzyil thanks! I missed that when looking at the thread though it's not clear what the PR actually changed in regards to this issue. I'll have to review it some more.

**Comment by raijinsetsu** [comment] 2021-03-17 16:12
@mzyil Actually... That PR would appear to be a shell script for another project and not directly related to this thread. They added the "--ci" flag to "lerna boostrap" so as to avoid re-building the package-lock.json.

**Comment by RobertVillalba** [comment] 2022-02-03 21:33
Old issue, but maybe I'll save someone some pain. I've been digging around or a day or so for a solution to this and I might have just figured out how to address the problem. I enabled NPM workspaces by adding 
```
// root/package.json
  "workspaces": [
    "packages/*"
  ],
  
// root/lerna.json
  "useWorkspaces": true,
```
I'm not 100% clear on if Lerna properly works with NPM workspaces, but some preliminary tests (deleting outdated deps within some of my packages and running `lerna bootstrap`) seems to show that the same outdated version gets installed. Now the slightly odd thing is that this works with and without the `--ci` flag for lerna. That said, even if something is working there by coincidence only, you should still be able to have reproducible builds by doing `npm ci` at the root level.

I tried using Yarn workspaces originally but yarn installs even with `--frozen-lockfile` flag was still updating out of date packages. Looking at this issue https://github.com/yarnpkg/yarn/issues/4098 it seems they're not going to fix it for v1 of Yarn.

Assuming this works, I think the moral of the story is that Lerna is not really meant (or great?) for package management (and seems to not be further maintained so likely switching to Nx in the future).

**Comment by JamesHenry** [comment] 2022-11-29 13:43
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏

**Closed by JamesHenry** 2022-11-29 13:43 UTC
Labels: scope: package management
