### ISSUE TITLE
Lerna 7.0.0: `lerna repair` locks up when nx.json doesn't exist

### ISSUE THREAD

**Issue by kerryj89** [lerna/lerna#3724] opened 2023-06-09 23:15 UTC
## Current Behavior

I have been using Lerna before the Nx team took over.  I do not use Nx and consequently don't have an `nx.json` file.
After upgrading Lerna to v7, I ran `lerna repair` as mentioned in the upgrade notes.  Running this command without `nx.json` locks up my terminal.

## Expected Behavior

Not to lock up.  I have never ran the command until now - I was previously on Lerna v6.6.2, I believe.

## Steps to Reproduce

1. Check out https://github.com/lerna/getting-started-example
2. Remove `nx.json`
3. Run `lerna repair`

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "0.0.0",
  "useWorkspaces": true
}
```

</p></details>

</p></details>

### Environment

Downloaded example repo and ran `yarn` prior to `npx lerna info` but was not getting anything of value:

```
> npx lerna info
lerna notice cli v7.0.0
lerna ERR! ENOGIT The git binary was not found, or this is not a git repository.
```

--

- MacBook Pro (Apple M1 Pro - 16-inch, 2021 - 16GB)
- macOS Ventura 13.3.1

**Comment by kerryj89** [comment] 2023-06-09 23:38
To circumvent this issue for now you can create an empty `nx.json` file with empty object `{}`.

This was also preventing me from running `lerna list` in my script.

**Comment by kerryj89** [comment] 2023-06-10 01:44
Noticed my CI was failing with `lerna run --scope @some-project/some-package some-script`. 

Running it locally I ran into the following issue, maybe due to empty/phony `nx.json` (?).

```
lerna notice cli v7.0.0
lerna info versioning independent
lerna notice filter including "@some-project/some-package"
lerna info filter [ '@some-project/some-package' ]

 >  Lerna (powered by Nx)   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
```

Regardless, I'm able to fix it by adding `"useNx": false` to my `lerna.json`.  Apparently it's set to true by default since v6 but it didn't affect my `lerna run` command until now.

However, the original problem of locking up still surfaces if `nx.json` is missing (even with `"useNx": false` in `lerna.json`).

**Comment by JamesHenry** [comment] 2023-06-12 15:26
@kerryj89 regarding `lerna repair` I cannot reproduce the issue.

You mention running `yarn`, but the example repo doesn't use yarn? You also are getting a git error when running the info command. Are you sure you are running it in the repo?

What version of nx is in your `node_modules` (e.g. if you run `npm ls nx`)?

Regarding https://github.com/lerna/lerna/issues/3724#issuecomment-1585417409 I think that will be a duplicate of #3719 so I won't comment further on that one here, but instead focus that on the other thread where a reproduction has been provided

**Comment by JamesHenry** [comment] 2023-06-13 09:03
#3719 has been resolved in lerna `7.0.1` so if we could just please clarify your main issue here per my previous comment that would be great

**Comment by kerryj89** [comment] 2023-06-13 22:41
Thanks - I am still able to reproduce the initial one following my steps and v7.0.1 (haven't tested the second issue which seems like it might be fixed).  I cloned the example repo twice just now and deleted `nx.json` from one of them and ran `lerna repair` in both.  The one without `nx.json` ends up freezing on me with `lerna notice cli v7.0.1`.

`npm ls nx` outputs:
```
root@ /Users/me/dev/test/getting-started-example
└─┬ lerna@7.0.1
  ├─┬ @nx/devkit@16.3.2
  │ └── nx@16.3.2 deduped
  └─┬ nx@16.3.2
    └─┬ @nrwl/tao@16.3.2
      └── nx@16.3.2 deduped
```

Here is `npx lerna info` in my project directory with my empty `nx.json` workaround (otherwise it would freeze like `lerna repair`):
```
 Environment info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Utilities:
    Git: 2.37.3 - /usr/local/bin/git
  npmPackages:
    lerna: 7 => 7.0.
```

**Comment by JamesHenry** [comment] 2023-06-14 08:31
Here are the exact steps I am following based on your report:

```sh
cd ~/Repos/tmp
gh repo clone lerna/getting-started-example
cd getting-started-example
rm nx.json
npm install
npx lerna repair
npm install -D lerna@7
npx lerna repair
```

My two outputs from `lerna repair` are as follows:

**v6**
![image](https://github.com/lerna/lerna/assets/900523/c796a656-c22e-45c4-a61d-47bdb51813bc)

**v7**
![image](https://github.com/lerna/lerna/assets/900523/72c8d0c8-117c-4112-8b0c-8b8fdd2732e0)

**lerna info**
![image](https://github.com/lerna/lerna/assets/900523/f33f7f99-8809-4327-8728-2b7fa3fa6ce4)

Running with `npx lerna repair --loglevel=silly` I get:

![image](https://github.com/lerna/lerna/assets/900523/cc770e1d-070d-4298-9644-e2842a7a26bc)

...as my lerna CLI logs before the success message. Do you see all those same logs?

Please could you try and figure out what is different about those steps I have outlined vs what you are doing? And/or if there is anything unusual about the directory structure? E.g. you haven't nested this repo inside another repo or anything like that right? There isn't another .git or nx.json in the parent folder hierarchy?

**Comment by kerryj89** [comment] 2023-06-14 14:29
Thanks for following up.  There is no strange directory structure that I know of.  No nesting/symlinks.

```
ls -l ~/dev/lerna-test/  
total 0
drwxr-xr-x  10 <me>  staff  320 Jun 14 09:11 getting-started-example
```

```
ls -l ~/dev/lerna-test/getting-started-example 
total 2728
-rw-r--r--    1 <me>  staff      784 Jun 14 09:11 README.md
-rw-r--r--    1 <me>  staff      111 Jun 14 09:11 lerna.json
drwxr-xr-x  988 <me>  staff    31616 Jun 14 09:12 node_modules
-rw-r--r--    1 <me>  staff  1381575 Jun 14 09:12 package-lock.json
-rw-r--r--    1 <me>  staff      130 Jun 14 09:12 package.json
drwxr-xr-x    5 <me>  staff      160 Jun 14 09:11 packages
```

This time my zsh killed the process after a minute.  I also tried deleting everything in my `.zshrc`, opening a new terminal and running again but it still locks up at this point.  This is on my work computer and we use SentinelOne... I am not sure if it could affect it but I thought I'd mention it.  It hasn't stopped me from running scripts and such, but who knows.  I will also try again after upgrading my OS to the latest.  I've already tried rebooting earlier but it gets stuck at this point.

![screenshot-2023-06-14-bbXYHAc7@2x](https://github.com/lerna/lerna/assets/1977804/1edda6d2-d25a-466d-b7d7-11b2c77fd72e)

**Comment by JamesHenry** [comment] 2023-06-14 14:36
Could you please try running the failing command again but with `NX_DAEMON=false` set?

i.e. 

```sh
NX_DAEMON=false npx lerna repair
```

On v7

I imagine your work's SentinelOne (which I am not familiar with) is blocking the daemon

**Comment by kerryj89** [comment] 2023-06-14 14:44
Unfortunately it still locks up on me.  Anyway, I'm starting to think this is a strange isolated issue with my setup somewhere since no one else seems to be running into it.  You can close this out if you're thinking the same and I guess if someone else runs into this same issue they can comment here with more details, but for now an empty `nx.json` allows it to chug along.  Thanks for taking a look!

```
NX_DAEMON=false npx lerna repair
lerna notice cli v7.0.1
```

**Comment by JamesHenry** [comment] 2023-06-14 14:47
Ok very strange, but thanks for confirming.

If anyone else runs into the issue please feel free to comment and we can reopen this if there is a reproduction of the problem

**Closed by JamesHenry** 2023-06-14 14:47 UTC
Labels: type: bug, blocked: more info needed
