### ISSUE TITLE
npm install fails, looking for @lerna/global-options@^3.1.3

### ISSUE THREAD

**Issue by tomwolber** [lerna/lerna#1594] opened 2018-08-21 18:28 UTC
## Expected Behavior
npm should install lerna correctly

## Current Behavior
npm install fails

```
npm install --global lerna
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lerna/global-options@^3.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@lerna/cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tommy/.npm/_logs/2018-08-21T18_20_56_845Z-debug.log

```

## Steps to Reproduce (for bugs)

1. `npm install --global lerna`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | N/A |
| `npm --version`  | 5.6.0 |
| `yarn --version` | N/A |
| `node --version` | v8.9.4 |

| OS | Version |
| ---: | :--- |
| macOS High Sierra | 10.13.6 |

**Comment by tyler-johnson** [comment] 2018-08-21 18:32
I keep hitting this on different dependencies. If I had to guess, this is on NPM's side.

**Comment by evocateur** [comment] 2018-08-21 18:37
Yeah, this is a dupe of #1593. I haven't been able to reproduce locally (with a fresh cache and `--prefer-online`), so I agree it's an npm issue.

**Closed by evocateur** 2018-08-21 18:37 UTC
