### ISSUE TITLE
lernajs.io is returning NXDOMAIN

### ISSUE THREAD

**Issue by jshou** [lerna/lerna#2042] opened 2019-04-16 22:23 UTC
Hi! It looks like DNS settings for `lernajs.io` aren't configured correctly and I'm not able to visit the homepage.

## Expected Behavior
Visit lernajs.io should bring up the website

## Current Behavior
DNS request returns `NXDOMAIN`

## Steps to Reproduce (for bugs)

1. Visit lernajs.io in any browser

**Comment by evocateur** [comment] 2019-04-17 01:12
Duplicate of #2033, I'm in the process of trying to get a js.org subdomain: https://github.com/js-org/js.org/pull/2967

**Closed by evocateur** 2019-04-17 01:12 UTC

**Comment by jshou** [comment] 2019-04-17 16:02
ack, apologies for the dupe; i tried to search for an issue  but i guess i didn't look far back enough!
