### ISSUE TITLE
lerna publish fails when prettier 3.0 is installed in the project

### ISSUE THREAD

**Issue by fabb** [lerna/lerna#3775] opened 2023-07-14 07:43 UTC
## Current Behavior

lerna publish fails when prettier 3.0 is installed in the local project.

## Expected Behavior

lerna should be able to publish independently of the prettier dependency version installed in the project. Since lerna uses the workspace version of prettier, it should update to be compatible with both prettier 3 and 2, and maybe even gracefully catch an error that happens when trying to execute that prettier version.

## Steps to Reproduce

```
lerna publish --conventional-commits --yes --no-verify-access --contents lib --no-commit-hooks
...
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-conventionalcommits"
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:7464:49)
lerna ERR!     at gitAdd (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:7487:5)
lerna ERR!     at VersionCommand.updatePackageVersions (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:8318:17)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:7464:49)
lerna ERR!     at gitAdd (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:7487:5)
lerna ERR!     at VersionCommand.updatePackageVersions (/builds/willhaben/chapter/frontend/wh-components/node_modules/lerna/dist/index.js:8318:17)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna resolvedPrettier.resolveConfig.sync is not a function
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
    "packages": ["packages/*"],
    "version": "independent",
    "changelogPreset": {
        "name": "conventionalcommits",
        "commitUrlFormat": "https://my.site/path/{{hash}}",
        "compareUrlFormat": "https://my.site/path/compare/{{previousTag}}...{{currentTag}}",
        "issueUrlFormat": "https://my.site/ISSUE-{{id}}",
        "issuePrefixes": ["ISSUE-"]
    }
}
```

</p></details>

### Environment

We build this in the `node:18.14.1` docker image.

**Comment by JamesHenry** [comment] 2023-07-14 08:09
This is a duplicate of https://github.com/lerna/lerna/issues/3765 and was already fixed in 7.1.3

**Closed by JamesHenry** 2023-07-14 08:09 UTC
Labels: type: bug
