### ISSUE TITLE
How to show log messages coming from scripts in packages?

### ISSUE THREAD

**Issue by noherczeg** [lerna/lerna#488] opened 2017-01-07 14:30 UTC
Hey guys!

First of all, thanks for Lerna! I found it really nice, works like a charm :)

So my question is the same as the subject. I red the docs, but couldn't find anything on the topic where I can toggle logs coming from packages when I run `lerna run whatever`. Is there a way to achieve this?

- node version: `6.9.2`
- npm version: `3.10.9`
- lerna version: `2.0.0-beta.31`

Thanks in advance!

**Comment by arekkas** [comment] 2017-01-17 15:27
Same question here, @noherczeg are you by any chance running on windows?

**Comment by noherczeg** [comment] 2017-01-17 20:07
@arekkas Nope, Fedora 25.

**Comment by arekkas** [comment] 2017-01-17 20:24
this is a dupe of #446

**Comment by noherczeg** [comment] 2017-01-31 14:12
@arekkas It is, so I closed this one.

**Closed** 2017-01-31 14:12 UTC
