### ISSUE TITLE
[Bug] Import failing (2.0.0-beta.38)

### ISSUE THREAD

**Issue by jmcpeak** [lerna/lerna#730] opened 2017-04-05 19:34 UTC
Trying to use lerna import. I saw in a few other issues that a rebase should be tried if import failed. I tried that first - no luck.

Here is the error message

`lerna import /Users/mcpeakj/projects/document-ui`
`Lerna v2.0.0-beta.38`
`About to import 248 commits from /Users/mcpeakj/projects/document-ui into packages/document-ui`
`? Are you sure you want to import these commits onto the current branch? Yes`
`Errored while running ImportCommand.execute`
`Failed to apply commit 5745ce9.`
`Error: Command failed: git am -3`
`error: Failed to merge in the changes.`

`Rolling back to previous HEAD (commit 0515496).`

This repo is hosted by JFrog/Artifactory, at my work - it is not a github repo.
I tried importing one of my public github repos and that worked fine.

[lerna-debug.log.zip](https://github.com/lerna/lerna/files/900592/lerna-debug.log.zip)

**Comment by Robinfr** [comment] 2017-04-13 08:12
I ran into the same problem when I tried to import a Git repository from a local path..

**Comment by jmcpeak** [comment] 2017-04-16 23:01
So if the -B flag is added (https://git-scm.com/docs/git-format-patch#git-format-patch) a lot more information is outputted.

**Comment by am80l** [comment] 2017-05-31 22:33
+1 same issue

**Comment by evocateur** [comment] 2017-05-31 22:41
@am80l Please don't add "+1" comments. If you have a reproducible example or other context, that would be very helpful.

**Comment by kanzelm3** [comment] 2017-06-07 18:39
+1

**Comment by dmaksimovic** [comment] 2017-09-20 20:49
I added a pull request https://github.com/lerna/lerna/pull/1019 that fixes this issue.

**Comment by dmaksimovic** [comment] 2017-10-02 07:25
I think this issue can be closed as fixed since pull request #1019 was merged

**Closed** 2017-10-02 15:02 UTC
Labels: bug, help wanted
