### ISSUE TITLE
Lerna returns success even if a package fails

### ISSUE THREAD

**Issue by AmirL** [lerna/lerna#3795] opened 2023-07-27 12:14 UTC
## Current Behavior

```bash
npm run lint

> lint
> lerna run lint --stream --bail

lerna notice cli v7.1.4

 >  Lerna (powered by Nx)   Running target lint for 2 projects:

    - back
    - front

 —————————————————————————————————————————————————————————————————————————————————————————————————————————

> back:lint


> front:lint

front: > front@1.0.1 lint
front: > next lint
back: > back@0.0.1 lint
back: > eslint "{src,apps,libs,test}/**/*.ts"
front: ✔ No ESLint warnings or errors
back: 
back: ✖ 5 problems (1 error, 4 warnings)
back:   0 errors and 1 warning potentially fixable with the `--fix` option.
back: 
back: npm ERR! Lifecycle script `lint` failed with error: 
back: npm ERR! Error: command failed 
back: npm ERR!   in workspace: back@0.0.1 
 —————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target lint for 2 projects
```

## Expected Behavior

I expect lerna returns exit code 1, and shows some error, instead of writing "Successfully ran target lint for 2 projects".

### Failure Logs / Configuration

<details><summary>package.json</summary><p>

```json
{
  "private": true,
  "scripts": {
    "lint": "lerna run lint --stream --bail",
  },
  "devDependencies": {
    "eslint": "^7.32.0",
    "lerna": "^7.0.0",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.11"
  },
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
}
```

</p></details>

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "0.0.0"
}
```

</p></details>

### Environment

lerna notice cli v7.1.4

 Environment info:

  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Utilities:
    Git: 2.37.3 - /usr/local/bin/git

**Comment by yukinami** [comment] 2024-01-09 12:31
Got the same issue here, and still exists after upgraing to `8.0.2`.  Also works fine with Node 18.19.

**Comment by bbeesley** [comment] 2024-03-08 11:58
Same issue here

**Comment by JamesHenry** [comment] 2024-03-22 16:08
@bbeesley If you have steps to reproduce a problem please provide them in a fresh issue with full context and I'll take a look.

In the meantime I am going to close this one as I cannot reproduce any issues, so maybe the bug in node has been fixed in a later version of Node 20.

I am running node `20.9.0`.

My steps:

```sh
mkdir lerna-issue-3795
cd lerna-issue-3795
npx lerna init
npx lerna create -y a
npx lerna create -y a
```

...then patch the `"test"` script in package `a` to be `"exit 1"` and run:

```sh
npx lerna run test --bail --stream
```

...it behaves as expected:

<img width="765" alt="image" src="https://github.com/lerna/lerna/assets/900523/968de2d8-3735-438a-8783-5a8ce85b1438">

**Closed by JamesHenry** 2024-03-22 16:08 UTC
Labels: type: bug
