### ISSUE TITLE
Proposal: integration of git subtree

### ISSUE THREAD

**Issue by bitliner** [lerna/lerna#414] opened 2016-11-23 09:40 UTC
Quite often there might be the need that each package of a monorepo has its own git repository.

Imagine the following scenario:
* the monorepo is made for a backend architecture: it includes, in /packages folder, different projects and each project is a different software process
* in order to deploy a single project to production/stage, quite often `git hooks` are used, or, generally speaking, there is the need to hit a webhook related to that project so the releasing process for that project can start

With the current version of lerna, all of this have to be managed by the developer, manually.

What about if lerna integrates some wrapper of git commands like git `push`, `pull` and `clone` that execute the related git command for the monorepo but also for the git repository in /packages folder?

Using subtree, it would make easier to download projects and manage more smoothly the related git repositories with subtree (I prefer git subtree because much easier and simpler than git submodules).

Something like:
`lerna git clone` or `lerna git add`
`lerna git push`
`lerna git pull`

They run the related git commands:
* for each git repository in /packages folder
* for the monorepo itself

**Comment by thejameskyle** [comment] 2016-11-27 11:53
Duplicate of #161

**Closed by thejameskyle** 2016-11-27 11:53 UTC
