### ISSUE TITLE
pre-release is not a dist-tag on <lib>

### ISSUE THREAD

**Issue by dthree** [lerna/lerna#37] opened 2016-02-05 03:04 UTC
When publishing with lerna, the packages do publish, but NPM takes a dump on me by saying:

> prerelease is not a dist-tag on [library]

I'm sure there's just some setting I need to do on my repo to fix this, however your docs should probably mention something on it.

---

Otherwise, great lib! It's saving my life [on this project](https://npmjs.com/package/cash).

**Comment by jasonmit** [comment] 2016-02-08 01:28
Ran into this as well.  My fix was to tag every package with prerelease but agree that either the docs should mention thing or Handle the error case.

**Comment by dthree** [comment] 2016-02-08 20:28
@jasonmit thanks - could you please explain exactly what you did to tag them properly? Can't get over this hump...

**Comment by dthree** [comment] 2016-02-09 00:58
Yeah, I have no idea what I'm doing on tags, but honestly they're terribly documented in general. I tried going into each of my packages and doing:

`npm dist-tag add mypkg@v0.0.7 prerelease`

However this didn't change anything on this error...

**Comment by hzoo** [comment] 2016-02-09 01:04
I think we need more info to debug this one? Not sure where the error is happening

What were doing is `npm publish --tag prerelease` for each pacakge,
`npm dist-tag rm " + name + " prerelease`, - if the error happens here, then it maybe it failed publishing?
and then `npm dist-tag add " + name + "@" + NEW_VERSION + " stable`

**Comment by thejameskyle** [comment] 2016-02-11 21:40
The only thing I can think of is if the initial tagging is failing for some reason.

**Comment by dthree** [comment] 2016-02-11 23:14
Yeah, it looks like it. But it's totally silent.

**Comment by thejameskyle** [comment] 2016-02-12 00:20
@dthree We might just have to close this one as cannot reproduce, but I'm going to add better logging for lerna (#49)

**Comment by dthree** [comment] 2016-02-12 00:30
okay... question - what If I let you clone the git repo It's happening on?

**Comment by thejameskyle** [comment] 2016-02-12 00:36
If you can give me a reproduction case I can try to diagnose this. However you want to do that is fine, I have a private npm server so I can test out publishing to it

**Comment by dthree** [comment] 2016-02-12 00:42
Okay, that would be really amazing!

[I temporary threw up the project here on Github (haven't released it yet, so keeping it off Github generally for now).](https://github.com/vorpaljs/cash)

You can just git clone this, and:

1. Update `./packages/template.package.json` to match your private NPM repos.
2. Run `gulp` to replicate those `package.json` files to each sub package.
3. Go nuts with `lerna` - it should be reproducible right there.

Thanks a million!

**Comment by greenish** [comment] 2016-04-03 16:06
Okay, I ran into the same problem and I think I can reproduce it:

The error happens when the folder name in `packages/` doesn't match the package name in `package.json`

So a package in folder `packages/core/` with `{ "name" : "library-core" }` in `package.json` will produce the error.

**Comment by dthree** [comment] 2016-04-03 16:55
Oh snap - yeah, that's what it is. 

https://github.com/dthree/cash/tree/master/packages

**Comment by cpsubrian** [comment] 2016-04-04 03:34
Ran into this also. I'm trying to manage a collection of namespaced modules so I can't name the folder the same as the package because of `@org` in the package name. AKA `@org/my-module` is the npm package name but the folder is `my-module`.

**Comment by cpsubrian** [comment] 2016-04-04 19:50
My package successfully published with `master`, so .. for me this issue is already resolved.

**Comment by hzoo** [comment] 2016-06-13 04:37
Alright cool closing for now

**Closed by hzoo** 2016-06-13 04:37 UTC
Labels: question

**Comment by dtothefp** [comment] 2016-10-05 17:28
@cpsubrian I'm running into the same problem of an `@org` name and getting the error

```
Errored while running PublishCommand.execute
Error: Command failed: npm dist-tag add @org/<package_name>@0.2.2-alpha.8d13b88f canary
npm ERR! registry error parsing json
```

Not sure if this is the same issue and/or how to resolve? I'm on `lerna 2.0.0-beta.30`

**Comment by doug-wade** [comment] 2016-11-17 05:35
I got this today with `lerna 2.0.0-beta.30` -- I just got this error over and over in the console:

```
npm ERR! prerelease is not a dist-tag on clefs
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dwade/foss/clefs/npm-debug.log

    at checkExecSyncError (child_process.js:488:13)
    at Object.execSync (child_process.js:528:13)
    at execSync (/Users/dwade/.config/yarn/global/node_modules/lerna/lib/commands/publish.js:74:18)
    at /Users/dwade/.config/yarn/global/node_modules/lerna/lib/commands/publish.js:184:13
    at /Users/dwade/.config/yarn/global/node_modules/async/lib/async.js:718:13
    at replenish (/Users/dwade/.config/yarn/global/node_modules/async/lib/async.js:319:21)
    at /Users/dwade/.config/yarn/global/node_modules/async/lib/async.js:330:15
    at _parallel (/Users/dwade/.config/yarn/global/node_modules/async/lib/async.js:717:9)
    at Object.async.parallelLimit (/Users/dwade/.config/yarn/global/node_modules/async/lib/async.js:735:9)
    at ship (/Users/dwade/.config/yarn/global/node_modules/lerna/lib/commands/publish.js:180:11)
```

I don't have have a `prerelease` tag of any kind:

```
i-200077 foss/clefs ‹master› » git tag                                                                                                                                         130 ↵
v0.0.1
v0.0.2
```

The affected repo is [clefs](https://github.com/doug-wade/clefs)

**Comment by thejameskyle** [comment] 2016-11-17 19:07
Did you get a lerna-debug.log file?
