### ISSUE TITLE
Bootstrapping doesn't work with certain consumption methods

### ISSUE THREAD

**Issue by lukebatchelor** [lerna/lerna#183] opened 2016-06-07 05:12 UTC
Hi,

We have a small issue with the way Lerna bootstrap links packages when it has the correct local version. Because it creates a `package.json` and a `index.js` that just imports and exports the main of the package you are pointing at, you lose the other artefacts that might have otherwise been consumable from the published package.

For example, if your package exposes `dist`, `lib` and `fonts` directories, a consumer would normally be able to use these directories, but once they are bootstrapped, they no longer can.

Is there a reason you link the way you do and not using symlinks? I see a couple of issues where you've mentioned it, so it sounds like it's something you've looked at before?

We are currently working around it by adding a script that looks for lerna linked packages and replaces them with `npm link`'d versions.

Cheers

**Comment by gigabo** [comment] 2016-06-07 21:44
Hi @lukebatchelor, thanks for reporting.  I think this is a duplicate of #11.  There's some discussion there.

**Comment by thejameskyle** [comment] 2016-06-07 22:01
Yeah, duplicate of #11. There were some issues, needs more investigating.

**Closed by thejameskyle** 2016-06-07 22:01 UTC

**Comment by lukebatchelor** [comment] 2016-06-08 02:48
Ah, apologies. I looked around and didnt see any issue titles that looked like this.

I was talking to some people who've had similar issues with symlinks and npm install. I'm wondering if you had the same problems as them, caused by linking first, then `npm install`ing. We are doing the linking after the install. 

I'll do some investigation and get back to you if I find a better way. Thanks!
