### ISSUE TITLE
Nested directory support

### ISSUE THREAD

**Issue by patrickheeney** [lerna/lerna#284] opened 2016-07-21 18:00 UTC
Original issue #11 was closed due to the conversation being off topic. Opening this issue again since it was decided the feature request was within scope of the project.

To avoid being locked, it would be nice to know why the original was closed as "off topic". The topic was to discover how to support nested directories. The conversation was discussing `pnpm` use case with `lerna` to accomplish just this. Other discussions were around patching `require`, also on topic. My inability to use `lerna` is the direct result of not having this feature, so hopefully that is also not considered "off topic".

**Comment by thejameskyle** [comment] 2016-07-21 18:20
Duplicate of #11

**Closed by thejameskyle** 2016-07-21 18:20 UTC
Labels: duplicate
