### ISSUE TITLE
Lerna (powered by Nx)   Running target "compile:ts" failed

### ISSUE THREAD

**Issue by DreamPWJ** [lerna/lerna#3223] opened 2022-07-06 01:04 UTC
08:57:23   >  Lerna (powered by Nx)   Running target "compile:ts" failed
08:57:23  
08:57:23     Tasks not run because their dependencies failed or --nx-bail=true:
08:57:23     
08:57:23     - athena-utils:compile:ts
08:57:23     - athena-common-mobile:compile:ts
08:57:23     - athena-common-web:compile:ts
08:57:23     
08:57:23     Failed tasks:
08:57:23     
08:57:23     - athena-components:compile:ts

08:57:21  src/Uploader/FileUploader.tsx(5,26): error TS2307: Cannot find module 'athena-constants' or its corresponding type declarations.
08:57:21  src/RichText/index.tsx(8,30): error TS2307: Cannot find module 'athena-utils' or its corresponding type declarations.
08:57:21  src/RichText/index.tsx(9,26): error TS2307: Cannot find module 'athena-constants' or its corresponding type declarations.
08:57:21  error Command failed with exit code 1.
08:57:21  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JamesHenry** [comment] 2022-07-06 07:01
Thanks @DreamPWJ I think this might be a duplicate of #3215

**Closed by JamesHenry** 2022-07-06 07:01 UTC
Labels: type: bug
