### ISSUE TITLE
lerna / nx yarn watch not run on every packages

### ISSUE THREAD

**Issue by vincent-capicotto-payfit** [lerna/lerna#3261] opened 2022-07-24 08:23 UTC
## Current Behavior

I try to run a `yarn --watch` on every packages with `--parallel`, but only 3 packages of my 43 are actually watched, I use nx with `useNx: true`. This issue seems to be the same as #3198 but it is not working in my case.
I use lerna `5.2.0` and nx `14.4.3`
It's working well if I deactivate nx: `useNx: false`

## Expected Behavior

The watch command should be executed on every package

## Steps to Reproduce

create `watch` command in every package, and run with `lerna --parallel ....`

### Environment

```
Environment info:

  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  npmPackages:
    lerna: 5.2.0 => 5.2.0 
```

**Comment by JamesHenry** [comment] 2022-07-24 09:51
Hi @vincent-capicotto-payfit, I was not able to reproduce this. 

I used https://github.com/lerna/repro and created 4 packages, each with a long-running "serve" command. When running with `--parallel` all four were executed, not just three:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/900523/180641689-94fd47ad-ec1a-4859-bd51-706f947b18b5.png">

Please kindly head over to https://github.com/lerna/repro and create a minimal reproduction so we can look into it further.

Many thanks 🙏

**Comment by vincent-capicotto-payfit** [comment] 2022-07-25 10:29
Hey, thank you for the answer.
So I tried to reproduce with a dummy project; I cannot.
In our project I saw that we have a lot of circular dependencies, do you think that could be the cause?

**Comment by ghiscoding** [comment] 2022-07-26 13:52
might be (probably) related to #3233 and a possible fix in PR #3234

**Comment by rileylnapier** [comment] 2022-08-03 18:00
i have this same issue.  i have 10 packages.  when i run my command to babel watch them all... i get it running on 4 out of 10 packages :(

**Comment by JamesHenry** [comment] 2022-08-04 12:30
Thank you @rileylnapier! I will take a look at your repo and report back

**Comment by JamesHenry** [comment] 2022-08-08 14:09
That was really helpful to have an open-source example, thank you @rileylnapier!

I've merged one part of a relevant fix already and #3283 is the final piece. I will cut a patch of lerna once it's merged

**Closed** 2022-08-08 14:47 UTC
Labels: type: bug

**Comment by JamesHenry** [comment] 2022-08-08 14:55
@vincent-capicotto-payfit @rileylnapier please try again with lerna `5.4.0` which I just released

**Comment by vincent-capicotto-payfit** [comment] 2022-08-08 15:03
> @vincent-capicotto-payfit @rileylnapier please try again with lerna `5.4.0` which I just released

Thx I will try to find some time to test it

**Comment by rileylnapier** [comment] 2022-08-08 23:07
thank you for the fix!!!  worked great :)
