### ISSUE TITLE
As of 6.5.0, lerna commands no longer work on `nx` projects without running `npm install` first

### ISSUE THREAD

**Issue by simon-abbott** [lerna/lerna#3566] opened 2023-03-02 17:56 UTC
## Current Behavior

If you have an `nx` project with an `extends` specified but without the `node_modules` installed, running any lerna command (`info`, `bootstrap`, `-h`, etc.) will throw the error `Error: Cannot find module <path/to/nx/extends>`.

This is a problem because Renovate runs `lerna bootstrap` in order to update the lock files, and for efficiency it doesn't run `npm install` first.

## Expected Behavior

Prior to version 6.5.0, running lerna would work, even if the dependencies had not been installed.

## Steps to Reproduce

1. Create a new `nx`-enabled project
2. Specify an `extends` in the `nx.json` (for example: `"extends": "@nrwl/workspace/presets/npm.json"`)
3. Delete the `node_modules` folder, if it exists
4. Run any lerna command

### Failure Logs / Configuration

`Error: Cannot find module '@nrwl/workspace/presets/npm.json'`

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "packages": ["packages/*"],
  "command": {
    "publish": {
      "ignoreChanges": ["**/__tests__/**", "**/*.md"],
      "registry": "https://npm.pkg.github.com"
    },
    "version": {
      "message": "chore(release): publish %s"
    }
  },
  "version": "independent"
}
```

</p></details>

### Environment

I cannot get an accurate report since I am unable to run any commands (including `info`) without installing first, and if I install to get `info` working then it will no longer be a report of the environment that is causing the problem.

**Comment by JamesHenry** [comment] 2023-03-10 12:51
Hi @simon-abbott, this makes sense and I would recommend removing the extends. If you follow it through to your node_modules you will notice in latest Nx the JSON file you are extending from only contains:

```sh
{
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    }
  }
}
```

You can easily reproduce this in your own nx.json, and IMO it is better to be clear and explicit in your own config and have all your targetDefaults defined there.

I cannot reproduce a generic issue with running issue with `npx` (without installing first) so going to close this one

**Closed by JamesHenry** 2023-03-10 12:51 UTC
Labels: type: bug

**Comment by simon-abbott** [comment] 2023-03-10 20:44
Removing the `extends` fixed the issue, as expected! I didn't realize that's all that was in the `npm.json` config, or I would have removed it a while ago. We've had that relation defined ourselves for ages.
