### ISSUE TITLE
lerna init does not produce a packages directory on 2.0.0-rc.5

### ISSUE THREAD

**Issue by talkingtab** [lerna/lerna#837] opened 2017-05-23 17:59 UTC
On a digital ocean instance of ubuntu 16.04,
clean install of lerna

> git init sooth
Initialized empty Git repository in /other/clones/sooth/.git/
> cd sooth
> lerna init
lerna info version 2.0.0-rc.5
lerna info Creating package.json
lerna info Creating lerna.json
lerna success Initialized Lerna files
> sooth (master)$ ls
lerna.json  package.json

**Comment by Krizzu** [comment] 2017-06-01 14:42
OS Sierra 10.12.4
Same issue, even with running `sudo`

**Comment by fsahmad** [comment] 2017-06-03 21:33
Same issue on windows 7

**Comment by evocateur** [comment] 2017-06-06 17:55
Closing as a dupe of #704

**Closed by evocateur** 2017-06-06 17:55 UTC
