### ISSUE TITLE
Bootstrap reformats package-lock.json to use tabs instead of spaces

### ISSUE THREAD

**Issue by omonk** [lerna/lerna#2845] opened 2021-03-11 08:26 UTC
## Expected Behavior
running`lerna bootstrap` installs packages and builds, if required it updates package-lock entries, it does not reformat package-lock to use a different spacing method.

## Current Behavior
running`lerna bootstrap` installs packages and builds and changes some of our packages to use tabs instead of spaces thus leading to +10k LOC.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.5.0",
  "command": {
    "publish": {
      "registry": "https://npm.pkg.github.com",
      "npmClientArgs": [
        "--loglevel",
        "silly"
      ]
    },
    "bootstrap": {
      "npmClientArgs": [
        "--legacy-peer-deps"
      ]
    }
  }
}

```
</p></details>

## Context

I've been looking around these specific packages but there is nothing to suggest we have any config that would cause npm to reformat it this way. Running `npm i` in the package dir reformats it back to using spaces so it suggests that it is something happening within lerna that causes the reformat.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | 7.5.3 |
| `yarn --version` | VERSION |
| `node --version` | 15.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.15.7 |

**Comment by alexmcmanus** [comment] 2021-03-15 11:01
This has caused issues for me trying to publish from a CI server, as it leaves the Git working directory dirty after `lerna boostrap`. I'm using Lerna 4.0.0 and NPM 7.6.0.

**Comment by inca** [comment] 2021-03-25 13:57
Struggled with the same just now, found out that lerna@4.0.0 works fine with npm@6 (was using npm@6.4.11 to be exact) — but not with npm@7.

Reverting to npm 6 solved it for me for the time being, so just in case someone is stuck:

```
npm i -g npm@6
```

**Comment by hudochenkov** [comment] 2021-04-26 10:40
npm [uses](https://github.com/npm/cli/issues/1662#issuecomment-700934724) the same indentation for `package-lock.json` as in `package.json`. During `lerna bootstrap` temporary created `package.json` have tabs as indentation for some reason on npm 7. That's the reason why `package-lock.json` has tabs. However, it's not clear why temporary `package.json` has tabs, while original `package.json` has spaces.

**Comment by ad-si** [comment] 2021-05-27 20:32
Ugh, this is really annoying 🙈. Has anyone already an idea how this should be fixed?

**Comment by tovbinm** [comment] 2021-06-07 22:33
Same here. Please fix.

**Comment by pachuka** [comment] 2021-06-28 20:28
If you are using prettier you can use the following config for now:

`prettier.config.js`
```jsx
module.exports = {
  trailingComma: 'none',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  printWidth: 120,
  arrowParens: 'always',
  overrides: [
    // TODO: this is temporary due to lerna/npm v7 issue
    // https://github.com/lerna/lerna/issues/2845
    {
      files: 'packages/**/package-lock.json',
      options: {
        tabWidth: 4,
        useTabs: true
      }
    }
  ]
};
```

**Comment by richardkazuomiller** [comment] 2021-07-13 16:05
It looks like lerna rewrites `package.json` with tabs temporarily. npm will use the same indentations as `package.json`, which is why it changes, I think. If lerna can do what npm does and detect the indentation type and use the same one when creating the temporary `package.json`, it would fix this.

**Comment by richardkazuomiller** [comment] 2021-07-13 16:18
Did some digging. `write-pkg` will keep the same indentations, so if instead of moving the `package.json` file to the backup file, **copying** it and overwriting the original will keep the same indentations and probably fix the problem https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/utils/npm-install/npm-install.js#L66

**Comment by richardkazuomiller** [comment] 2021-07-28 10:07
Submitted a PR for this https://github.com/lerna/lerna/pull/2955

**Comment by giovannipds** [comment] 2022-02-22 20:43
Not merged yet... damn...

**Comment by marr** [comment] 2022-06-17 14:33
Any updates on this ticket?

**Comment by JamesHenry** [comment] 2022-06-17 16:18
Hi Folks 👋 

I had a look at this just now and I am unfortunately struggling to reproduce the issue with the latest lerna and LTS version of Node, NPM 8.

```
❯ npx lerna info
lerna notice cli v5.1.4

 Environment info:

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.10.0 - ~/.volta/tools/image/npm/8.10.0/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  npmPackages:
    lerna: ^5.1.4 => 5.1.4 
```

I'm sure I must be missing something so please can somebody help out by heading over to https://github.com/lerna/repro and creating a minimal reproduction?

As soon as I can confirm the issue we can look to merge PR #2955.

Many thanks! 🙏

**Comment by pachuka** [comment] 2022-06-17 16:27
@JamesHenry - awesome! I can make some time this weekend to see if  I can create a reproduction. I know it was an issue for myself with NPM 7.x and Lerna 4, but haven't tried against NPM 8.x yet.

**Comment by JamesHenry** [comment] 2022-06-17 17:53
@pachuka Thank you, I'm please to say another community member was able to provide a reproduction already. This will be fixed in the next release of lerna!

**Closed** 2022-06-17 17:52 UTC
Labels: scope: package management

**Comment by tovbinm** [comment] 2022-06-17 19:14
Awesome!!!

**Comment by pachuka** [comment] 2022-06-18 03:44
Awesome! Great news :)
