### ISSUE TITLE
Lerna publish publishes all packages, regardless to whether they changed or not

### ISSUE THREAD

**Issue by osher** [lerna/lerna#1117] opened 2017-11-15 13:55 UTC
Lerna publish publishes all packages, regardless to whether they changed or not
I'm not sure if that's the right behavior, so I report it anyway.

## Expected Behavior
I expect only packages that contain changes to be published

## Current Behavior
Every package is updated, wither it changed or not.

## Possible Solution
I don't know how it works, so I can't help here...

## Steps to Reproduce (for bugs)

I'm trying to eval lerna.
I `lerna init --independent` straight from the manual, everything is out of the box.
**UPDATED** - I did rename `packages` to `ws` in some point in both fs and `lerna.json`, it does not seem to be related.

My project looks as following:
```
D:.
│   lerna.json
│   package.json
│
└───packages
    ├───logger
    │       index.js
    │       package.json
    │
    ├───orm
    │       index.js
    │       package.json
    │
    ├───web-one
    │       index.js
    │       package.json
    │
    └───web-two
            index.js
            package.json
```

I'm working with local npm registries powered by verdaccio.
I'm not sure if it's related - I ran two of them, because I wanted to see how it handles scoped packages.

I work with the local git repository I got from `lerna init`, I did not set a remote.
when I the repo in git-graken I can see the labels created by every publish.
(Do note the first funny label `vnull` ..lol)
![image](https://user-images.githubusercontent.com/803101/32839303-aa211108-ca1c-11e7-8e6c-f0f6cf90fbd3.png)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "commands": {
    "publish": {
      "ignore": [
        "*.md"
      ]
    },
    "bootstrap": {
      "ignore": "component-*"
    }
  },
  "packages": [
    "ws/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>
not sure it's related to the last publish, I did some one after the other without modifying files, or with modifying files in only one package

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   registry: 'http://localhost:8888' }
2 verbose rootPath D:\ws\evals\lerna-eval-indi
3 info version 2.5.1
4 info versioning independent
5 silly isInitialized
6 silly isInitialized true
7 silly existsSync D:\ws\evals\lerna-eval-indi\VERSION
8 info ignore [ 'ignored-file', '*.md' ]
9 silly initialize attempt
10 silly isDetachedHead
11 silly getCurrentBranch
12 verbose getCurrentBranch master
13 verbose isDetachedHead false
14 silly getCurrentBranch
15 verbose getCurrentBranch master
16 silly getUpdates
17 info Checking for updated packages...
18 silly hasTags
19 verbose hasTags true
20 silly getLastTag
21 verbose getLastTag @adtechium/orm@1.0.7
22 info Comparing with @adtechium/orm@1.0.7.
23 silly diffSinceIn @adtechium/orm@1.0.7 ws/logger
24 silly diff ws/logger/npm-debug.log
25 silly diffSinceIn @adtechium/orm@1.0.7 ws/orm
26 silly diff
27 silly diffSinceIn @adtechium/orm@1.0.7 ws/web-one
28 silly diff
29 silly diffSinceIn @adtechium/orm@1.0.7 ws/web-two
30 silly diff
31 verbose updated logger
32 info Checking for prereleased packages...
33 silly collectDependents
34 silly isPackageDependentOf logger logger
35 silly isPackageDependentOf @adtechium/orm logger
36 verbose dependent @adtechium/orm depends on logger
37 silly isPackageDependentOf web-one logger
38 verbose dependent web-one depends on logger
39 silly isPackageDependentOf web-two logger
40 verbose dependent web-two depends on logger
41 silly collectUpdates
42 verbose has filtered update logger
43 verbose has filtered update @adtechium/orm
44 verbose has filtered update web-one
45 verbose has filtered update web-two
46 silly initialize success
47 silly execute attempt
48 silly runScriptSync preversion logger
49 silly runScriptSync version logger
50 silly runScriptSync preversion @adtechium/orm
51 silly runScriptSync version @adtechium/orm
52 silly runScriptSync preversion web-one
53 silly runScriptSync version web-one
54 silly runScriptSync preversion web-two
55 silly runScriptSync version web-two
56 silly addFile D:\ws\evals\lerna-eval-indi\ws\logger\package.json
57 silly addFile D:\ws\evals\lerna-eval-indi\ws\orm\package.json
58 silly addFile D:\ws\evals\lerna-eval-indi\ws\web-one\package.json
59 silly addFile D:\ws\evals\lerna-eval-indi\ws\web-two\package.json
60 silly commit Publish
60 silly commit
60 silly commit  - logger@0.0.8
60 silly commit  - @adtechium/orm@1.0.8
60 silly commit  - web-one@0.0.10
60 silly commit  - web-two@0.0.10
61 verbose commit [ 'commit',
61 verbose commit   '--no-gpg-sign',
61 verbose commit   '-F',
61 verbose commit   'C:\\Users\\osher\\AppData\\Local\\Temp\\520231ca-7078-44dd-a676-8eb0c267e179\\lerna-commit.txt' ]
62 silly addTag logger@0.0.8
63 error execute caught error
64 error Error: fatal: tag 'logger@0.0.8' already exists
64 error
64 error     at Function.module.exports.sync (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\node_modules\execa\index.js:303:26)
64 error     at Function.execSync (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\ChildProcessUtilities.js:59:30)
64 error     at Function.addTag (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\GitUtilities.js:94:39)
64 error     at C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\commands\PublishCommand.js:728:39
64 error     at Array.forEach (native)
64 error     at PublishCommand.gitCommitAndTagVersionForUpdates (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\commands\PublishCommand.js:727:12)
64 error     at PublishCommand.commitAndTagUpdates (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\commands\PublishCommand.js:702:26)
64 error     at PublishCommand.execute (C:\Program Files (x86)\Nodist\bin\node_modules\lerna\lib\commands\PublishCommand.js:307:14)

```
</p></details>

## Context
This is a deal breaker.
If this cannot be resolved, I'll have to makdo without lerna

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1|
| `npm --version`  | 4.0.5|
| `yarn --version` | n/a|
| `node --version` | 7.2.1|

I'm also using nodist 0.8.8
| OS | Version |
| --- | --- |
| Windows 10 | home x64 |

**Comment by osher** [comment] 2017-11-15 14:02
maybe related to #1116 ?
in both cases I worked with a local git repo without a remote

**Comment by osher** [comment] 2017-11-15 17:38
more info.

I connected a remote to the GIT, you can see it here https://github.com/osher/eval-lerna

I did changes to `logger`, and expected ***only*** `logger` to be published, since semver rules would allow the other projects to accept the new `logger` version.

I switched between indipendent and fixed to see the differences - no differences were observed.
`lerna updated` kept saying that all of them needs publishing.


When I did a change to `orm` - then `orm` was updated, together with `web-one` and `web-two`, while `logger` is not published.

This is sad. when I publish a patch to a lib I do not expect all the web projects to be published.

It might make sense only when publishing with `--exact` wihch (AFAI understand) does not allow range-markers (caret/tilde). But as a default - it's sins to the main premise that caught my attention to this project.

I hope this can be resolved or at least explained 😅

**Comment by evocateur** [comment] 2017-11-15 18:13
If you make changes to a package that is itself a dependency of other sibling packages, then that version is bumped in the consumer packages and is thus a change, hence the new versions for packages that have no diff from the previous tag.

Closing as a duplicate of #886, our reasoning is explained in #707.

A `vnull` tag is probably due to an error during publish prompts, a variation on #853.

**Closed by evocateur** 2017-11-15 18:13 UTC

**Comment by osher** [comment] 2017-11-21 13:15
That is not true.
If the package.json has not changed - and there is no reason that it should change - then this is a version that is needlessly published, a and a needless noise in the changelog entry.
