### ISSUE TITLE
lerna publish PROBLEMS

### ISSUE THREAD

**Issue by Ognian** [lerna/lerna#1009] opened 2017-09-06 15:40 UTC
When working with lerna I found it very confusing how **lerna publish** really works.

according to the documentation it should do the following:
1. Run the equivalent of lerna updated to determine which packages need to be published.
2. If necessary, increment the version key in lerna.json.
3. Update the package.json of all updated packages to their new versions.
4. Update all dependencies of the updated packages with the new versions, specified with a caret (^).
5. Create a new git commit and tag for the new version.
6. Publish updated packages to npm.
Lerna won't publish packages which are marked as private ("private": true in the package.json).

The problems I found are:
ad.1 It detects ONLY changes in the packages directory; root directory changes like package.json or lerna.json changes are NOT detected
ad.5. if the changed files are not staged, they are not committed 

These two make it practically impossible to let lerna publish commit anything into git

ad.6 prepublish scripts are NOT run, or to be more precise npm prepublish scripts are NOT run, actually I see when using --loglevel 99 that an attempt is made to run packages/package_name/scripts/prepublish.js BUT this is NOT what I would expect as a prepublish script in npm context (all of the modules are private, but even npm publish would run the scripts only and not publish...)
 
The only solution for the above problems is do do everything manually and if every thing is OK use ```lerna publish --force-publish``` to generate tags

What do you think? Am I doing something terrible wrong?
Thanks
Ognian

**Comment by ricky** [comment] 2017-09-11 12:12
> ad.1 It detects ONLY changes in the packages directory; root directory changes like package.json or lerna.json changes are NOT detected

That is intentional, as it is only meant to publish packages that live in locations specified by [`lerna.json#packages`](https://github.com/lerna/lerna#lernajson), which defaults to `packages/`. You _can_ add `"."` to this list if it fits your use case. The most common case is probably where all "publishable" packages live under `packages/`, and I think it's worth thinking about whether it would be better to capture these top-level dependency changes that should trigger updates with with a new `private` package under `packages/` instead of in the root `package.json`. That, of course, depends on your specific needs.

> ad.5. if the changed files are not staged, they are not committed

Unless you're using `--skip-git`, changes that `lerna publish` makes _should_ get [committed](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L215-L217) (and [pushed](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L253)). If there were other unstaged/committed local changes, that would be outside the purview of the `publish` command.

Caveat: Since `pushWithTags` is called after a successful npm publish, it [looks like](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L223-L253) it will _not_ push your git changes if you `--skip-npm`.

> ad.6 prepublish scripts are NOT run, or to be more precise [...] an attempt is made to run packages/package_name/scripts/prepublish.js

Looks like you're right about that one: https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L603-L611 
That does seem a bit of an overly specific solution...

**Comment by Ognian** [comment] 2017-09-11 14:22
Thanks for your answer. I start to understand. What I'm actually trying to achieve is to have the git version (tag and hash and dirty or not) of every module displayed into my app. Therefore it is crucial that some steps like tagging, committing and build (prepublish) are done in the right order and as flawless to human error as possible.
actually lerna is doing this quite good...

- regarding the root directory: now knowing this I can live with it the way it is.

- regarding unstaged changes: you are of course right If I do not stage and ```lerna publish``` commits then they will be not included. BUT actually I need to be warned that there are unstaged changes before committing. This is because before committing I either stage the changed files or remove them (or stash them, so that if there are unstaged files when trying to ```lerna publish``` there must be some human error. So maybe lerna publish could check for unstaged files and offer me to continue or not? Is this possible?

- regarding prepublish scripts: I'm intentionally NOT using --skip-npm since even for private packages I want npm publish to be run. npm publish would trigger the prepublish script and only if not private really publish. And my prepublish script actually runs the build, where the git tag, hash and dirty or not is embedded into the app... BUT actually I do not see a reason why npm prepublish scripts are not run since npm publish should be called for private repos too ... Have to try to debug this...

**Comment by Ognian** [comment] 2017-09-11 16:50
Below the log of lerna publish
I don't see that npm publish is actually executed.
Any idea why? Locking thru the code it should be...
Or could it be that the npm output is not logged?
Thanks
Ognian

```
$ lerna publish --message="- updated connect options to match new driver" --loglevel=99
lerna sill input [ 'publish' ]
lerna sill flags { _: [ 'publish' ],
lerna sill flags   message: '- updated connect options to match new driver',
lerna sill flags   m: '- updated connect options to match new driver',
lerna sill flags   loglevel: '99' }
lerna verb rootPath /storage/safe/ogi-it/Projekte/IMS/IMS_v2
lerna info version 2.1.2
lerna sill isInitialized 
lerna sill isInitialized true
lerna sill existsSync /storage/safe/ogi-it/Projekte/IMS/IMS_v2/VERSION
lerna sill initialize attempt
lerna info current version 1.7.9
lerna sill getUpdates 
lerna info Checking for updated packages...
lerna sill hasTags 
lerna verb hasTags true
lerna sill getLastTag 
lerna verb getLastTag v1.7.9
lerna info Comparing with v1.7.9.
lerna sill diffSinceIn v1.7.9 /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/IMS-limsart
lerna sill diff 
lerna sill diffSinceIn v1.7.9 /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/IMS
lerna sill diff packages/IMS/src/crud.js
lerna sill diffSinceIn v1.7.9 /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/LIMS_test
lerna sill diff 
lerna verb updated OGI-IT_IMS
lerna sill collectDependents 
lerna sill isPackageDependentOf OGI-IT_IMS-limsart OGI-IT_IMS
lerna sill isPackageDependentOf OGI-IT_IMS OGI-IT_IMS
lerna sill isPackageDependentOf OGI-IT_IMS-limsart OGI-IT_IMS
lerna sill isPackageDependentOf LIMS_test OGI-IT_IMS
lerna verb dependent LIMS_test depends on OGI-IT_IMS
lerna sill collectUpdates 
lerna verb has filtered update OGI-IT_IMS
lerna verb has filtered update LIMS_test
? Select a new version (currently 1.7.9) Patch (1.7.10)

Changes:
 - OGI-IT_IMS: 1.7.9 => 1.7.10 (private)
 - LIMS_test: 1.7.9 => 1.7.10 (private)

? Are you sure you want to publish the above changes? Yes
lerna sill initialize success
lerna sill execute attempt
lerna sill isDetachedHead 
lerna sill getCurrentBranch 
lerna verb getCurrentBranch master
lerna verb isDetachedHead false
lerna sill addFile /storage/safe/ogi-it/Projekte/IMS/IMS_v2/lerna.json
lerna sill addFile /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/IMS/package.json
lerna sill addFile /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/LIMS_test/package.json
lerna sill commit - updated connect options to match new driver
lerna verb commit [ 'commit',
lerna verb commit   '-m',
lerna verb commit   '- updated connect options to match new driver' ]
lerna sill addTag v1.7.10
lerna info publish Publishing packages to npm...
lerna sill existsSync /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/IMS/scripts/prepublish.js
lerna verb execScript No prepublish script found at /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/IMS/scripts/prepublish.js
lerna sill existsSync /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/LIMS_test/scripts/prepublish.js
lerna verb execScript No prepublish script found at /storage/safe/ogi-it/Projekte/IMS/IMS_v2/packages/LIMS_test/scripts/prepublish.js
lerna info git Pushing tags...
lerna sill pushWithTags [ 'origin', [ 'v1.7.10' ] ]
lerna sill getCurrentBranch 
lerna verb getCurrentBranch master
Successfully published:

lerna success publish finished
lerna sill execute success
```

**Comment by evocateur** [comment] 2017-09-11 17:06
The output of `npm publish` is not forwarded to the parent process (lerna itself). Trust me, the lifecycle scripts are always called, because lerna is only calling `npm publish`. The `scripts/prepublish.js` stuff is a legacy babel thing that I am rather inclined to deprecate/remove in the next few major version releases. It does not replace the lifecycle scripts present in a given `package.json`.

**Comment by evocateur** [comment] 2017-09-11 17:09
You might also consider chaining `lerna bootstrap` before `lerna publish` in a root npm script, as `lerna publish` doesn't really do any validation that things are symlinked and prepared (transpiled, etc). Perhaps even begin the chain with a `git clean -fdx packages` to get super-clean before a release, if that's your jam.

**Comment by Ognian** [comment] 2017-09-11 17:59
@evocateur thanks for your answer. I changed my prepublish script:
```
-    "prepublish": "npm run build",
+    "prepublish": "date | tee -a prepublish_log.txt && npm run build 2>&1 | tee -a prepublish_log.txt",
```
and tested that the prepublish_log.txt is created by running ```npm publish```
BUT when running ```lerna publish --message="- updated scripts" --loglevel=99```
it is definitely NOT run...
Any idea what that could be?

**Comment by evocateur** [comment] 2017-09-11 18:03
I need an example repo with a minimal reproduction to speak further. (also version of node/npm and OS, etc)

**Comment by Ognian** [comment] 2017-09-11 18:14
@evocateur  OK I found it [here](https://github.com/lerna/lerna/blob/0e6a56232aa56ce9473223b8ed5cd4e0d737e022/src/commands/PublishCommand.js#L163) you are filtering the private packages wich should not be done...

**Comment by Ognian** [comment] 2017-09-12 14:58
OK I stiered up a honets nest :-)
After removing the private filter (removing the mentioned line) npm publish is indeed called, but if private=true npm publish is returning an error, therefore lerna is retrying the command and so on and so on...
Actualy what should be documented is that for private packages npm publish is never ever called for npm reasons and if someone wants this he should call the lifecycle methods like```lerna run prepublish``` after ```lerna publish```

**Comment by evocateur** [comment] 2017-09-12 17:01
Yeah, coulda told you private packages are never published. That's the whole point of private packages.

If you need build output for non-private siblings to depend on, run `lerna bootstrap` and that *will* run prepublish/prepare in the private package.

**Closed** 2018-04-13 06:24 UTC
