### ISSUE TITLE
Using yarn and hoisting together causes yarn.lock to be ignored

### ISSUE THREAD

**Issue by ef4** [lerna/lerna#852] opened 2017-05-27 00:47 UTC
If you try to use `--npm-client=yarn` and `--hoist` simultaneously, all your package's `yarn.lock` files will be ignored because `lerna` uses `npm` instead of `yarn` for everything except the top-level hoisted dependencies.

## Expected Behavior

When using `yarn` as the npm client, all installed dependencies should satisfy any `yarn.lock` files that are present.

## Current Behavior

`lerna` invokes `npm --global-style` instead of `yarn` in each of the packages, causing the yarn.lock to be ignored.

## Possible Solution

We could forbid the combination of hoisting and yarn, or at least warn that it will give surprising results.

A more complete solution would mangle the contents of yarn.lock in a way analogous to what `lerna` already does for `package.json` in order to preserve the intended semantics.

## Steps to Reproduce (for bugs)

1. In any lerna project, run `lerna bootstrap --hoist --npm-client=yarn`
2. Observe the resulting processes via `ps` or `pstree` and see that lerna is running `npm` instead of `yarn`.

**Comment by thomasfr** [comment] 2017-06-01 12:46
I can confirm this. We are using `--hoist` and `--npm-client=yarn` together and when doing lerna bootstrap i can see `npm install --global-style`

**Comment by evocateur** [comment] 2017-06-06 17:49
> mangle the contents of yarn.lock

😨  uhhh, pardon my shock, but that's asking us to reverse-engineer `yarn`. Definitely _not_ happening. Warn about `--npm-client=yarn` + `--hoist`, sure, that's possible.

`npm install --global-style` is important to avoid improper transitive dependency resolution for non-hoisted dependencies. If you want to use `yarn` everywhere, `yarn` will have to be extended to support that, which is obviously out of scope for lerna itself.

**Comment by MoOx** [comment] 2017-06-10 22:12
Yarn will have a built in feature, called "workspaces" to offer a lerna like solution. More at https://github.com/yarnpkg/yarn/issues/3294

**Comment by thomasfr** [comment] 2017-06-11 09:18
@evocateur @MoOx Do you know what this would mean to lerna? Would Lerna then be obsolete? Or would Lerna just use this workspaces feature?

**Comment by evocateur** [comment] 2017-06-11 15:43
Workspaces don't manage anything related to version decisions (git stuff, basically), so lerna isn't being replaced entirely. Just as we call out to npm/yarn as much as possible, workspaces will help simplify lerna's logic.

**Comment by jadengore** [comment] 2017-06-20 21:25
So if using `yarn` as the `npmClient`, hoist will use `npm` instead of `yarn` always/

**Comment by evocateur** [comment] 2017-06-20 21:34
If `--hoist` needs to do a leaf install (i.e., there are "unhoisted", possibly conflicting deps in the tree), then it will use `npm` because `yarn` does not support `--global-install`, which avoids leaking transitive dependencies incorrectly.

**Comment by edmorley** [comment] 2017-09-29 20:52
I spent a while trying to debug/create a reduced STR for why using `--hoist` plus yarn caused a `package-lock.json` to be created in one of the sub-package directories. Reading here it seems that yarn + `--hoist` is not recommended.

If that's the case, a warning message during usage would save a lot of confusion :-)

**Comment by evocateur** [comment] 2017-11-20 17:31
#1063 fixed this by making it error when `--npm-client yarn` and `--hoist` are used together, released in v2.5.0.

**Closed by evocateur** 2017-11-20 17:31 UTC
Labels: help wanted
