### ISSUE TITLE
Independent versioning mode

### ISSUE THREAD

**Issue by its-me-dhina** [lerna/lerna#3840] opened 2023-09-16 04:40 UTC
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://lerna.js.org/docs/features/version-and-publish#independent-mode

### Additional context or description

In independent versioning mode, 

- How can I version only a particular package with the help of a scope tag If that is supported?
- Some code examples would be great.

**Comment by mcanelo** [comment] 2023-10-01 11:08
I have the same problem. 

i can't version only one package.

**Comment by fahslaj** [comment] 2023-10-11 18:10
Duplicate of #3853

**Closed by fahslaj** 2023-10-11 18:10 UTC
Labels: type: docs
