### ISSUE TITLE
[Feature] Bootstrap fails to install from private registry

### ISSUE THREAD

**Issue by giladgray** [lerna/lerna#239] opened 2016-06-22 00:18 UTC
we use an internal NPM registry with plenty of internal modules. `npm install` works just fine OOTB because we have an `.npmrc` file in the repo that sets the registry. however, `lerna boostrap` fails to install saying it can't find our internal modules on the public registry (because of course).

```
lerna bootstrap
Lerna v2.0.0-beta.13
Independent Versioning Mode
Linking all dependencies
Errored while running BootstrapCommand.execute
Error: Command failed: /bin/sh -c npm install bourbon@4.2.2 @company/private@0.15.3 angular@>=1.3 classnames@^2.2.5 codemirror@~5.12.0 dom4@^1.8.3 jquery@^2.2.3 normalize.css@3.0.3 plottable@^2.1.0 pure-render-decorator@^1.1.1 react@15.0.1 react-addons-css-transition-group@15.0.1 react-dom@15.0.1 react-select@^1.0.0-beta select2@3.5.2-browserify why-did-you-update@0.0.8
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "bourbon@4.2.2" "@company/private@0.15.3" "angular@" "classnames@^2.2.5" "codemirror@~5.12.0" "dom4@^1.8.3" "jquery@^2.2.3" "normalize.css@3.0.3" "plottable@^2.1.0" "pure-render-decorator@^1.1.1" "react@15.0.1" "react-addons-css-transition-group@15.0.1" "react-dom@15.0.1" "react-select@^1.0.0-beta" "select2@3.5.2-browserify" "why-did-you-update@0.0.8"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Not found : @company/private
npm ERR! 404
npm ERR! 404 '@company/private' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

a quick peek in `npm-debug.log` shows the following lines repeated for each dependency:

```
25 silly mapToRegistry name bourbon
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/bourbon
29 silly fetchNamedPackageData @company/private
30 silly mapToRegistry name @company/private
31 silly mapToRegistry scope (from package name) @company
32 verbose mapToRegistry no registry URL found in name for scope @company
```

**Comment by giladgray** [comment] 2016-06-22 00:23
ok hmm solved by adding `registry` config to my user-wide `~/.npmrc` file. i would expect lerna to support an `.npmrc` file in the project too, but that does not seem to be the case.

**Comment by thejameskyle** [comment] 2016-07-13 19:43
It probably does support it within the individual package directories.

Should it handle it at the top level or should config be added to `lerna.json`?

**Comment by danderu** [comment] 2016-07-14 12:02
@thejameskyle It makes sense, otherwise we have to copy it in every package, which makes no sense :(

**Comment by thejameskyle** [comment] 2016-07-14 18:33
In general I would prefer people put stuff like that in every package. I want to keep it so that you could still `cd packages/package-name && npm version minor && npm publish` and that work fine

**Comment by pgoldrbx** [comment] 2016-07-30 18:49
My use case is identical to @giladgray. I'd like to add that I also use various CI build environments that need to run a full set of install and test scripts, so this needs to work in other environments beyond local development.

It will be extra labor and maintenance to modify all package files/dirs, but, of course, that can be scripted. My expected behavior might be:

* pass explicit CLI args to `lerna bootstrap`
* resolve npm config based on specificity / "nearest"
  * `package.json` config > `package/.npmrc` > root `.npmrc` > `~/.npmrc`
  * npm env vars?
* setting it in `lerna.json` would be redundant (since npm needs it set somewhere anyway) but it would be a workable solution

In the meantime, since I'm working with `lerna` for the first time, I will attempt the per-package `.npmrc` suggestion for starters to at least

**Comment by artisologic** [comment] 2016-11-10 20:40
Hi,

Just switched a 20 odd repo project to lerna the past few days and it looks like I'm hitting the same issue. All of our packages are private npm packages hosted on NPM itself.

All our old repos used to work on our CI environment by adding an `NPM_TOKEN` env variable and then adding this to our `.travis.yml` file:

```yaml
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
```

Since switching to a monorepo using lerna, we use the same technique on travis, and I can see that the top level `npm install` does have access to install some of our private packages, but as soon as `lerna boostrap` executes, lerna seems unable to access our private packages.

```
npm ERR! 404 Not found : @fathom-london/cb-fusion-text
npm ERR! 404 
npm ERR! 404  '@fathom-london/cb-fusion-text' is not in the npm registry.
```

Has anybody found a work around?
We're loving the switch to monorepo so far, but I would hate having to completely disable our CI because of it.

**Comment by doug-wade** [comment] 2017-07-08 16:44
@giladgray I'm fairly certain this was resolved in https://github.com/lerna/lerna/pull/599.  Does that meet your need?

**Comment by joshdick** [comment] 2017-07-24 22:48
FWIW, I was able to work around the issue that seems to be described here by adding this to my `lerna.json` (assuming an `npmClient` of `npm`.) Not super elegant, but it worked:

```json
"npmClientArgs": [
	"--@myCompany:registry=http://some-custom-registry.com"
],
```

**Comment by giladgray** [comment] 2017-07-26 21:17
@doug-wade yeah i'm fairly certain this is working as expected now

**Closed** 2017-08-24 20:11 UTC
Labels: Tag: Enhancement
