### ISSUE TITLE
`publish` should handle failures better

### ISSUE THREAD

**Issue by alexgorbatchev** [lerna/lerna#340] opened 2016-09-13 23:34 UTC
When something happens during the `publish`, in particular if it's during `npm publish`, there's no easy way to rerun `lerna publish` because tags have already been committed. At this point it becomes a HUGE pain in the ass to clean it up, especially if you already have a few hundred tags in the repo.

I think there should be a better way, one or mix of the following:

* continuing interrupted publish
* not making changes unless everything succeded
* a way to clean up interrupted publish

What do you think?

**Comment by rygine** [comment] 2016-09-14 00:36
this is a duplicate of https://github.com/lerna/lerna/issues/56

**Closed** 2016-09-14 03:55 UTC
