### ISSUE TITLE
`npx lerna` fails to run with `undefined` error

### ISSUE THREAD

**Issue by dtbuchholz** [lerna/lerna#4007] opened 2024-05-14 22:09 UTC
## Current Behavior

Can't use lerna with 8.1.3—it crashes with every command that outlines the error `Class extends value undefined is not a constructor or null`.

## Expected Behavior

Commands should work. After downgrading to 8.1.2, everything works again.

## Steps to Reproduce

Run `npx lerna -h` and install the latest lerna version (8.1.3)

### Failure Logs / Configuration

```
> npx lerna -h
/Users/dtb/.npm/_npx/d5cad42883f80c04/node_modules/tar/lib/read-entry.js:97
  [SLURP] (ex, global) {
   ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/dtb/.npm/_npx/d5cad42883f80c04/node_modules/tar/lib/read-entry.js:97:4)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/dtb/.npm/_npx/d5cad42883f80c04/node_modules/tar/lib/pack.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

```

### Environment

- Node v20.11.0
- Mac OS Sonoma 14.3 (23D56)
- Lerna 8.1.3

**Comment by ghiscoding** [comment] 2024-05-16 21:51
duplicate of #4005

**Closed** 2024-05-16 22:36 UTC
Labels: type: bug
