### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by mokone91** [lerna/lerna#3195] opened 2022-06-22 07:54 UTC
Is pnpm support planned?
I happy that to know that Lerna is alive again!
I have several projects that uses lerna, and this will be nice if i can replace npm with pnpm to reduce installation/bootstrap time.

Thanks!

**Comment by mokone91** [comment] 2022-06-24 14:34
https://lerna.js.org/docs/core-concepts/bootstrapping#useworkspaces seems this not working with pnpm..

When running bootstrap with option enabled - getting next error:
`lerna notice cli v5.1.5
lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
`

**Comment by ghiscoding** [comment] 2022-06-27 18:42
duplicate of #1818, I would suggest you to read the last [comment](https://github.com/lerna/lerna/issues/1818#issuecomment-1161974302) I wrote

**Comment by runspired** [comment] 2022-11-04 19:24
`pnpm pack` is not compatible with lerna because lerna still after all these years can't do the most basic thing  of increment the version in the root package.json.

**Comment by JamesHenry** [comment] 2022-11-29 12:01
Hi Folks 👋 Closing this one as pnpm support was added a while ago, thanks all!

**Closed by JamesHenry** 2022-11-29 12:01 UTC
Labels: type: feature
