### ISSUE TITLE
Doesn't link `.bin` files

### ISSUE THREAD

**Issue by tjbenton** [lerna/lerna#274] opened 2016-07-12 19:53 UTC
If a project has a cli for it declared in the `package.json`, it get's ignored during `lerna bootstrap`.

Here's what I expected to get

```bash
├── package-1/
│   ├── bin/
│   │   └── cli-tool
│   ├── index.js
│   └── package.json
└── package-2/
    ├── node_modules/
    │   ├── .bin/
    │   │   └── cli-tool
    │   └── package-1/
    │       ├── index.js
    │       └── package.json
    └── package.json
```pack

**Comment by rygine** [comment] 2016-07-12 23:20
@tjbenton this is fixed via PR #192

**Comment by thejameskyle** [comment] 2016-07-13 19:53
There's a bunch of issues about linking already, closing this

**Closed by thejameskyle** 2016-07-13 19:53 UTC

**Comment by thomasklein** [comment] 2017-01-06 20:31
Hi guys! First of all, thanks for lerna!

@rygine I'm using node 6.6.0, npm 3.10.3 and lerna 2.0.0-beta.31 and the issue is happening to me when another level of nesting is added. 

My setup:

```
package-1
   package.json (dependency: eslint)
package-2
   package.json (dependency package-1)
   package.json.scripts
      "lint": "eslint"
```

In `package-2` no `node_modules/.bin` directory is created and therefore `eslint` is not found. I only get `package-1` symlinked in `package-2/node_modules`.

Why do I even have this setup?  `package-1` should group dependencies - kinda preset style.

**Comment by rygine** [comment] 2017-01-06 22:09
@thomasklein i believe this is working as intended. however, if all dependencies are hoisted, that's a different story. can you post your dependencies for each of those packages, and what kind of bootstrap you are running?

**Comment by thomasklein** [comment] 2017-01-07 00:15
Sure! I forgot to mention that in my case the packages are scoped; although my understanding is that it shouldn't make...

```
package.json
    "dependencies": {
        "lerna": "^2.0.0-beta.31" 
    }
lerna.json
    "lerna": "2.0.0-beta.31",
    "version": "1.0.0"
packages
     @company/package-1
          "version": "1.0.0",
           "dependencies": {
                "eslint": "^3.12.2"
           }
     @company/package-2
          "dependencies": {
               "@company/package-1": "^1.0.0"
          },
          "scripts": {
               "lint": "eslint"
          }
```
(basically what I had posted before)

From within `root`I run `./node/modules/.bin/lerna bootstrap`.

Meanwhile I wrote me shell scripts that creates the symlinks to the "binary" executables on `scripts.postinstall`.
---
System: Mac
node: 6.6.0
npm: 3.10.3

**Comment by rygine** [comment] 2017-01-09 19:00
@thomasklein i think what you're experiencing is the correct behavior. the original issue filed had to do with package binaries (not dependency binaries) being symlink'd.  since each of your packages can operate independent of each other, they should all declare `eslint` as a dependency, if they rely on it.

does that make sense?

**Comment by thomasklein** [comment] 2017-01-10 08:03
Hi Ry! Thanks for taking your time on this, much appreciated!

A pity that the [npm docs](https://docs.npmjs.com/files/package.json#bin) are not really verbose about it...

Setup for a package.json
```
{
  "name": "name",
  "version": "1.0.0",
  "description": "description",
  "dependencies": {
    "eslint": "3.12.1"
  }
}
```

Now if you run `npm install && ls node_modules/.bin` you should get
```
acorn               esvalidate          rimraf
eslint              js-yaml             shjs
esparse             mkdirp              strip-json-comments
```

E.g. `esparse`is only a transitive dependency but nevertheless I have now it's executable available.

In that sense my example is similar, where `eslint`is a transitive dependency and it's exported bin should therefore also be available in the node_module/.bin folder.
