### ISSUE TITLE
@lerna/legacy-package-management missing dependency on rimraf

### ISSUE THREAD

**Issue by keeganstreet** [lerna/lerna#3611] opened 2023-03-24 03:32 UTC
## Current Behavior

Error when running lerna after 6.6.0 release

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin' is not defined by "exports" in node_modules/rimraf/package.json
```

## Expected Behavior

The new @lerna/legacy-package-management module imports from rimraf, so it probably needs to specify rimraf as a dependency to ensure it gets the correct version

```
RIMRAF_CLI = require.resolve("rimraf/bin");
```

**Comment by buffcode** [comment] 2023-03-24 07:52
Error and stack trace:
```
$ /builds/node_modules/.bin/lerna bootstrap
node:internal/modules/cjs/loader:488
      throw e;
      ^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin' is not defined by "exports" in /builds/node_modules/rimraf/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:753:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at libs/core/src/lib/rimraf-dir.ts (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:3574:26)
    at __init (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:10:56)
    at libs/core/src/index.ts (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:3942:5)
    at __init (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:10:56)
    at libs/commands/add/src/command.ts (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:4613:5)
    at __require (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:13:50)
    at Object.<anonymous> (/builds/node_modules/@lerna/legacy-package-management/dist/index.js:4884:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by char0n** [comment] 2023-03-24 08:55
Yep, I can confirm. `6.6.0` is unsable as it tries to import `rimraf/bin` which is not exported by `rimraf` package via `exports` field.

**Comment by HitkoDev** [comment] 2023-03-24 08:58
Is there a way to get rid of `@lerna/legacy-package-management` altogether if I don't need it? As far as I understand it only provides a handful of deprecated commands.

**Comment by tada5hi** [comment] 2023-03-24 11:21
i implemented a hot fix. Hopefully this will be reviewed and merged soon.

**Comment by JamesHenry** [comment] 2023-03-24 14:58
@HitkoDev in v7 of lerna (coming next month) it will no longer be installed by default, and folks would have to opt into it. It needs to stick around until the major release because it's a significant breaking change

**Comment by JamesHenry** [comment] 2023-03-24 14:59
Thanks for the PR @tada5hi I'll take a look!

**Comment by tada5hi** [comment] 2023-03-24 15:54
@JamesHenry I was very happy to do that :v: :relaxed: I hope you can make use of it.

**Comment by JamesHenry** [comment] 2023-03-24 16:16
I'm pleased to say our e2e tests do actually catch this issue: https://github.com/lerna/lerna/pull/3616

It must be that in the workspaces of the folks affected here you are forcing lerna to use rimraf v4 even though it currently depends on v3?

**Closed** 2023-03-24 16:20 UTC
Labels: type: bug

**Comment by char0n** [comment] 2023-03-25 08:59
> It must be that in the workspaces of the folks affected here you are forcing lerna to use rimraf v4 even though it currently depends on v3?

Nope that's not the case. If you do fresh install of lerna, you'll get `rimraf@4.4.1` with it.

```sh
$ npm i --verbose lerna@6.6.1
$ cat ./node_modules/rimraf/package.json
```

**Comment by JamesHenry** [comment] 2023-03-25 09:01
@char0n 6.6.1 was released yesterday after this comment - I upgraded to the latest rimraf as part of the work to fix this issue.

The comment applied to 6.6.0 and earlier

**Comment by char0n** [comment] 2023-03-25 09:11
@JamesHenry,

You're right. Sorry, it failed for 6.6.0 - https://github.com/swagger-api/apidom/pull/2650 and I don't have any `overrides` defined in package.json.

**Comment by JamesHenry** [comment] 2023-03-25 09:13
I guess your direct devDependency on it was somehow enough, strange… anyway glad it’s resolved now!
